// frontend-nuxt/pages/superadmin/tiers/index.vue
<template>
  <div class="space-y-6">
    <!-- Actions -->
    <div class="flex items-center justify-between">
      <h2 class="text-lg font-semibold text-gray-900">Paket Langganan</h2>
      <button @click="openCreateModal" class="h-10 px-4 rounded-xl bg-indigo-600 hover:bg-indigo-500 text-white text-sm font-medium transition-colors flex items-center gap-2">
        <Icon name="lucide:plus" class="w-4 h-4" />
        Tambah Paket
      </button>
    </div>

    <!-- Tier Cards -->
    <div v-if="isLoading" class="flex items-center justify-center py-16">
      <Icon name="lucide:loader-2" class="w-8 h-8 animate-spin text-indigo-600" />
    </div>

    <div v-else-if="tiers?.length" class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
      <div v-for="tier in tiers" :key="tier.id" class="bg-white rounded-2xl card-shadow overflow-hidden">
        <div class="p-6">
          <div class="flex items-center justify-between mb-4">
            <div>
              <h3 class="text-lg font-bold text-gray-900">{{ tier.label }}</h3>
              <p class="text-xs text-gray-400">{{ tier.nama }}</p>
            </div>
            <span :class="[
              'px-2 py-1 text-xs rounded-full font-medium',
              tier.isActive ? 'bg-green-50 text-green-600 border border-green-200' : 'bg-red-50 text-red-600 border border-red-200'
            ]">
              {{ tier.isActive ? 'Aktif' : 'Nonaktif' }}
            </span>
          </div>

          <p class="text-2xl font-bold text-indigo-600 mb-4">
            {{ tier.harga > 0 ? `Rp ${tier.harga.toLocaleString('id-ID')}` : 'Gratis' }}
            <span v-if="tier.harga > 0" class="text-xs text-gray-500 font-normal">/bulan</span>
          </p>

          <div class="space-y-2 text-sm">
            <div class="flex justify-between text-gray-500">
              <span>Max Siswa</span>
              <span class="text-gray-900 font-medium">{{ tier.maxSiswa }}</span>
            </div>
            <div class="flex justify-between text-gray-500">
              <span>Max Guru</span>
              <span class="text-gray-900 font-medium">{{ tier.maxGuru }}</span>
            </div>
            <div class="flex justify-between text-gray-500">
              <span>Max Kelas</span>
              <span class="text-gray-900 font-medium">{{ tier.maxKelas }}</span>
            </div>
            <div class="flex justify-between text-gray-500">
              <span>Max Mapel</span>
              <span class="text-gray-900 font-medium">{{ tier.maxMapel }}</span>
            </div>
            <div class="flex justify-between text-gray-500">
              <span>Max Ujian/bln</span>
              <span class="text-gray-900 font-medium">{{ tier.maxUjian }}</span>
            </div>
            <div class="flex justify-between text-gray-500">
              <span>Storage</span>
              <span class="text-gray-900 font-medium">{{ tier.maxStorage }} MB</span>
            </div>
          </div>

          <div class="flex items-center justify-between mt-4 pt-4 border-t border-gray-100">
            <span class="text-xs text-gray-500">{{ tier._count?.schools ?? 0 }} sekolah</span>
            <div class="flex gap-1">
              <button @click="openEditModal(tier)" class="p-2 rounded-lg hover:bg-gray-100 text-gray-400 hover:text-indigo-600 transition-colors">
                <Icon name="lucide:pencil" class="w-4 h-4" />
              </button>
              <button @click="confirmDelete(tier)" class="p-2 rounded-lg hover:bg-gray-100 text-gray-400 hover:text-red-500 transition-colors">
                <Icon name="lucide:trash-2" class="w-4 h-4" />
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div v-else class="bg-white rounded-2xl card-shadow py-16 text-center">
      <Icon name="lucide:crown" class="w-12 h-12 mx-auto text-gray-300 mb-3" />
      <p class="text-gray-500">Belum ada paket langganan</p>
    </div>

    <!-- Create/Edit Modal -->
    <div v-if="showModal" class="fixed inset-0 bg-black/60 flex items-center justify-center z-50 p-4" @click.self="showModal = false">
      <div class="bg-white rounded-2xl p-6 w-full max-w-lg card-shadow max-h-[90vh] overflow-y-auto">
        <h3 class="text-lg font-semibold text-gray-900 mb-5">{{ editingTier ? 'Edit Paket' : 'Tambah Paket' }}</h3>

        <form @submit.prevent="handleSave" class="space-y-4">
          <div class="grid grid-cols-2 gap-4">
            <div class="space-y-1.5">
              <label class="text-xs font-medium text-gray-400">Nama (slug) *</label>
              <input v-model="tierForm.nama" required placeholder="starter" class="sa-input" />
            </div>
            <div class="space-y-1.5">
              <label class="text-xs font-medium text-gray-400">Label (display) *</label>
              <input v-model="tierForm.label" required placeholder="Starter" class="sa-input" />
            </div>
          </div>

          <div class="grid grid-cols-2 gap-4">
            <div class="space-y-1.5">
              <label class="text-xs font-medium text-gray-400">Harga (IDR/bulan)</label>
              <input v-model.number="tierForm.harga" type="number" min="0" class="sa-input" />
            </div>
            <div class="space-y-1.5">
              <label class="text-xs font-medium text-gray-400">Urutan</label>
              <input v-model.number="tierForm.urutan" type="number" min="0" class="sa-input" />
            </div>
          </div>

          <div class="grid grid-cols-3 gap-4">
            <div class="space-y-1.5">
              <label class="text-xs font-medium text-gray-400">Max Siswa</label>
              <input v-model.number="tierForm.maxSiswa" type="number" min="1" class="sa-input" />
            </div>
            <div class="space-y-1.5">
              <label class="text-xs font-medium text-gray-400">Max Guru</label>
              <input v-model.number="tierForm.maxGuru" type="number" min="1" class="sa-input" />
            </div>
            <div class="space-y-1.5">
              <label class="text-xs font-medium text-gray-400">Max Kelas</label>
              <input v-model.number="tierForm.maxKelas" type="number" min="1" class="sa-input" />
            </div>
          </div>

          <div class="grid grid-cols-3 gap-4">
            <div class="space-y-1.5">
              <label class="text-xs font-medium text-gray-400">Max Mapel</label>
              <input v-model.number="tierForm.maxMapel" type="number" min="1" class="sa-input" />
            </div>
            <div class="space-y-1.5">
              <label class="text-xs font-medium text-gray-400">Max Ujian/bln</label>
              <input v-model.number="tierForm.maxUjian" type="number" min="1" class="sa-input" />
            </div>
            <div class="space-y-1.5">
              <label class="text-xs font-medium text-gray-400">Storage (MB)</label>
              <input v-model.number="tierForm.maxStorage" type="number" min="1" class="sa-input" />
            </div>
          </div>

          <div class="flex items-center gap-2">
            <input type="checkbox" v-model="tierForm.isActive" id="tierActive" class="rounded border-gray-300 bg-white text-indigo-600 focus:ring-indigo-500" />
            <label for="tierActive" class="text-sm text-gray-700">Aktif</label>
          </div>

          <div class="flex justify-end gap-3 pt-2">
            <button type="button" @click="showModal = false" class="px-4 py-2 rounded-xl bg-gray-100 text-gray-700 text-sm hover:bg-gray-200 transition-colors">
              Batal
            </button>
            <button
              type="submit"
              :disabled="isSaving"
              class="px-4 py-2 rounded-xl bg-indigo-600 hover:bg-indigo-500 text-white text-sm font-medium transition-colors disabled:opacity-50 flex items-center gap-2"
            >
              <Icon v-if="isSaving" name="lucide:loader-2" class="w-4 h-4 animate-spin" />
              {{ editingTier ? 'Simpan' : 'Tambah' }}
            </button>
          </div>
        </form>
      </div>
    </div>

    <!-- Delete Confirmation -->
    <div v-if="deleteTarget" class="fixed inset-0 bg-black/60 flex items-center justify-center z-50 p-4" @click.self="deleteTarget = null">
      <div class="bg-white rounded-2xl p-6 w-full max-w-md card-shadow">
        <h3 class="text-lg font-semibold text-gray-900 mb-2">Hapus Paket</h3>
        <p class="text-gray-500 text-sm mb-6">
          Yakin ingin menghapus paket <strong class="text-gray-900">{{ deleteTarget.label }}</strong>?
          <span v-if="deleteTarget._count?.schools > 0" class="text-red-500 block mt-1">
            ⚠ {{ deleteTarget._count.schools }} sekolah masih menggunakan paket ini.
          </span>
        </p>
        <div class="flex justify-end gap-3">
          <button @click="deleteTarget = null" class="px-4 py-2 rounded-xl bg-gray-100 text-gray-700 text-sm hover:bg-gray-200 transition-colors">
            Batal
          </button>
          <button
            @click="handleDelete"
            :disabled="deleteMutation.isPending.value"
            class="px-4 py-2 rounded-xl bg-red-600 hover:bg-red-500 text-white text-sm font-medium transition-colors disabled:opacity-50"
          >
            Hapus
          </button>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { toast } from 'vue-sonner'

definePageMeta({ layout: 'superadmin' })
useHead({ title: 'Paket Langganan - Super Admin' })

const { data: tiers, isLoading } = useSuperAdminTiers()
const createMutation = useCreateTier()
const updateMutation = useUpdateTier()
const deleteMutation = useDeleteTier()

const showModal = ref(false)
const editingTier = ref<any>(null)
const deleteTarget = ref<any>(null)
const isSaving = computed(() => createMutation.isPending.value || updateMutation.isPending.value)

const defaultForm = () => ({
  nama: '', label: '', harga: 0, urutan: 0,
  maxSiswa: 50, maxGuru: 5, maxKelas: 5, maxMapel: 10, maxUjian: 10, maxStorage: 500,
  isActive: true,
})

const tierForm = ref(defaultForm())

const openCreateModal = () => {
  editingTier.value = null
  tierForm.value = defaultForm()
  showModal.value = true
}

const openEditModal = (tier: any) => {
  editingTier.value = tier
  tierForm.value = {
    nama: tier.nama, label: tier.label, harga: tier.harga || 0, urutan: tier.urutan || 0,
    maxSiswa: tier.maxSiswa, maxGuru: tier.maxGuru, maxKelas: tier.maxKelas,
    maxMapel: tier.maxMapel, maxUjian: tier.maxUjian, maxStorage: tier.maxStorage,
    isActive: tier.isActive,
  }
  showModal.value = true
}

const handleSave = async () => {
  if (!tierForm.value.nama || !tierForm.value.label) {
    toast.error('Nama dan label wajib diisi')
    return
  }
  try {
    let result
    if (editingTier.value) {
      result = await updateMutation.mutateAsync({ id: editingTier.value.id, ...tierForm.value })
    } else {
      result = await createMutation.mutateAsync(tierForm.value)
    }
    if (result.success) {
      toast.success(editingTier.value ? 'Paket berhasil diperbarui' : 'Paket berhasil ditambahkan')
      showModal.value = false
    } else {
      toast.error(result.error || 'Gagal menyimpan')
    }
  } catch {
    toast.error('Terjadi kesalahan')
  }
}

const confirmDelete = (tier: any) => {
  deleteTarget.value = tier
}

const handleDelete = async () => {
  if (!deleteTarget.value) return
  try {
    const result = await deleteMutation.mutateAsync(deleteTarget.value.id)
    if (result.success) {
      toast.success('Paket berhasil dihapus')
      deleteTarget.value = null
    } else {
      toast.error(result.error || 'Gagal menghapus')
    }
  } catch {
    toast.error('Terjadi kesalahan')
  }
}
</script>

<style scoped>
.sa-input {
  @apply w-full h-10 px-4 rounded-xl bg-white border border-gray-200 text-gray-900 placeholder-gray-400 text-sm focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:border-transparent transition-all;
}
</style>

// frontend/src/app/superadmin/tiers/page.tsx
"use client";

import { useState } from "react";
import useSWR from "swr";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from "@/components/ui/dialog";
import { Separator } from "@/components/ui/separator";
import { toast } from "sonner";
import { Plus, Pencil, Users, GraduationCap, BookOpen, School, ClipboardList, HardDrive, Loader2, Check, X, Trash2 } from "lucide-react";
import { cn } from "@/lib/utils";

import { superadminFetcher, superadminFetch } from '../_lib/fetcher';

const emptyTier = {
  nama: "", label: "", harga: 0, maxSiswa: 50, maxGuru: 5,
  maxKelas: 5, maxMapel: 10, maxUjian: 10, maxStorage: 500, urutan: 0,
  fipitur: {} as Record<string, boolean>,
};

const PRESET_FEATURES = [
  { key: "ujianOnline", label: "Ujian Online (CBT)" },
  { key: "bankSoal", label: "Bank Soal" },
  { key: "autoGrading", label: "Auto-Grading" },
  { key: "exportPdf", label: "Export PDF" },
  { key: "bulkImport", label: "Bulk Import Data" },
  { key: "aiChatbot", label: "AI Generate Soal" },
  { key: "dashboardAnalitik", label: "Dashboard Analitik" },
  { key: "prioritySupport", label: "Priority Support" },
  { key: "customBranding", label: "Custom Branding" },
  { key: "apiAccess", label: "API Access" },
];

export default function TiersPage() {
  const { data, mutate, isLoading } = useSWR("/api/superadmin/tiers", superadminFetcher);
  const [showDialog, setShowDialog] = useState(false);
  const [editId, setEditId] = useState<string | null>(null);
  const [form, setForm] = useState<any>(emptyTier);
  const [saving, setSaving] = useState(false);
  const [newFeatureKey, setNewFeatureKey] = useState("");
  const [newFeatureLabel, setNewFeatureLabel] = useState("");

  const tiers = data?.data || [];

  // Collect all known feature keys from presets + all tiers
  const allFeatureKeys = new Set<string>(PRESET_FEATURES.map(f => f.key));
  tiers.forEach((tier: any) => {
    if (tier.fipitur && typeof tier.fipitur === "object") {
      Object.keys(tier.fipitur).forEach((k: string) => allFeatureKeys.add(k));
    }
  });

  // Build label map: preset labels + custom keys as-is
  const featureLabelMap: Record<string, string> = {};
  PRESET_FEATURES.forEach(f => { featureLabelMap[f.key] = f.label; });
  allFeatureKeys.forEach(k => { if (!featureLabelMap[k]) featureLabelMap[k] = k; });

  const openCreate = () => {
    setEditId(null);
    setForm({ ...emptyTier, fipitur: {} });
    setShowDialog(true);
  };

  const openEdit = (tier: any) => {
    setEditId(tier.id);
    setForm({
      nama: tier.nama, label: tier.label, harga: tier.harga,
      maxSiswa: tier.maxSiswa, maxGuru: tier.maxGuru, maxKelas: tier.maxKelas,
      maxMapel: tier.maxMapel, maxUjian: tier.maxUjian, maxStorage: tier.maxStorage,
      urutan: tier.urutan,
      fipitur: tier.fipitur || {},
    });
    setShowDialog(true);
  };

  const toggleFeature = (key: string) => {
    const current = form.fipitur || {};
    setForm({ ...form, fipitur: { ...current, [key]: !current[key] } });
  };

  const removeFeature = (key: string) => {
    const current = { ...(form.fipitur || {}) };
    delete current[key];
    setForm({ ...form, fipitur: current });
  };

  const addCustomFeature = () => {
    const key = newFeatureKey.trim().replace(/\s+/g, "");
    if (!key) { toast.error("Key fitur harus diisi"); return; }
    if (form.fipitur?.[key] !== undefined) { toast.error("Fitur sudah ada"); return; }
    setForm({ ...form, fipitur: { ...form.fipitur, [key]: true } });
    if (newFeatureLabel.trim()) {
      featureLabelMap[key] = newFeatureLabel.trim();
    }
    setNewFeatureKey("");
    setNewFeatureLabel("");
  };

  const handleSave = async () => {
    if (!form.nama || !form.label) { toast.error("Nama dan label harus diisi"); return; }
    setSaving(true);
    try {
      const url = "/api/superadmin/tiers";
      const method = editId ? "PUT" : "POST";
      const body = editId ? { id: editId, ...form } : form;

      const res = await fetch(url, {
        method, headers: { "Content-Type": "application/json" },
        credentials: "include", body: JSON.stringify(body),
      });
      const result = await res.json();
      if (result.success) {
        toast.success(result.message);
        mutate();
        setShowDialog(false);
      } else {
        toast.error(result.error);
      }
    } catch { toast.error("Gagal menyimpan tier"); }
    finally { setSaving(false); }
  };

  const formatRupiah = (n: number) => new Intl.NumberFormat("id-ID", { style: "currency", currency: "IDR", minimumFractionDigits: 0 }).format(n);

  const tierColors = ["bg-gray-100 dark:bg-slate-800", "bg-blue-50 dark:bg-blue-900/20", "bg-green-50 dark:bg-green-900/20", "bg-purple-50 dark:bg-purple-900/20", "bg-amber-50 dark:bg-amber-900/20"];

  const getActiveFeatures = (fipitur: Record<string, boolean> | null) => {
    if (!fipitur) return [];
    return Object.entries(fipitur).filter(([, v]) => v).map(([k]) => featureLabelMap[k] || k);
  };

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <h1 className="text-2xl font-bold text-gray-900 dark:text-white">Kelola Tier</h1>
        <Button onClick={openCreate} className="bg-purple-600 hover:bg-purple-700">
          <Plus className="w-4 h-4 mr-2" /> Tambah Tier
        </Button>
      </div>

      {isLoading ? (
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
          {[...Array(3)].map((_, i) => (
            <Card key={i} className="bg-white dark:bg-slate-900 border-gray-200 dark:border-slate-800 animate-pulse">
              <CardContent className="p-6"><div className="h-32" /></CardContent>
            </Card>
          ))}
        </div>
      ) : (
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
          {tiers.map((tier: any, idx: number) => (
            <Card key={tier.id} className={cn("border-gray-200 dark:border-slate-800 relative overflow-hidden", tierColors[idx % tierColors.length])}>
              <CardHeader className="pb-2">
                <div className="flex items-center justify-between">
                  <CardTitle className="text-lg text-gray-900 dark:text-white">{tier.label}</CardTitle>
                  <Button size="icon" variant="ghost" className="h-8 w-8 text-gray-400 hover:text-gray-900 dark:text-slate-400 dark:hover:text-white" onClick={() => openEdit(tier)}>
                    <Pencil className="w-3.5 h-3.5" />
                  </Button>
                </div>
                <p className="text-2xl font-bold text-purple-600 dark:text-purple-400">
                  {tier.harga === 0 ? "Gratis" : formatRupiah(tier.harga)}
                  {tier.harga > 0 && <span className="text-xs font-normal text-gray-400 dark:text-slate-500">/bulan</span>}
                </p>
              </CardHeader>
              <CardContent className="space-y-3">
                <div className="grid grid-cols-2 gap-2 text-sm">
                  <div className="flex items-center gap-1.5 text-gray-600 dark:text-slate-300">
                    <GraduationCap className="w-3.5 h-3.5 text-blue-500" />
                    <span>{tier.maxSiswa >= 99999 ? "∞" : tier.maxSiswa} Siswa</span>
                  </div>
                  <div className="flex items-center gap-1.5 text-gray-600 dark:text-slate-300">
                    <Users className="w-3.5 h-3.5 text-green-500" />
                    <span>{tier.maxGuru >= 99999 ? "∞" : tier.maxGuru} Guru</span>
                  </div>
                  <div className="flex items-center gap-1.5 text-gray-600 dark:text-slate-300">
                    <School className="w-3.5 h-3.5 text-purple-500" />
                    <span>{tier.maxKelas >= 99999 ? "∞" : tier.maxKelas} Kelas</span>
                  </div>
                  <div className="flex items-center gap-1.5 text-gray-600 dark:text-slate-300">
                    <BookOpen className="w-3.5 h-3.5 text-orange-500" />
                    <span>{tier.maxMapel >= 99999 ? "∞" : tier.maxMapel} Mapel</span>
                  </div>
                  <div className="flex items-center gap-1.5 text-gray-600 dark:text-slate-300">
                    <ClipboardList className="w-3.5 h-3.5 text-red-500" />
                    <span>{tier.maxUjian >= 99999 ? "∞" : tier.maxUjian} Ujian</span>
                  </div>
                  <div className="flex items-center gap-1.5 text-gray-600 dark:text-slate-300">
                    <HardDrive className="w-3.5 h-3.5 text-cyan-500" />
                    <span>{tier.maxStorage >= 100000 ? "∞" : `${tier.maxStorage} MB`}</span>
                  </div>
                </div>

                {/* Feature list */}
                {getActiveFeatures(tier.fipitur).length > 0 && (
                  <div className="pt-2 border-t border-gray-200 dark:border-slate-700">
                    <p className="text-xs font-medium text-gray-500 dark:text-slate-400 mb-1.5">Fitur:</p>
                    <div className="flex flex-wrap gap-1">
                      {getActiveFeatures(tier.fipitur).map((f) => (
                        <span key={f} className="inline-flex items-center gap-1 text-xs px-2 py-0.5 rounded-full bg-green-100 text-green-700 dark:bg-green-900/30 dark:text-green-400">
                          <Check className="w-3 h-3" />{f}
                        </span>
                      ))}
                    </div>
                  </div>
                )}

                <div className="pt-2 border-t border-gray-200 dark:border-slate-700">
                  <p className="text-xs text-gray-500 dark:text-slate-400">
                    {tier._count?.schools || 0} sekolah menggunakan tier ini
                  </p>
                </div>
              </CardContent>
            </Card>
          ))}
        </div>
      )}

      <Dialog open={showDialog} onOpenChange={setShowDialog}>
        <DialogContent className="max-w-lg max-h-[90vh] overflow-y-auto">
          <DialogHeader>
            <DialogTitle>{editId ? "Edit Tier" : "Tambah Tier Baru"}</DialogTitle>
            <DialogDescription>Atur batas, harga, dan fitur untuk tier ini</DialogDescription>
          </DialogHeader>
          <div className="space-y-4">
            <div className="grid grid-cols-2 gap-3">
              <div className="space-y-1.5">
                <Label>Nama (slug)</Label>
                <Input placeholder="basic" value={form.nama} onChange={(e) => setForm({ ...form, nama: e.target.value })} disabled={!!editId} />
              </div>
              <div className="space-y-1.5">
                <Label>Label (display)</Label>
                <Input placeholder="Basic" value={form.label} onChange={(e) => setForm({ ...form, label: e.target.value })} />
              </div>
            </div>
            <div className="grid grid-cols-2 gap-3">
              <div className="space-y-1.5">
                <Label>Harga / bulan (IDR)</Label>
                <Input type="number" value={form.harga} onChange={(e) => setForm({ ...form, harga: parseInt(e.target.value) || 0 })} />
              </div>
              <div className="space-y-1.5">
                <Label>Urutan</Label>
                <Input type="number" value={form.urutan} onChange={(e) => setForm({ ...form, urutan: parseInt(e.target.value) || 0 })} />
              </div>
            </div>
            <div className="grid grid-cols-3 gap-3">
              <div className="space-y-1.5">
                <Label>Max Siswa</Label>
                <Input type="number" value={form.maxSiswa} onChange={(e) => setForm({ ...form, maxSiswa: parseInt(e.target.value) || 0 })} />
              </div>
              <div className="space-y-1.5">
                <Label>Max Guru</Label>
                <Input type="number" value={form.maxGuru} onChange={(e) => setForm({ ...form, maxGuru: parseInt(e.target.value) || 0 })} />
              </div>
              <div className="space-y-1.5">
                <Label>Max Kelas</Label>
                <Input type="number" value={form.maxKelas} onChange={(e) => setForm({ ...form, maxKelas: parseInt(e.target.value) || 0 })} />
              </div>
            </div>
            <div className="grid grid-cols-3 gap-3">
              <div className="space-y-1.5">
                <Label>Max Mapel</Label>
                <Input type="number" value={form.maxMapel} onChange={(e) => setForm({ ...form, maxMapel: parseInt(e.target.value) || 0 })} />
              </div>
              <div className="space-y-1.5">
                <Label>Max Ujian</Label>
                <Input type="number" value={form.maxUjian} onChange={(e) => setForm({ ...form, maxUjian: parseInt(e.target.value) || 0 })} />
              </div>
              <div className="space-y-1.5">
                <Label>Storage (MB)</Label>
                <Input type="number" value={form.maxStorage} onChange={(e) => setForm({ ...form, maxStorage: parseInt(e.target.value) || 0 })} />
              </div>
            </div>

            <Separator />

            {/* Dynamic Features */}
            <div className="space-y-3">
              <Label className="text-sm font-semibold">Fitur Tier</Label>
              <p className="text-xs text-muted-foreground">Klik untuk mengaktifkan/menonaktifkan fitur. Gunakan tombol hapus untuk menghapus fitur dari tier ini.</p>

              <div className="space-y-1.5">
                {PRESET_FEATURES.map((pf) => {
                  const isActive = form.fipitur?.[pf.key] === true;
                  return (
                    <div key={pf.key} className="flex items-center justify-between py-1.5 px-2 rounded-md hover:bg-muted/50">
                      <button
                        type="button"
                        onClick={() => toggleFeature(pf.key)}
                        className="flex items-center gap-2 text-sm flex-1 text-left"
                      >
                        <div className={cn(
                          "w-5 h-5 rounded flex items-center justify-center border transition-colors",
                          isActive ? "bg-green-500 border-green-500 text-white" : "border-gray-300 dark:border-slate-600"
                        )}>
                          {isActive && <Check className="w-3 h-3" />}
                        </div>
                        <span className={cn(isActive ? "text-foreground" : "text-muted-foreground")}>{pf.label}</span>
                      </button>
                    </div>
                  );
                })}

                {/* Custom features (non-preset) */}
                {Object.keys(form.fipitur || {}).filter(k => !PRESET_FEATURES.some(pf => pf.key === k)).map((key) => {
                  const isActive = form.fipitur[key] === true;
                  return (
                    <div key={key} className="flex items-center justify-between py-1.5 px-2 rounded-md hover:bg-muted/50">
                      <button
                        type="button"
                        onClick={() => toggleFeature(key)}
                        className="flex items-center gap-2 text-sm flex-1 text-left"
                      >
                        <div className={cn(
                          "w-5 h-5 rounded flex items-center justify-center border transition-colors",
                          isActive ? "bg-green-500 border-green-500 text-white" : "border-gray-300 dark:border-slate-600"
                        )}>
                          {isActive && <Check className="w-3 h-3" />}
                        </div>
                        <span className={cn(isActive ? "text-foreground" : "text-muted-foreground")}>{featureLabelMap[key] || key}</span>
                        <span className="text-xs text-muted-foreground ml-1">(custom)</span>
                      </button>
                      <button type="button" onClick={() => removeFeature(key)} className="text-red-400 hover:text-red-600 p-1">
                        <Trash2 className="w-3.5 h-3.5" />
                      </button>
                    </div>
                  );
                })}
              </div>

              {/* Add custom feature */}
              <div className="flex items-end gap-2 pt-1">
                <div className="flex-1 space-y-1">
                  <Label className="text-xs">Key</Label>
                  <Input
                    placeholder="namaFitur"
                    value={newFeatureKey}
                    onChange={(e) => setNewFeatureKey(e.target.value)}
                    className="h-8 text-sm"
                  />
                </div>
                <div className="flex-1 space-y-1">
                  <Label className="text-xs">Label (opsional)</Label>
                  <Input
                    placeholder="Nama Fitur"
                    value={newFeatureLabel}
                    onChange={(e) => setNewFeatureLabel(e.target.value)}
                    className="h-8 text-sm"
                  />
                </div>
                <Button type="button" size="sm" variant="outline" onClick={addCustomFeature} className="h-8">
                  <Plus className="w-3.5 h-3.5" />
                </Button>
              </div>
            </div>

            <Button onClick={handleSave} disabled={saving} className="w-full bg-purple-600 hover:bg-purple-700">
              {saving ? <Loader2 className="w-4 h-4 mr-2 animate-spin" /> : null}
              {editId ? "Update Tier" : "Buat Tier"}
            </Button>
          </div>
        </DialogContent>
      </Dialog>
    </div>
  );
}
