// frontend-nuxt/pages/guru/ujian/[id]/index.vue
<template>
  <div>
    <!-- Header -->
    <div class="flex items-center justify-between mb-6">
      <div class="flex items-center gap-4">
        <Button
          variant="ghost"
          size="sm"
          icon="lucide:arrow-left"
          @click="navigateTo('/guru/ujian')"
        />
        <div>
          <h1 class="text-2xl font-bold text-gray-900">{{ ujian?.judul || 'Detail Ujian' }}</h1>
          <p class="text-sm text-gray-500">{{ typeof ujian?.mapel === 'object' ? ujian?.mapel?.nama : ujian?.mapel || 'Mata Pelajaran' }}</p>
        </div>
      </div>
      <div class="flex gap-3">
        <Button variant="outline" icon="lucide:printer" :loading="isPrinting" @click="handlePrintSoal">
          Print Soal
        </Button>
        <Button variant="outline" icon="lucide:pencil" @click="navigateTo(`/guru/ujian/${ujianId}/edit`)">
          Edit
        </Button>
        <Button 
          v-if="ujian?.status === 'draft'"
          @click="publishUjian"
          :loading="isPublishing"
          icon="lucide:send"
          class="bg-green-500 hover:bg-green-600 text-white"
        >
          Publish
        </Button>
        <Button 
          v-else-if="ujian?.status === 'active'"
          @click="unpublishUjian"
          :loading="isPublishing"
          variant="outline"
          icon="lucide:pause"
        >
          Unpublish
        </Button>
      </div>
    </div>

    <!-- Loading -->
    <div v-if="isLoading" class="flex items-center justify-center h-64">
      <Icon name="lucide:loader-2" class="w-8 h-8 animate-spin text-orange-500" />
    </div>

    <div v-else class="space-y-6">
      <!-- Info Card -->
      <div class="bg-white rounded-2xl card-shadow p-6">
        <div class="flex items-center justify-between mb-6">
          <h3 class="text-lg font-semibold text-gray-900">Informasi Ujian</h3>
          <span :class="getStatusClass(ujian?.status)">
            {{ getStatusLabel(ujian?.status) }}
          </span>
        </div>

        <div class="grid grid-cols-2 md:grid-cols-4 gap-6">
          <div>
            <p class="text-sm text-gray-500 mb-1">Mata Pelajaran</p>
            <p class="font-medium text-gray-900">{{ typeof ujian?.mapel === 'object' ? ujian?.mapel?.nama : ujian?.mapel || '-' }}</p>
          </div>
          <div>
            <p class="text-sm text-gray-500 mb-1">Kelas</p>
            <p class="font-medium text-gray-900">{{ formatKelas(ujian?.kelas) }}</p>
          </div>
          <div>
            <p class="text-sm text-gray-500 mb-1">Waktu Mulai</p>
            <p class="font-medium text-gray-900">{{ formatDateTime(ujian?.startUjian) }}</p>
          </div>
          <div>
            <p class="text-sm text-gray-500 mb-1">Waktu Selesai</p>
            <p class="font-medium text-gray-900">{{ formatDateTime(ujian?.endUjian) }}</p>
          </div>
        </div>

        <div class="grid grid-cols-2 md:grid-cols-4 gap-6 mt-6 pt-6 border-t border-gray-100">
          <div>
            <p class="text-sm text-gray-500 mb-1">Total Soal</p>
            <p class="text-2xl font-bold text-gray-900">{{ soalList.length }}</p>
          </div>
          <div>
            <p class="text-sm text-gray-500 mb-1">Total Poin</p>
            <p class="text-2xl font-bold text-gray-900">{{ totalPoin }}</p>
          </div>
          <div>
            <p class="text-sm text-gray-500 mb-1">Acak Soal</p>
            <p class="font-medium text-gray-900">{{ ujian?.shuffleQuestions ? 'Ya' : 'Tidak' }}</p>
          </div>
          <div>
            <p class="text-sm text-gray-500 mb-1">Tampilkan Nilai</p>
            <p class="font-medium text-gray-900">{{ ujian?.showScore ? 'Ya' : 'Tidak' }}</p>
          </div>
        </div>

        <div v-if="ujian?.deskripsi" class="mt-6 pt-6 border-t border-gray-100">
          <p class="text-sm text-gray-500 mb-2">Deskripsi</p>
          <div class="prose prose-sm max-w-none" v-html="ujian.deskripsi"></div>
        </div>
      </div>

      <!-- Soal Preview -->
      <div class="bg-white rounded-2xl card-shadow">
        <div class="px-6 py-5 border-b border-gray-100 flex items-center justify-between">
          <h3 class="text-lg font-semibold text-gray-900">Daftar Soal</h3>
          <div class="flex items-center gap-3">
            <label class="flex items-center gap-2 cursor-pointer">
              <input
                type="checkbox"
                v-model="showAnswerKey"
                class="w-4 h-4 text-orange-500 rounded focus:ring-orange-500"
              />
              <span class="text-sm text-gray-600">Tampilkan Kunci Jawaban</span>
            </label>
          </div>
        </div>

        <div class="p-6">
          <div v-if="soalList.length === 0" class="text-center py-12">
            <Icon name="lucide:file-question" class="w-16 h-16 mx-auto text-gray-300 mb-4" />
            <p class="text-gray-500">Belum ada soal</p>
          </div>

          <div v-else class="space-y-6">
            <div 
              v-for="(soal, index) in soalList" 
              :key="soal.id"
              class="border border-gray-200 rounded-xl p-5"
            >
              <!-- Soal Header -->
              <div class="flex items-start justify-between mb-4">
                <div class="flex items-center gap-3">
                  <div class="flex items-center justify-center w-8 h-8 rounded-lg bg-orange-100 text-orange-600 font-semibold text-sm">
                    {{ index + 1 }}
                  </div>
                  <span :class="getTipeBadgeClass(soal.tipe)">
                    {{ getTipeLabel(soal.tipe) }}
                  </span>
                  <span class="text-sm text-gray-500">{{ soal.poin }} poin</span>
                </div>
              </div>

              <!-- Pertanyaan -->
              <div class="mb-4">
                <div class="prose prose-sm max-w-none" v-html="soal.pertanyaan || '<em class=\'text-gray-400\'>Tidak ada pertanyaan</em>'"></div>
              </div>

              <!-- Pilihan Ganda -->
              <div v-if="soal.tipe === 'PILIHAN_GANDA'" class="space-y-2">
                <div 
                  v-for="opsi in (soal.data?.opsi || [])" 
                  :key="opsi.label"
                  :class="[
                    'flex items-center gap-3 p-3 border rounded-lg transition-colors',
                    showAnswerKey && soal.data?.kunciJawaban === opsi.label
                      ? 'bg-green-50 border-green-400'
                      : 'bg-white border-gray-200'
                  ]"
                >
                  <div :class="[
                    'w-5 h-5 rounded-full border-2 flex items-center justify-center',
                    showAnswerKey && soal.data?.kunciJawaban === opsi.label
                      ? 'border-green-500 bg-green-500'
                      : 'border-gray-300'
                  ]">
                    <div v-if="showAnswerKey && soal.data?.kunciJawaban === opsi.label" class="w-2 h-2 rounded-full bg-white"></div>
                  </div>
                  <span :class="[
                    'font-semibold text-sm',
                    showAnswerKey && soal.data?.kunciJawaban === opsi.label ? 'text-green-700' : 'text-gray-700'
                  ]">{{ opsi.label }}.</span>
                  <span 
                    :class="[
                      'text-sm flex-1',
                      showAnswerKey && soal.data?.kunciJawaban === opsi.label ? 'text-green-900' : 'text-gray-700'
                    ]"
                    v-html="opsi.text || '-'"
                  ></span>
                  <Icon 
                    v-if="showAnswerKey && soal.data?.kunciJawaban === opsi.label" 
                    name="lucide:check-circle" 
                    class="w-5 h-5 text-green-600 ml-auto"
                  />
                </div>
              </div>

              <!-- Essay -->
              <div v-if="soal.tipe === 'ESSAY'" class="space-y-3">
                <div class="border-2 border-dashed border-gray-200 rounded-lg p-4 bg-gray-50">
                  <p class="text-sm text-gray-400 italic">Siswa akan menulis jawaban di sini...</p>
                </div>
                <div v-if="showAnswerKey && soal.data?.kunciJawaban" class="p-3 bg-green-50 border border-green-300 rounded-lg">
                  <div class="flex items-center gap-1.5 mb-1.5">
                    <Icon name="lucide:check-circle" class="w-4 h-4 text-green-600" />
                    <p class="text-xs font-semibold text-green-700">Kunci Jawaban</p>
                  </div>
                  <p class="text-sm text-green-900">{{ soal.data.kunciJawaban }}</p>
                </div>
              </div>

              <!-- Isian Singkat -->
              <div v-if="soal.tipe === 'ISIAN_SINGKAT'" class="space-y-3">
                <div class="h-10 bg-white border border-gray-300 rounded-md px-3 flex items-center">
                  <span class="text-sm text-gray-400 italic">Ketik jawaban singkat...</span>
                </div>
                <div v-if="showAnswerKey" class="p-3 bg-green-50 border border-green-300 rounded-lg">
                  <div class="flex items-center gap-1.5 mb-1.5">
                    <Icon name="lucide:check-circle" class="w-4 h-4 text-green-600" />
                    <p class="text-xs font-semibold text-green-700">
                      Jawaban yang Diterima {{ soal.data?.caseSensitive ? '(Case Sensitive)' : '' }}
                    </p>
                  </div>
                  <div class="flex flex-wrap gap-1.5">
                    <span 
                      v-for="(jawaban, idx) in (soal.data?.kunciJawaban || [])" 
                      :key="idx"
                      class="px-2 py-1 text-xs rounded-full bg-green-100 text-green-800"
                    >
                      {{ jawaban || '(kosong)' }}
                    </span>
                  </div>
                </div>
              </div>

              <!-- Benar/Salah -->
              <div v-if="soal.tipe === 'BENAR_SALAH'" class="space-y-3">
                <div class="flex gap-3">
                  <div :class="[
                    'flex-1 p-3 border rounded-lg text-center font-medium',
                    showAnswerKey && soal.data?.kunciJawaban === true
                      ? 'bg-green-50 border-green-400 text-green-700'
                      : 'bg-white border-gray-200 text-gray-700'
                  ]">
                    Benar
                    <Icon v-if="showAnswerKey && soal.data?.kunciJawaban === true" name="lucide:check" class="w-4 h-4 inline ml-1 text-green-600" />
                  </div>
                  <div :class="[
                    'flex-1 p-3 border rounded-lg text-center font-medium',
                    showAnswerKey && soal.data?.kunciJawaban === false
                      ? 'bg-green-50 border-green-400 text-green-700'
                      : 'bg-white border-gray-200 text-gray-700'
                  ]">
                    Salah
                    <Icon v-if="showAnswerKey && soal.data?.kunciJawaban === false" name="lucide:check" class="w-4 h-4 inline ml-1 text-green-600" />
                  </div>
                </div>
              </div>

              <!-- Pencocokan -->
              <div v-if="soal.tipe === 'PENCOCOKAN'" class="space-y-4">
                <div class="grid grid-cols-2 gap-6">
                  <!-- Item Kiri -->
                  <div class="space-y-2">
                    <p class="text-sm font-medium text-gray-700">Item Kiri</p>
                    <div 
                      v-for="(item, idx) in (soal.data?.itemKiri || [])" 
                      :key="item.id || idx"
                      class="flex items-center gap-2 p-3 bg-blue-50 border border-blue-200 rounded-lg"
                    >
                      <span class="w-6 h-6 flex items-center justify-center bg-blue-500 text-white rounded text-xs font-bold">
                        {{ idx + 1 }}
                      </span>
                      <span class="text-sm flex-1" v-html="item.text || '-'"></span>
                    </div>
                  </div>
                  
                  <!-- Item Kanan -->
                  <div class="space-y-2">
                    <p class="text-sm font-medium text-gray-700">Item Kanan</p>
                    <div 
                      v-for="(item, idx) in (soal.data?.itemKanan || [])" 
                      :key="item.id || idx"
                      class="flex items-center gap-2 p-3 bg-green-50 border border-green-200 rounded-lg"
                    >
                      <span class="w-6 h-6 flex items-center justify-center bg-green-500 text-white rounded text-xs font-bold">
                        {{ String.fromCharCode(65 + idx) }}
                      </span>
                      <span class="text-sm flex-1" v-html="item.text || '-'"></span>
                    </div>
                  </div>
                </div>
                
                <!-- Kunci Jawaban Pencocokan -->
                <div v-if="showAnswerKey && soal.data?.jawaban" class="p-4 bg-green-50 border border-green-300 rounded-lg">
                  <div class="flex items-center gap-1.5 mb-3">
                    <Icon name="lucide:check-circle" class="w-4 h-4 text-green-600" />
                    <p class="text-sm font-semibold text-green-700">Kunci Jawaban</p>
                  </div>
                  <div class="flex flex-wrap gap-2">
                    <template v-for="(kananIds, kiriId) in soal.data.jawaban" :key="kiriId">
                      <template v-if="Array.isArray(kananIds)">
                        <div 
                          v-for="kananId in kananIds" 
                          :key="`${kiriId}-${kananId}`"
                          class="flex items-center gap-1 px-2 py-1 bg-white rounded-lg border border-green-300"
                        >
                          <span class="w-5 h-5 flex items-center justify-center bg-blue-500 text-white rounded text-xs font-bold">
                            {{ getKiriIndex(soal.data.itemKiri, kiriId) + 1 }}
                          </span>
                          <Icon name="lucide:arrow-right" class="w-3 h-3 text-green-500" />
                          <span class="w-5 h-5 flex items-center justify-center bg-green-500 text-white rounded text-xs font-bold">
                            {{ String.fromCharCode(65 + getKananIndex(soal.data.itemKanan, kananId)) }}
                          </span>
                        </div>
                      </template>
                      <div 
                        v-else
                        class="flex items-center gap-1 px-2 py-1 bg-white rounded-lg border border-green-300"
                      >
                        <span class="w-5 h-5 flex items-center justify-center bg-blue-500 text-white rounded text-xs font-bold">
                          {{ getKiriIndex(soal.data.itemKiri, kiriId) + 1 }}
                        </span>
                        <Icon name="lucide:arrow-right" class="w-3 h-3 text-green-500" />
                        <span class="w-5 h-5 flex items-center justify-center bg-green-500 text-white rounded text-xs font-bold">
                          {{ String.fromCharCode(65 + getKananIndex(soal.data.itemKanan, kananIds)) }}
                        </span>
                      </div>
                    </template>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { format } from 'date-fns'
import { id as idLocale } from 'date-fns/locale'
import { toast } from 'vue-sonner'

definePageMeta({
  layout: 'guru',
})

useHead({
  title: 'Detail Ujian',
})

const route = useRoute()
const ujianId = route.params.id as string

const { printSoal, isPrinting } = usePrintSoal()

const isLoading = ref(true)
const isPublishing = ref(false)
const showAnswerKey = ref(false)
const ujian = ref<any>(null)
const soalList = ref<any[]>([])

const totalPoin = computed(() => {
  return soalList.value.reduce((sum, soal) => sum + (soal.poin || 0), 0)
})

const formatDateTime = (dateStr: string) => {
  if (!dateStr) return '-'
  return format(new Date(dateStr), 'dd MMM yyyy, HH:mm', { locale: idLocale })
}

const formatKelas = (kelas: any) => {
  if (!kelas) return '-'
  if (Array.isArray(kelas)) return kelas.join(', ')
  return kelas
}

const getStatusClass = (status: string) => {
  const classes: Record<string, string> = {
    draft: 'px-3 py-1 text-sm rounded-full bg-gray-100 text-gray-600',
    aktif: 'px-3 py-1 text-sm rounded-full bg-green-100 text-green-600',
    selesai: 'px-3 py-1 text-sm rounded-full bg-blue-100 text-blue-600',
  }
  return classes[status] || classes.draft
}

const getStatusLabel = (status: string) => {
  const labels: Record<string, string> = {
    draft: 'Draft',
    aktif: 'Aktif',
    selesai: 'Selesai',
  }
  return labels[status] || status
}

const getTipeLabel = (tipe: string) => {
  const labels: Record<string, string> = {
    PILIHAN_GANDA: 'Pilihan Ganda',
    ESSAY: 'Essay',
    ISIAN_SINGKAT: 'Isian Singkat',
    BENAR_SALAH: 'Benar/Salah',
    PENCOCOKAN: 'Pencocokan',
  }
  return labels[tipe] || tipe
}

const getTipeBadgeClass = (tipe: string) => {
  const classes: Record<string, string> = {
    PILIHAN_GANDA: 'px-2 py-1 text-xs rounded-full bg-blue-100 text-blue-700',
    ESSAY: 'px-2 py-1 text-xs rounded-full bg-green-100 text-green-700',
    ISIAN_SINGKAT: 'px-2 py-1 text-xs rounded-full bg-purple-100 text-purple-700',
    BENAR_SALAH: 'px-2 py-1 text-xs rounded-full bg-orange-100 text-orange-700',
    PENCOCOKAN: 'px-2 py-1 text-xs rounded-full bg-pink-100 text-pink-700',
  }
  return classes[tipe] || 'px-2 py-1 text-xs rounded-full bg-gray-100 text-gray-700'
}

const handlePrintSoal = async () => {
  if (soalList.value.length === 0) {
    toast.error('Belum ada soal untuk dicetak')
    return
  }
  const mapelNama = typeof ujian.value?.mapel === 'object' ? ujian.value?.mapel?.nama : ujian.value?.mapel || ''
  const kelas = Array.isArray(ujian.value?.kelas) ? ujian.value.kelas : []
  try {
    await printSoal(
      { judul: ujian.value?.judul || 'Ujian', mapel: mapelNama, kelas },
      soalList.value,
    )
  } catch {
    toast.error('Gagal membuat PDF soal')
  }
}

const publishUjian = async () => {
  isPublishing.value = true
  try {
    const response = await fetchApi(`/api/guru/ujian/${ujianId}`, {
      method: 'PUT',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ status: 'active' }),
    })
    const data = await response.json()
    if (data.success) {
      toast.success('Ujian berhasil dipublish')
      ujian.value.status = 'active'
    } else {
      toast.error(data.error || 'Gagal mempublish ujian')
    }
  } catch (err) {
    toast.error('Terjadi kesalahan')
  } finally {
    isPublishing.value = false
  }
}

const unpublishUjian = async () => {
  isPublishing.value = true
  try {
    const response = await fetchApi(`/api/guru/ujian/${ujianId}`, {
      method: 'PUT',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ status: 'draft' }),
    })
    const data = await response.json()
    if (data.success) {
      toast.success('Ujian berhasil di-unpublish')
      ujian.value.status = 'draft'
    } else {
      toast.error(data.error || 'Gagal mengubah status ujian')
    }
  } catch (err) {
    toast.error('Terjadi kesalahan')
  } finally {
    isPublishing.value = false
  }
}

// Helper functions for pencocokan
const getKiriIndex = (itemKiri: any[], kiriId: string): number => {
  if (!itemKiri) return -1
  return itemKiri.findIndex(item => item.id === kiriId)
}

const getKananIndex = (itemKanan: any[], kananId: string): number => {
  if (!itemKanan) return -1
  return itemKanan.findIndex(item => item.id === kananId)
}

const fetchData = async () => {
  try {
    const [ujianRes, soalRes] = await Promise.all([
      fetchApi(`/api/guru/ujian/${ujianId}`),
      fetchApi(`/api/guru/ujian/${ujianId}/soal`),
    ])

    const ujianData = await ujianRes.json()
    const soalData = await soalRes.json()

    if (ujianData.success && ujianData.data?.ujian) {
      ujian.value = ujianData.data.ujian
    }
    if (soalData.success) {
      soalList.value = soalData.data || []
    }
  } catch (err) {
    console.error('Error fetching data:', err)
  }
}

onMounted(async () => {
  try {
    await fetchData()
  } catch (err) {
    console.error('Error:', err)
  } finally {
    isLoading.value = false
  }
})
</script>

<style scoped>
@media print {
  .card-shadow {
    box-shadow: none !important;
    border: 1px solid #e5e7eb;
  }
}
</style>

// src/app/(main)/guru/ujian/[id]/page.tsx
"use client";

import { useState } from "react";
import useSWR from "swr";
import { useRouter, useParams } from "next/navigation";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { LoadingSpinner } from "@/components/ui/loading-spinner";
import { MathRenderer } from "@/components/ui/math-renderer";
import { useAuth } from "@/hooks/useAuth";
import { ArrowLeft, PencilSimple, ListChecks, Article, TextT, ArrowsLeftRight, CheckCircle, Eye, EyeSlash, Clock, Exam, Printer } from "@phosphor-icons/react";
import { Calendar as CalendarIcon } from "lucide-react";
import { format } from "date-fns";
import { id } from "date-fns/locale";
import { cn } from "@/lib/utils";
import { TIPE_SOAL_LABELS } from "@/types/soal";
import type { PilihanGandaData, EssayData, IsianSingkatData, PencocokanData, BenarSalahData } from "@/types/soal";

const fetcher = async (url: string) => {
  const res = await fetch(url);
  if (!res.ok) throw new Error('Failed to fetch');
  return res.json();
};

const TIPE_ICON: Record<string, React.ReactNode> = {
  PILIHAN_GANDA: <ListChecks className="w-4 h-4" weight="duotone" />,
  ESSAY: <Article className="w-4 h-4" weight="duotone" />,
  ISIAN_SINGKAT: <TextT className="w-4 h-4" weight="duotone" />,
  PENCOCOKAN: <ArrowsLeftRight className="w-4 h-4" weight="duotone" />,
  BENAR_SALAH: <CheckCircle className="w-4 h-4" weight="duotone" />,
};

/**
 * Student-style soal preview with optional answer key overlay.
 * This renders each soal type exactly as students will see it during the exam,
 * with a green overlay showing the correct answer when showKey is true.
 */
function SoalStudentPreview({ soal, showKey }: { soal: any; showKey: boolean }) {
  const data = soal.data;

  switch (soal.tipe) {
    case 'PILIHAN_GANDA': {
      const pgData = data as PilihanGandaData;
      return (
        <div className="space-y-2">
          {pgData.opsi?.map((opsi) => {
            const isAnswer = pgData.kunciJawaban === opsi.label;
            return (
              <div
                key={opsi.label}
                className={cn(
                  "flex items-start gap-3 p-3 sm:p-4 border rounded-lg transition-colors",
                  showKey && isAnswer
                    ? "bg-green-50 border-green-400 ring-2 ring-green-200"
                    : "bg-white border-gray-200 hover:bg-muted/50"
                )}
              >
                <div className={cn(
                  "flex-shrink-0 w-5 h-5 mt-0.5 rounded-full border-2 flex items-center justify-center",
                  showKey && isAnswer
                    ? "border-green-500 bg-green-500"
                    : "border-gray-300"
                )}>
                  {showKey && isAnswer && (
                    <div className="w-2 h-2 rounded-full bg-white" />
                  )}
                </div>
                <div className="flex-1 flex items-center gap-2">
                  <span className={cn(
                    "font-semibold text-sm",
                    showKey && isAnswer ? "text-green-700" : "text-gray-700"
                  )}>{opsi.label}.</span>
                  <MathRenderer content={opsi.text || ""} className={cn(
                    "text-sm",
                    showKey && isAnswer ? "text-green-900" : "text-gray-700"
                  )} />
                </div>
                {showKey && isAnswer && (
                  <CheckCircle className="w-5 h-5 text-green-600 flex-shrink-0" weight="fill" />
                )}
              </div>
            );
          })}
        </div>
      );
    }

    case 'ESSAY': {
      const essayData = data as EssayData;
      return (
        <div className="space-y-3">
          {/* Student view: textarea placeholder */}
          <div className="border-2 border-dashed border-gray-200 rounded-lg p-4 bg-gray-50/50">
            <p className="text-sm text-muted-foreground italic">Siswa akan menulis jawaban di sini...</p>
            <div className="mt-2 h-20 bg-white border border-gray-200 rounded-md" />
          </div>
          {/* Answer key overlay */}
          {showKey && essayData.kunciJawaban && (
            <div className="p-3 bg-green-50 border border-green-300 rounded-lg">
              <div className="flex items-center gap-1.5 mb-1.5">
                <CheckCircle className="w-4 h-4 text-green-600" weight="fill" />
                <p className="text-xs font-semibold text-green-700">Kunci Jawaban</p>
              </div>
              <MathRenderer content={essayData.kunciJawaban} className="text-sm text-green-900" />
            </div>
          )}
        </div>
      );
    }

    case 'ISIAN_SINGKAT': {
      const isianData = data as IsianSingkatData;
      return (
        <div className="space-y-3">
          {/* Student view: input field */}
          <div className="flex items-center gap-2">
            <div className="flex-1 h-10 bg-white border border-gray-300 rounded-md px-3 flex items-center">
              <span className="text-sm text-muted-foreground italic">Ketik jawaban singkat...</span>
            </div>
          </div>
          {/* Answer key overlay */}
          {showKey && (
            <div className="p-3 bg-green-50 border border-green-300 rounded-lg">
              <div className="flex items-center gap-1.5 mb-1.5">
                <CheckCircle className="w-4 h-4 text-green-600" weight="fill" />
                <p className="text-xs font-semibold text-green-700">
                  Jawaban yang Diterima {isianData.caseSensitive ? "(Case Sensitive)" : "(Case Insensitive)"}
                </p>
              </div>
              <div className="flex flex-wrap gap-1.5">
                {isianData.kunciJawaban?.map((jawaban, idx) => (
                  <Badge key={idx} variant="secondary" className="bg-green-100 text-green-800 border-green-200">
                    {jawaban || "(kosong)"}
                  </Badge>
                ))}
              </div>
            </div>
          )}
        </div>
      );
    }

    case 'BENAR_SALAH': {
      const bsData = data as BenarSalahData;
      return (
        <div className="space-y-3">
          {/* Student view: two buttons */}
          <div className="flex gap-3">
            <div className={cn(
              "flex-1 p-4 rounded-lg border-2 text-center font-semibold transition-colors cursor-default",
              showKey && bsData.kunciJawaban === true
                ? "bg-green-50 border-green-400 text-green-700 ring-2 ring-green-200"
                : "bg-white border-gray-200 text-gray-700 hover:bg-muted/50"
            )}>
              <div className="flex items-center justify-center gap-2">
                {showKey && bsData.kunciJawaban === true && (
                  <CheckCircle className="w-5 h-5 text-green-600" weight="fill" />
                )}
                <span>Benar</span>
              </div>
            </div>
            <div className={cn(
              "flex-1 p-4 rounded-lg border-2 text-center font-semibold transition-colors cursor-default",
              showKey && bsData.kunciJawaban === false
                ? "bg-green-50 border-green-400 text-green-700 ring-2 ring-green-200"
                : "bg-white border-gray-200 text-gray-700 hover:bg-muted/50"
            )}>
              <div className="flex items-center justify-center gap-2">
                {showKey && bsData.kunciJawaban === false && (
                  <CheckCircle className="w-5 h-5 text-green-600" weight="fill" />
                )}
                <span>Salah</span>
              </div>
            </div>
          </div>
        </div>
      );
    }

    case 'PENCOCOKAN': {
      const pencocokanData = data as PencocokanData;
      const jawabanEntries = Object.entries(pencocokanData.jawaban || {});
      return (
        <div className="space-y-3">
          {/* Student view: two columns with items to match */}
          <div className="grid grid-cols-2 gap-4">
            {/* Left column */}
            <div className="space-y-2">
              <p className="text-xs font-semibold text-muted-foreground uppercase tracking-wide mb-1">Kolom Kiri</p>
              {pencocokanData.itemKiri?.map((item, idx) => (
                <div key={item.id} className="p-3 bg-blue-50 border border-blue-200 rounded-lg">
                  <div className="flex items-start gap-2">
                    <span className="flex-shrink-0 w-6 h-6 rounded-full bg-blue-200 text-blue-800 flex items-center justify-center text-xs font-bold">
                      {idx + 1}
                    </span>
                    <MathRenderer content={item.text || ""} className="text-sm text-gray-900" />
                  </div>
                </div>
              ))}
            </div>
            {/* Right column */}
            <div className="space-y-2">
              <p className="text-xs font-semibold text-muted-foreground uppercase tracking-wide mb-1">Kolom Kanan</p>
              {pencocokanData.itemKanan?.map((item, idx) => (
                <div key={item.id} className="p-3 bg-orange-50 border border-orange-200 rounded-lg">
                  <div className="flex items-start gap-2">
                    <span className="flex-shrink-0 w-6 h-6 rounded-full bg-orange-200 text-orange-800 flex items-center justify-center text-xs font-bold">
                      {String.fromCharCode(65 + idx)}
                    </span>
                    <MathRenderer content={item.text || ""} className="text-sm text-gray-900" />
                  </div>
                </div>
              ))}
            </div>
          </div>
          {/* Answer key: show connections */}
          {showKey && jawabanEntries.length > 0 && (
            <div className="p-3 bg-green-50 border border-green-300 rounded-lg">
              <div className="flex items-center gap-1.5 mb-2">
                <CheckCircle className="w-4 h-4 text-green-600" weight="fill" />
                <p className="text-xs font-semibold text-green-700">Kunci Jawaban (Pasangan Benar)</p>
              </div>
              <div className="space-y-1.5">
                {jawabanEntries.map(([kiriId, kananId]) => {
                  const kiriItem = pencocokanData.itemKiri?.find(i => i.id === kiriId);
                  const kananItem = pencocokanData.itemKanan?.find(i => i.id === kananId);
                  const kiriIdx = pencocokanData.itemKiri?.findIndex(i => i.id === kiriId) ?? -1;
                  const kananIdx = pencocokanData.itemKanan?.findIndex(i => i.id === kananId) ?? -1;
                  if (!kiriItem || !kananItem) return null;
                  return (
                    <div key={kiriId} className="flex items-center gap-2 text-sm">
                      <span className="flex-shrink-0 w-5 h-5 rounded-full bg-blue-200 text-blue-800 flex items-center justify-center text-xs font-bold">
                        {kiriIdx + 1}
                      </span>
                      <ArrowsLeftRight className="w-3.5 h-3.5 text-green-500 flex-shrink-0" />
                      <span className="flex-shrink-0 w-5 h-5 rounded-full bg-orange-200 text-orange-800 flex items-center justify-center text-xs font-bold">
                        {String.fromCharCode(65 + kananIdx)}
                      </span>
                      <span className="text-green-800 text-xs truncate">
                        {kiriItem.text?.replace(/<[^>]*>/g, '').slice(0, 30)} → {kananItem.text?.replace(/<[^>]*>/g, '').slice(0, 30)}
                      </span>
                    </div>
                  );
                })}
              </div>
            </div>
          )}
          {jawabanEntries.length === 0 && pencocokanData.itemKiri?.length > 0 && (
            <p className="text-sm text-muted-foreground italic">Belum ada koneksi jawaban yang ditentukan</p>
          )}
        </div>
      );
    }

    default:
      return <p className="text-sm text-muted-foreground">Tipe soal tidak dikenali</p>;
  }
}

export default function UjianDetailPage() {
  const router = useRouter();
  const params = useParams();
  const { isLoading: authLoading } = useAuth();
  const [showAnswerKey, setShowAnswerKey] = useState(true);

  const { data, error, isLoading } = useSWR(
    params.id ? `/api/guru/ujian/${params.id}` : null,
    fetcher
  );

  if (authLoading || isLoading) {
    return <LoadingSpinner />;
  }

  if (error) {
    return (
      <div className="flex items-center justify-center h-96">
        <p className="text-red-600">Gagal memuat data ujian</p>
      </div>
    );
  }

  if (!data?.data) {
    return (
      <div className="flex items-center justify-center h-96">
        <p className="text-muted-foreground">Ujian tidak ditemukan</p>
      </div>
    );
  }

  const ujian = data.data.ujian;
  const soalList = data.data.soal || [];
  const totalPoin = soalList.reduce((sum: number, s: any) => sum + (s.poin || 0), 0);
  const durationMinutes = Math.round((new Date(ujian.endUjian).getTime() - new Date(ujian.startUjian).getTime()) / 60000);

  // Count soal by type
  const soalByType: Record<string, number> = {};
  soalList.forEach((s: any) => {
    soalByType[s.tipe] = (soalByType[s.tipe] || 0) + 1;
  });

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div className="flex items-center gap-4">
          <Button
            variant="ghost"
            size="icon"
            onClick={() => router.push("/guru/ujian")}
          >
            <ArrowLeft className="w-5 h-5" weight="bold" />
          </Button>
          <div>
            <h1 className="text-2xl sm:text-3xl font-bold">{ujian.judul}</h1>
            <div className="flex flex-wrap items-center gap-x-3 gap-y-1 text-sm text-muted-foreground mt-1">
              <Badge variant="outline" className="text-xs">{ujian.mapel}</Badge>
              <span>{ujian.kelas.join(", ")}</span>
              <span className={cn(
                "inline-flex items-center px-2 py-0.5 rounded-full text-xs font-medium",
                ujian.status === "aktif" && "bg-green-100 text-green-700",
                ujian.status === "draft" && "bg-orange-100 text-orange-700",
                ujian.status === "selesai" && "bg-gray-100 text-gray-700"
              )}>
                {ujian.status === "aktif" ? "Aktif" : ujian.status === "draft" ? "Draft" : "Selesai"}
              </span>
            </div>
          </div>
        </div>
        <div className="flex gap-2 ml-14 sm:ml-0">
          <Button variant="outline" onClick={() => router.push(`/guru/ujian/${params.id}/print`)}>
            <Printer className="w-4 h-4 mr-2" weight="duotone" />
            Print
          </Button>
          <Button variant="outline" onClick={() => router.push(`/guru/ujian/${params.id}/nilai`)}>
            <Exam className="w-4 h-4 mr-2" weight="duotone" />
            Nilai
          </Button>
          <Button onClick={() => router.push(`/guru/ujian/${params.id}/edit`)}>
            <PencilSimple className="w-4 h-4 mr-2" weight="bold" />
            Edit
          </Button>
        </div>
      </div>

      {/* Stats Cards */}
      <div className="grid gap-3 grid-cols-2 md:grid-cols-4">
        <Card className="border-0 shadow-lg bg-gradient-to-br from-blue-500 to-blue-600">
          <CardContent className="p-4 md:p-6">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-xs md:text-sm font-medium text-blue-100">Jadwal</p>
                <p className="text-lg md:text-2xl font-bold text-white mt-1">
                  {format(new Date(ujian.startUjian), "dd MMM", { locale: id })}
                </p>
                <p className="text-xs text-blue-100 mt-1">
                  {format(new Date(ujian.startUjian), "HH:mm", { locale: id })} - {format(new Date(ujian.endUjian), "HH:mm", { locale: id })}
                </p>
              </div>
              <div className="p-2 md:p-3 bg-white/20 rounded-lg hidden md:block">
                <CalendarIcon className="w-6 h-6 text-white" />
              </div>
            </div>
          </CardContent>
        </Card>

        <Card className="border-0 shadow-lg bg-gradient-to-br from-green-500 to-green-600">
          <CardContent className="p-4 md:p-6">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-xs md:text-sm font-medium text-green-100">Durasi</p>
                <p className="text-2xl md:text-3xl font-bold text-white mt-1">{durationMinutes}</p>
                <p className="text-xs text-green-100 mt-1">menit</p>
              </div>
              <div className="p-2 md:p-3 bg-white/20 rounded-lg hidden md:block">
                <Clock className="w-6 h-6 text-white" weight="duotone" />
              </div>
            </div>
          </CardContent>
        </Card>

        <Card className="border-0 shadow-lg bg-gradient-to-br from-orange-500 to-orange-600">
          <CardContent className="p-4 md:p-6">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-xs md:text-sm font-medium text-orange-100">Total Soal</p>
                <p className="text-2xl md:text-3xl font-bold text-white mt-1">{soalList.length}</p>
                <p className="text-xs text-orange-100 mt-1 hidden md:block">
                  {Object.entries(soalByType).map(([tipe, count]) => (
                    `${count} ${TIPE_SOAL_LABELS[tipe as keyof typeof TIPE_SOAL_LABELS] || tipe}`
                  )).join(" • ")}
                </p>
              </div>
              <div className="p-2 md:p-3 bg-white/20 rounded-lg hidden md:block">
                <ListChecks className="w-6 h-6 text-white" weight="duotone" />
              </div>
            </div>
          </CardContent>
        </Card>

        <Card className="border-0 shadow-lg bg-gradient-to-br from-purple-500 to-purple-600">
          <CardContent className="p-4 md:p-6">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-xs md:text-sm font-medium text-purple-100">Total Poin</p>
                <p className="text-2xl md:text-3xl font-bold text-white mt-1">{totalPoin}</p>
                <p className="text-xs text-purple-100 mt-1">
                  ~{soalList.length > 0 ? Math.round(totalPoin / soalList.length) : 0} poin/soal
                </p>
              </div>
              <div className="p-2 md:p-3 bg-white/20 rounded-lg hidden md:block">
                <Exam className="w-6 h-6 text-white" weight="duotone" />
              </div>
            </div>
          </CardContent>
        </Card>
      </div>

      {/* Description */}
      {ujian.deskripsi && (
        <Card className="border shadow-sm">
          <CardContent className="p-4">
            <p className="text-xs font-semibold text-muted-foreground mb-2">Deskripsi Ujian</p>
            <MathRenderer content={ujian.deskripsi} className="text-sm leading-relaxed" />
          </CardContent>
        </Card>
      )}

      {/* Soal Preview - Student Style */}
      {soalList.length > 0 ? (
        <Card className="border shadow-lg">
          <CardHeader className="pb-3">
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-2">
                <Eye className="w-5 h-5 text-gray-700" weight="duotone" />
                <CardTitle className="text-gray-900">Preview Soal</CardTitle>
                <Badge variant="secondary" className="text-xs">{soalList.length} soal</Badge>
              </div>
              <Button
                variant={showAnswerKey ? "default" : "outline"}
                size="sm"
                onClick={() => setShowAnswerKey(!showAnswerKey)}
                className="gap-1.5"
              >
                {showAnswerKey ? (
                  <>
                    <EyeSlash className="w-4 h-4" weight="duotone" />
                    Sembunyikan Kunci
                  </>
                ) : (
                  <>
                    <Eye className="w-4 h-4" weight="duotone" />
                    Tampilkan Kunci
                  </>
                )}
              </Button>
            </div>
            <p className="text-xs text-muted-foreground mt-1">
              Tampilan ini sama persis dengan yang dilihat siswa saat ujian
            </p>
          </CardHeader>
          <CardContent className="space-y-4">
            {soalList.map((soal: any, index: number) => (
              <div key={soal.id} className="rounded-xl border bg-white shadow-sm overflow-hidden">
                <div className="p-4 sm:p-6 space-y-4">
                  {/* Question header */}
                  <div className="flex items-start gap-3">
                    <span className="flex-shrink-0 w-9 h-9 rounded-full bg-blue-100 text-blue-600 font-bold flex items-center justify-center text-sm">
                      {soal.urutan || index + 1}
                    </span>
                    <div className="flex-1 min-w-0">
                      <div className="flex items-center gap-2 mb-2">
                        <Badge variant="outline" className="text-[10px] gap-1 px-1.5 py-0">
                          {TIPE_ICON[soal.tipe]}
                          {TIPE_SOAL_LABELS[soal.tipe as keyof typeof TIPE_SOAL_LABELS] || soal.tipe}
                        </Badge>
                        <Badge variant="secondary" className="text-[10px] px-1.5 py-0">
                          {soal.poin || 0} poin
                        </Badge>
                      </div>
                      <MathRenderer content={soal.pertanyaan || "(Belum ada pertanyaan)"} className="text-sm sm:text-base text-gray-900" />
                    </div>
                  </div>
                  {/* Answer area - student style */}
                  <div className="ml-12">
                    <SoalStudentPreview soal={soal} showKey={showAnswerKey} />
                  </div>
                </div>
              </div>
            ))}
          </CardContent>
        </Card>
      ) : (
        <Card className="border shadow-lg">
          <CardContent className="flex flex-col items-center justify-center py-16 text-center">
            <ListChecks className="w-16 h-16 text-muted-foreground mb-4" weight="duotone" />
            <h3 className="text-lg font-semibold mb-2">Belum ada soal</h3>
            <p className="text-sm text-muted-foreground mb-6">
              Tambahkan soal melalui halaman edit ujian
            </p>
            <Button onClick={() => router.push(`/guru/ujian/${params.id}/edit`)}>
              <PencilSimple className="w-4 h-4 mr-2" weight="bold" />
              Edit & Tambah Soal
            </Button>
          </CardContent>
        </Card>
      )}
    </div>
  );
}
