// frontend/src/app/(main)/guru/ujian/create/page.tsx
"use client";


import { fetchApi } from '@/lib/fetch-api';
import { fetcherWithAuth } from '@/lib/swr-config';
import { useState } from "react";
import useSWR from "swr";
import { useRouter } from "next/navigation";
import { LoadingSpinner } from "@/components/ui/loading-spinner";
import { useAuth } from "@/hooks/useAuth";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Checkbox } from "@/components/ui/checkbox";
import { Switch } from "@/components/ui/switch";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { TiptapEditorWithToolbar } from "@/components/tiptap";
import { TimePickerIndonesia } from "@/components/ui/time-picker-indonesia";
import { ArrowLeft, Shuffle, Eye, EyeClosed } from "@phosphor-icons/react";
import { toast } from "sonner";

interface ExamInfo {
  judul: string;
  deskripsi: string;
  kelas: string[];
  mapelId: string;
  startUjian: Date;
  endUjian: Date;
  shuffleQuestions: boolean;
  showScore: boolean;
}

export default function CreateUjianPage() {
  const router = useRouter();
  const { isLoading: authLoading } = useAuth();
  const [isSaving, setIsSaving] = useState(false);
  
  const [examInfo, setExamInfo] = useState<ExamInfo>({
    judul: "",
    deskripsi: "",
    kelas: [],
    mapelId: "",
    startUjian: new Date(),
    endUjian: new Date(Date.now() + 90 * 60000),
    shuffleQuestions: false,
    showScore: true,
  });

  const { data, error, isLoading } = useSWR('/api/guru/ujian?status=all', fetcherWithAuth);

  const handleKelasToggle = (kelas: string) => {
    setExamInfo(prev => ({
      ...prev,
      kelas: prev.kelas.includes(kelas)
        ? prev.kelas.filter(k => k !== kelas)
        : [...prev.kelas, kelas]
    }));
  };

  const handleCreate = async () => {
    // Validate
    if (!examInfo.judul || examInfo.kelas.length === 0 || !examInfo.mapelId) {
      toast.error("Mohon lengkapi informasi ujian dan pilih minimal 1 kelas");
      return;
    }

    setIsSaving(true);
    try {
      const response = await fetchApi('/api/guru/ujian', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          ...examInfo,
          status: "draft",
        }),
      });

      const result = await response.json();

      if (response.ok && result.success) {
        toast.success("Ujian berhasil dibuat. Silakan tambahkan soal.");
        // Redirect ke halaman edit untuk tambah soal
        router.push(`/guru/ujian/${result.data.id}/edit`);
      } else {
        toast.error(result.error || "Gagal membuat ujian");
      }
    } catch (error) {
      console.error('Error creating ujian:', error);
      toast.error("Terjadi kesalahan saat membuat ujian");
    } finally {
      setIsSaving(false);
    }
  };

  if (authLoading || isLoading) {
    return <LoadingSpinner />;
  }

  if (error) {
    return (
      <div className="flex items-center justify-center h-96">
        <p className="text-red-600">Gagal memuat data</p>
      </div>
    );
  }

  const kelasList = data?.data?.kelasList || [];
  const mapelList = data?.data?.mapelList || [];

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-4">
          <Button
            variant="ghost"
            size="icon"
            onClick={() => router.push("/guru/ujian")}
          >
            <ArrowLeft className="w-5 h-5" weight="bold" />
          </Button>
          <div>
            <h1 className="text-2xl font-bold">Buat Ujian Baru</h1>
            <p className="text-sm text-muted-foreground">
              Isi informasi dasar ujian, lalu tambahkan soal di halaman berikutnya
            </p>
          </div>
        </div>
        <div className="flex gap-2">
          <Button
            variant="outline"
            onClick={() => router.push("/guru/ujian")}
          >
            Batal
          </Button>
          <Button
            onClick={handleCreate}
            disabled={isSaving}
          >
            {isSaving ? "Membuat..." : "Buat Ujian & Tambah Soal"}
          </Button>
        </div>
      </div>

      {/* Form */}
      <Card>
        <CardHeader>
          <CardTitle>Informasi Ujian</CardTitle>
          <CardDescription>
            Atur detail dan konfigurasi ujian
          </CardDescription>
        </CardHeader>
        <CardContent className="space-y-4">
          <div className="space-y-2">
            <Label htmlFor="judul">Judul Ujian</Label>
            <Input
              id="judul"
              value={examInfo.judul}
              onChange={(e) => setExamInfo({ ...examInfo, judul: e.target.value })}
              placeholder="Contoh: Ulangan Harian Matematika Bab 3"
              className="w-full"
            />
          </div>

          <div className="space-y-2">
            <Label htmlFor="deskripsi">Deskripsi</Label>
            <TiptapEditorWithToolbar
              onChange={(html) => setExamInfo({ ...examInfo, deskripsi: html })}
              content={examInfo.deskripsi}
              placeholder="Deskripsi singkat tentang ujian"
            />
          </div>

          <div className="space-y-2">
            <Label>Kelas (Pilih satu atau lebih)</Label>
            <div className="grid grid-cols-3 gap-3 p-4 border rounded-lg">
              {kelasList.map((kelas: any) => (
                <div key={kelas.id} className="flex items-center space-x-2">
                  <Checkbox
                    id={`create-kelas-${kelas.id}`}
                    checked={examInfo.kelas.includes(kelas.nama)}
                    onCheckedChange={() => handleKelasToggle(kelas.nama)}
                  />
                  <label
                    htmlFor={`create-kelas-${kelas.id}`}
                    className="text-sm font-medium leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70 cursor-pointer"
                  >
                    {kelas.nama}
                  </label>
                </div>
              ))}
            </div>
            {examInfo.kelas.length > 0 && (
              <p className="text-xs text-muted-foreground">
                Dipilih: {examInfo.kelas.join(", ")}
              </p>
            )}
          </div>

          <div className="space-y-4">
            <div className="space-y-2">
              <Label htmlFor="mapel">Mata Pelajaran</Label>
              <Select
                value={examInfo.mapelId}
                onValueChange={(value) => setExamInfo({ ...examInfo, mapelId: value })}
              >
                <SelectTrigger>
                  <SelectValue placeholder="Pilih Mata Pelajaran" />
                </SelectTrigger>
                <SelectContent>
                  {mapelList.map((mapel: any) => (
                    <SelectItem key={mapel.id} value={mapel.id}>
                      {mapel.nama}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              <div className="space-y-2">
                <Label htmlFor="startUjian">Waktu Mulai Ujian</Label>
                <div className="grid grid-cols-2 gap-2">
                  <div className="space-y-1">
                    <Label htmlFor="startDate" className="text-xs text-muted-foreground">Tanggal</Label>
                    <Input
                      id="startDate"
                      type="date"
                      value={(() => {
                        const d = new Date(examInfo.startUjian);
                        const year = d.getFullYear();
                        const month = String(d.getMonth() + 1).padStart(2, '0');
                        const day = String(d.getDate()).padStart(2, '0');
                        return `${year}-${month}-${day}`;
                      })()}
                      onChange={(e) => {
                        if (e.target.value) {
                          const dateStr = e.target.value;
                          const timeStr = (() => {
                            const d = new Date(examInfo.startUjian);
                            return `${String(d.getHours()).padStart(2, '0')}:${String(d.getMinutes()).padStart(2, '0')}`;
                          })();
                          const newDate = new Date(`${dateStr}T${timeStr}`);
                          setExamInfo({ ...examInfo, startUjian: newDate });
                        }
                      }}
                      className="w-full"
                    />
                  </div>
                  <div className="space-y-1">
                    <TimePickerIndonesia
                      value={examInfo.startUjian}
                      onChange={(date) => {
                        setExamInfo({ ...examInfo, startUjian: date });
                      }}
                      placeholder="08:00"
                      label="Waktu (24 jam)"
                    />
                  </div>
                </div>
                <p className="text-xs text-muted-foreground">
                  Format waktu: 24 jam (00:00 - 23:59). Contoh: 14:00 untuk jam 2 siang
                </p>
              </div>

              <div className="space-y-2">
                <Label htmlFor="endUjian">Waktu Akhir Ujian</Label>
                <div className="grid grid-cols-2 gap-2">
                  <div className="space-y-1">
                    <Label htmlFor="endDate" className="text-xs text-muted-foreground">Tanggal</Label>
                    <Input
                      id="endDate"
                      type="date"
                      value={(() => {
                        const d = new Date(examInfo.endUjian);
                        const year = d.getFullYear();
                        const month = String(d.getMonth() + 1).padStart(2, '0');
                        const day = String(d.getDate()).padStart(2, '0');
                        return `${year}-${month}-${day}`;
                      })()}
                      onChange={(e) => {
                        if (e.target.value) {
                          const dateStr = e.target.value;
                          const timeStr = (() => {
                            const d = new Date(examInfo.endUjian);
                            return `${String(d.getHours()).padStart(2, '0')}:${String(d.getMinutes()).padStart(2, '0')}`;
                          })();
                          const newDate = new Date(`${dateStr}T${timeStr}`);
                          setExamInfo({ ...examInfo, endUjian: newDate });
                        }
                      }}
                      className="w-full"
                    />
                  </div>
                  <div className="space-y-1">
                    <TimePickerIndonesia
                      value={examInfo.endUjian}
                      onChange={(date) => {
                        setExamInfo({ ...examInfo, endUjian: date });
                      }}
                      placeholder="09:00"
                      label="Waktu (24 jam)"
                    />
                  </div>
                </div>
                <p className="text-xs text-muted-foreground">
                  Format waktu: 24 jam (00:00 - 23:59). Durasi akan dihitung otomatis.
                </p>
              </div>
            </div>
          </div>

          <div className="space-y-4 pt-4 border-t">
            <h3 className="font-semibold">Pengaturan Ujian</h3>
            
            <div className="flex items-center justify-between p-4 rounded-lg border">
              <div className="flex items-center gap-3">
                <div className="p-2 rounded-lg bg-purple-50">
                  <Shuffle className="w-5 h-5 text-purple-600" weight="duotone" />
                </div>
                <div>
                  <Label htmlFor="shuffle" className="font-medium">Acak Urutan Soal</Label>
                  <p className="text-sm text-muted-foreground">
                    Soal akan ditampilkan secara acak untuk setiap siswa
                  </p>
                </div>
              </div>
              <Switch
                id="shuffle"
                checked={examInfo.shuffleQuestions}
                onCheckedChange={(checked) => setExamInfo({ ...examInfo, shuffleQuestions: checked })}
              />
            </div>

            <div className="flex items-center justify-between p-4 rounded-lg border">
              <div className="flex items-center gap-3">
                <div className="p-2 rounded-lg bg-green-50">
                  {examInfo.showScore ? (
                    <Eye className="w-5 h-5 text-green-600" weight="duotone" />
                  ) : (
                    <EyeClosed className="w-5 h-5 text-gray-600" weight="duotone" />
                  )}
                </div>
                <div>
                  <Label htmlFor="showScore" className="font-medium">Tampilkan Nilai ke Siswa</Label>
                  <p className="text-sm text-muted-foreground">
                    Siswa dapat melihat nilai setelah menyelesaikan ujian
                  </p>
                </div>
              </div>
              <Switch
                id="showScore"
                checked={examInfo.showScore}
                onCheckedChange={(checked) => setExamInfo({ ...examInfo, showScore: checked })}
              />
            </div>
          </div>
        </CardContent>
      </Card>
    </div>
  );
}

// frontend-nuxt/pages/guru/ujian/create.vue
<template>
  <div>
    <!-- Header -->
    <div class="flex items-center justify-between mb-6">
      <div class="flex items-center gap-4">
        <Button
          variant="ghost"
          size="sm"
          icon="lucide:arrow-left"
          @click="navigateTo('/guru/ujian')"
        />
        <div>
          <h1 class="text-2xl font-bold text-gray-900">Buat Ujian Baru</h1>
          <p class="text-sm text-gray-500">Isi informasi dasar ujian, lalu tambahkan soal di halaman berikutnya</p>
        </div>
      </div>
      <div class="flex gap-3">
        <Button variant="outline" @click="navigateTo('/guru/ujian')">
          Batal
        </Button>
        <Button :loading="isSaving" @click="handleCreate">
          Buat Ujian & Tambah Soal
        </Button>
      </div>
    </div>

    <!-- Loading -->
    <div v-if="isLoading" class="flex items-center justify-center h-64">
      <Icon name="lucide:loader-2" class="w-8 h-8 animate-spin text-orange-500" />
    </div>

    <!-- Form -->
    <div v-else class="bg-white rounded-2xl card-shadow">
      <div class="px-6 py-5 border-b border-gray-100">
        <h3 class="text-lg font-semibold text-gray-900">Informasi Ujian</h3>
        <p class="text-sm text-gray-500">Atur detail dan konfigurasi ujian</p>
      </div>
      
      <div class="p-6 space-y-6">
        <!-- Judul -->
        <div class="space-y-2">
          <Label>Judul Ujian *</Label>
          <Input 
            v-model="form.judul" 
            placeholder="Contoh: Ulangan Harian Matematika Bab 3"
            icon="lucide:file-text"
          />
        </div>

        <!-- Deskripsi -->
        <div class="space-y-2">
          <Label>Deskripsi</Label>
          <TiptapEditor 
            v-model="form.deskripsi" 
            placeholder="Deskripsi singkat tentang ujian..."
          />
        </div>

        <!-- Kelas Selection -->
        <div class="space-y-3">
          <Label>Kelas (Pilih satu atau lebih) *</Label>
          <div class="border border-gray-200 rounded-xl p-4">
            <div v-if="kelasList.length === 0" class="text-sm text-gray-500">
              Tidak ada kelas tersedia
            </div>
            <div v-else class="grid grid-cols-3 gap-3">
              <div 
                v-for="kelas in kelasList" 
                :key="kelas.id" 
                class="flex items-center gap-3"
              >
                <input
                  type="checkbox"
                  :id="`kelas-${kelas.id}`"
                  :checked="form.kelas.includes(kelas.nama)"
                  @change="toggleKelas(kelas.nama)"
                  class="w-4 h-4 text-orange-500 rounded focus:ring-orange-500"
                />
                <label :for="`kelas-${kelas.id}`" class="text-sm cursor-pointer">
                  {{ kelas.nama }}
                </label>
              </div>
            </div>
          </div>
          <p v-if="form.kelas.length > 0" class="text-xs text-orange-600">
            Dipilih: {{ form.kelas.join(', ') }}
          </p>
        </div>

        <!-- Mata Pelajaran -->
        <div class="space-y-2">
          <Label>Mata Pelajaran *</Label>
          <select 
            v-model="form.mapelId"
            class="w-full px-4 py-2.5 border border-gray-200 rounded-xl text-sm focus:outline-none focus:ring-2 focus:ring-orange-500/20 focus:border-orange-500"
          >
            <option value="">Pilih Mata Pelajaran</option>
            <option v-for="mapel in mapelList" :key="mapel.id" :value="mapel.id">
              {{ mapel.nama }}
            </option>
          </select>
        </div>

        <!-- Waktu Ujian -->
        <div class="grid grid-cols-2 gap-6">
          <div class="space-y-2">
            <Label>Waktu Mulai Ujian *</Label>
            <div class="grid grid-cols-2 gap-2">
              <div class="space-y-1">
                <span class="text-xs text-gray-500">Tanggal</span>
                <Input 
                  v-model="startDate" 
                  type="date"
                />
              </div>
              <div class="space-y-1">
                <span class="text-xs text-gray-500">Waktu</span>
                <Input 
                  v-model="startTime" 
                  type="time"
                />
              </div>
            </div>
          </div>

          <div class="space-y-2">
            <Label>Waktu Akhir Ujian *</Label>
            <div class="grid grid-cols-2 gap-2">
              <div class="space-y-1">
                <span class="text-xs text-gray-500">Tanggal</span>
                <Input 
                  v-model="endDate" 
                  type="date"
                />
              </div>
              <div class="space-y-1">
                <span class="text-xs text-gray-500">Waktu</span>
                <Input 
                  v-model="endTime" 
                  type="time"
                />
              </div>
            </div>
          </div>
        </div>

        <!-- Pengaturan Ujian -->
        <div class="space-y-4 pt-4 border-t border-gray-100">
          <h3 class="font-semibold text-gray-900">Pengaturan Ujian</h3>
          
          <!-- Acak Soal -->
          <div class="flex items-center justify-between p-4 rounded-xl border border-gray-200">
            <div class="flex items-center gap-3">
              <div class="w-10 h-10 rounded-xl bg-purple-100 flex items-center justify-center">
                <Icon name="lucide:shuffle" class="w-5 h-5 text-purple-600" />
              </div>
              <div>
                <p class="font-medium text-gray-900">Acak Urutan Soal</p>
                <p class="text-sm text-gray-500">Soal akan ditampilkan secara acak untuk setiap siswa</p>
              </div>
            </div>
            <label class="relative inline-flex items-center cursor-pointer">
              <input 
                type="checkbox" 
                v-model="form.shuffleQuestions" 
                class="sr-only peer"
              />
              <div class="w-11 h-6 bg-gray-200 peer-focus:outline-none peer-focus:ring-4 peer-focus:ring-orange-300 rounded-full peer peer-checked:after:translate-x-full peer-checked:after:border-white after:content-[''] after:absolute after:top-[2px] after:left-[2px] after:bg-white after:border-gray-300 after:border after:rounded-full after:h-5 after:w-5 after:transition-all peer-checked:bg-orange-500"></div>
            </label>
          </div>

          <!-- Tampilkan Nilai -->
          <div class="flex items-center justify-between p-4 rounded-xl border border-gray-200">
            <div class="flex items-center gap-3">
              <div class="w-10 h-10 rounded-xl bg-green-100 flex items-center justify-center">
                <Icon :name="form.showScore ? 'lucide:eye' : 'lucide:eye-off'" class="w-5 h-5 text-green-600" />
              </div>
              <div>
                <p class="font-medium text-gray-900">Tampilkan Nilai ke Siswa</p>
                <p class="text-sm text-gray-500">Siswa dapat melihat nilai setelah menyelesaikan ujian</p>
              </div>
            </div>
            <label class="relative inline-flex items-center cursor-pointer">
              <input 
                type="checkbox" 
                v-model="form.showScore" 
                class="sr-only peer"
              />
              <div class="w-11 h-6 bg-gray-200 peer-focus:outline-none peer-focus:ring-4 peer-focus:ring-orange-300 rounded-full peer peer-checked:after:translate-x-full peer-checked:after:border-white after:content-[''] after:absolute after:top-[2px] after:left-[2px] after:bg-white after:border-gray-300 after:border after:rounded-full after:h-5 after:w-5 after:transition-all peer-checked:bg-orange-500"></div>
            </label>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { toast } from 'vue-sonner'

definePageMeta({
  layout: 'guru',
})

useHead({
  title: 'Buat Ujian Baru',
})

const router = useRouter()
const isLoading = ref(true)
const isSaving = ref(false)

const kelasList = ref<any[]>([])
const mapelList = ref<any[]>([])

// Form data
const form = ref({
  judul: '',
  deskripsi: '',
  kelas: [] as string[],
  mapelId: '',
  shuffleQuestions: false,
  showScore: true,
})

// Date/time inputs
const now = new Date()
const startDate = ref(formatDateInput(now))
const startTime = ref(formatTimeInput(now))
const endDate = ref(formatDateInput(new Date(now.getTime() + 90 * 60000)))
const endTime = ref(formatTimeInput(new Date(now.getTime() + 90 * 60000)))

function formatDateInput(date: Date) {
  const year = date.getFullYear()
  const month = String(date.getMonth() + 1).padStart(2, '0')
  const day = String(date.getDate()).padStart(2, '0')
  return `${year}-${month}-${day}`
}

function formatTimeInput(date: Date) {
  const hours = String(date.getHours()).padStart(2, '0')
  const minutes = String(date.getMinutes()).padStart(2, '0')
  return `${hours}:${minutes}`
}

const toggleKelas = (kelasNama: string) => {
  const idx = form.value.kelas.indexOf(kelasNama)
  if (idx === -1) {
    form.value.kelas.push(kelasNama)
  } else {
    form.value.kelas.splice(idx, 1)
  }
}

const handleCreate = async () => {
  // Validate
  if (!form.value.judul) {
    toast.error('Judul ujian wajib diisi')
    return
  }
  if (form.value.kelas.length === 0) {
    toast.error('Pilih minimal 1 kelas')
    return
  }
  if (!form.value.mapelId) {
    toast.error('Pilih mata pelajaran')
    return
  }

  // Build datetime as local string (Jakarta time) — do NOT convert to UTC
  const startUjian = `${startDate.value}T${startTime.value}`
  const endUjian = `${endDate.value}T${endTime.value}`

  if (new Date(endUjian) <= new Date(startUjian)) {
    toast.error('Waktu akhir harus lebih besar dari waktu mulai')
    return
  }

  isSaving.value = true
  try {
    const response = await fetchApi('/api/guru/ujian', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        judul: form.value.judul,
        deskripsi: form.value.deskripsi,
        kelas: form.value.kelas,
        mapelId: form.value.mapelId,
        startUjian,
        endUjian,
        shuffleQuestions: form.value.shuffleQuestions,
        showScore: form.value.showScore,
        status: 'draft',
      }),
    })

    const data = await response.json()

    if (data.success) {
      toast.success('Ujian berhasil dibuat. Silakan tambahkan soal.')
      navigateTo(`/guru/ujian/${data.data.id}/edit`)
    } else {
      toast.error(data.error || 'Gagal membuat ujian')
    }
  } catch (err) {
    console.error('Error creating ujian:', err)
    toast.error('Terjadi kesalahan saat membuat ujian')
  } finally {
    isSaving.value = false
  }
}

const fetchData = async () => {
  try {
    // Try to get kelas and mapel from guru/ujian endpoint first
    const response = await fetchApi('/api/guru/ujian?status=all')
    const data = await response.json()
    
    if (data.success) {
      kelasList.value = data.data?.kelasList || []
      mapelList.value = data.data?.mapelList || []
    }
    
    // If lists are empty, fetch them separately from admin endpoints
    if (kelasList.value.length === 0) {
      try {
        const kelasRes = await fetchApi('/api/admin/kelas')
        const kelasData = await kelasRes.json()
        if (kelasData.success) {
          kelasList.value = kelasData.data || []
        }
      } catch (e) {
        console.error('Error fetching kelas:', e)
      }
    }
    
    if (mapelList.value.length === 0) {
      try {
        const mapelRes = await fetchApi('/api/admin/mapel')
        const mapelData = await mapelRes.json()
        if (mapelData.success) {
          mapelList.value = mapelData.data || []
        }
      } catch (e) {
        console.error('Error fetching mapel:', e)
      }
    }
  } catch (err) {
    console.error('Error fetching data:', err)
  }
}

onMounted(async () => {
  try {
    await fetchData()
  } catch (err) {
    console.error('Error:', err)
  } finally {
    isLoading.value = false
  }
})
</script>
