// frontend/src/app/(main)/admin/guru/page.tsx
"use client";


import { fetchApi } from '@/lib/fetch-api';
import { useState } from "react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { Plus, Pencil, Trash2, Search, BookOpen, Users, CheckCircle, XCircle } from "lucide-react";
import { toast } from "sonner";
import { useGuru, useMapel, useKelas } from "@/hooks/useSWR";
import { LoadingSpinner, ErrorState } from "@/components/ui/loading-spinner";
import { DeleteConfirmationModal } from "@/components/ui/delete-confirmation-modal";
import { Checkbox } from "@/components/ui/checkbox";
import { Badge } from "@/components/ui/badge";

export default function GuruPage() {
  const [selectedMapel, setSelectedMapel] = useState<string>("all");
  const { data: guruData, isLoading, mutate } = useGuru(selectedMapel);
  const { data: mapelData, isLoading: mapelLoading } = useMapel();
  const { data: kelasData, isLoading: kelasLoading } = useKelas();
  
  const [isDialogOpen, setIsDialogOpen] = useState(false);
  const [editingGuru, setEditingGuru] = useState<any | null>(null);
  const [searchQuery, setSearchQuery] = useState("");
  const [deleteModal, setDeleteModal] = useState<{ open: boolean; guru: any | null }>({
    open: false,
    guru: null,
  });
  const [formData, setFormData] = useState({
    nipUsername: "",
    nama: "",
    email: "",
    alamat: "",
    jenisKelamin: "L",
    isActive: true,
    mapelIds: [] as string[],
    kelasIds: [] as string[],
  });

  if (isLoading || mapelLoading || kelasLoading) {
    return <LoadingSpinner />;
  }

  const guru = (guruData as any)?.data || [];
  const mapelList = (mapelData as any)?.data || [];
  const kelasList = (kelasData as any)?.data || [];

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    
    try {
      const method = editingGuru ? 'PUT' : 'POST';
      const payload = editingGuru ? { id: editingGuru.id, ...formData } : formData;
      
      const response = await fetchApi('/api/guru', {
        method,
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(payload),
      });

      if (response.ok) {
        toast.success(editingGuru ? "Data guru berhasil diperbarui" : "Guru berhasil ditambahkan");
        mutate();
        setIsDialogOpen(false);
        resetForm();
      } else {
        const errorData = await response.json();
        toast.error(errorData.error || "Gagal menyimpan data guru");
      }
    } catch (error) {
      toast.error("Terjadi kesalahan");
    }
  };

  const handleEdit = (g: any) => {
    setEditingGuru(g);
    setFormData({
      nipUsername: g.nipUsername || "",
      nama: g.nama || "",
      email: g.email || "",
      alamat: g.alamat || "",
      jenisKelamin: g.jenisKelamin || "L",
      isActive: g.isActive !== undefined ? g.isActive : true,
      mapelIds: g.mapel?.map((m: any) => m.mapelId) || [],
      kelasIds: g.kelas?.map((k: any) => k.kelasId) || [],
    });
    setIsDialogOpen(true);
  };

  const handleDelete = async () => {
    if (!deleteModal.guru) return;
    
    try {
      const response = await fetchApi(`/api/guru?id=${deleteModal.guru.id}`, {
        method: 'DELETE',
      });

      if (response.ok) {
        toast.success("Guru berhasil dihapus");
        mutate();
        setDeleteModal({ open: false, guru: null });
      } else {
        toast.error("Gagal menghapus guru");
      }
    } catch (error) {
      toast.error("Terjadi kesalahan");
    }
  };

  const openDeleteModal = (guru: any) => {
    setDeleteModal({ open: true, guru });
  };

  const resetForm = () => {
    setFormData({
      nipUsername: "",
      nama: "",
      email: "",
      alamat: "",
      jenisKelamin: "L",
      isActive: true,
      mapelIds: [],
      kelasIds: [],
    });
    setEditingGuru(null);
  };

  const toggleMapel = (mapelId: string) => {
    setFormData(prev => ({
      ...prev,
      mapelIds: prev.mapelIds.includes(mapelId)
        ? prev.mapelIds.filter(id => id !== mapelId)
        : [...prev.mapelIds, mapelId]
    }));
  };

  const toggleKelas = (kelasId: string) => {
    setFormData(prev => ({
      ...prev,
      kelasIds: prev.kelasIds.includes(kelasId)
        ? prev.kelasIds.filter(id => id !== kelasId)
        : [...prev.kelasIds, kelasId]
    }));
  };

  const filteredGuru = guru.filter((g: any) =>
    g.nama?.toLowerCase().includes(searchQuery.toLowerCase()) ||
    g.nipUsername?.includes(searchQuery) ||
    g.email?.toLowerCase().includes(searchQuery.toLowerCase())
  );

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-3xl font-bold">Data Guru</h1>
          <p className="text-muted-foreground">Kelola data guru sekolah</p>
        </div>
        <Button onClick={() => { resetForm(); setIsDialogOpen(true); }}>
          <Plus className="mr-2 h-4 w-4" />
          Tambah Guru
        </Button>
      </div>

      <Card>
        <CardHeader>
          <CardTitle>Daftar Guru</CardTitle>
          <div className="flex gap-4 mt-4">
            <div className="flex-1">
              <div className="relative">
                <Search className="absolute left-3 top-3 h-4 w-4 text-muted-foreground" />
                <Input
                  placeholder="Cari guru..."
                  value={searchQuery}
                  onChange={(e) => setSearchQuery(e.target.value)}
                  className="pl-10"
                />
              </div>
            </div>
          </div>
        </CardHeader>
        <CardContent>
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead>NIP/Username</TableHead>
                <TableHead>Nama</TableHead>
                <TableHead>Email</TableHead>
                <TableHead>Jenis Kelamin</TableHead>
                <TableHead>Mata Pelajaran</TableHead>
                <TableHead>Kelas</TableHead>
                <TableHead>Status</TableHead>
                <TableHead className="text-right">Aksi</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {filteredGuru.length === 0 ? (
                <TableRow>
                  <TableCell colSpan={8} className="text-center text-muted-foreground">
                    Tidak ada data guru
                  </TableCell>
                </TableRow>
              ) : (
                filteredGuru.map((g: any) => (
                  <TableRow key={g.id}>
                    <TableCell className="font-mono">{g.nipUsername}</TableCell>
                    <TableCell className="font-medium">{g.nama}</TableCell>
                    <TableCell>{g.email}</TableCell>
                    <TableCell>{g.jenisKelamin === 'L' ? 'Laki-laki' : 'Perempuan'}</TableCell>
                    <TableCell>
                      <div className="flex flex-wrap gap-1">
                        {g.mapel && g.mapel.length > 0 ? (
                          g.mapel.map((m: any) => (
                            <Badge key={m.id} variant="secondary" className="text-xs">
                              <BookOpen className="h-3 w-3 mr-1" />
                              {m.mapel?.nama}
                            </Badge>
                          ))
                        ) : (
                          <span className="text-muted-foreground text-sm">-</span>
                        )}
                      </div>
                    </TableCell>
                    <TableCell>
                      <div className="flex flex-wrap gap-1">
                        {g.kelas && g.kelas.length > 0 ? (
                          g.kelas.map((k: any) => (
                            <Badge key={k.id} variant="outline" className="text-xs">
                              <Users className="h-3 w-3 mr-1" />
                              {k.kelas?.nama}
                            </Badge>
                          ))
                        ) : (
                          <span className="text-muted-foreground text-sm">-</span>
                        )}
                      </div>
                    </TableCell>
                    <TableCell>
                      {g.isActive ? (
                        <Badge variant="default" className="gap-1">
                          <CheckCircle className="h-3 w-3" />
                          Aktif
                        </Badge>
                      ) : (
                        <Badge variant="destructive" className="gap-1">
                          <XCircle className="h-3 w-3" />
                          Nonaktif
                        </Badge>
                      )}
                    </TableCell>
                    <TableCell className="text-right">
                      <div className="flex justify-end gap-2">
                        <Button variant="ghost" size="sm" onClick={() => handleEdit(g)}>
                          <Pencil className="h-4 w-4" />
                        </Button>
                        <Button variant="ghost" size="sm" onClick={() => openDeleteModal(g)}>
                          <Trash2 className="h-4 w-4" />
                        </Button>
                      </div>
                    </TableCell>
                  </TableRow>
                ))
              )}
            </TableBody>
          </Table>
        </CardContent>
      </Card>

      <Dialog open={isDialogOpen} onOpenChange={setIsDialogOpen}>
        <DialogContent className="max-w-4xl max-h-[90vh] overflow-y-auto">
          <DialogHeader>
            <DialogTitle>{editingGuru ? "Edit Guru" : "Tambah Guru Baru"}</DialogTitle>
            <DialogDescription>
              {editingGuru ? "Perbarui data guru" : "Tambahkan guru baru ke sistem"}
            </DialogDescription>
          </DialogHeader>
          <form onSubmit={handleSubmit} className="space-y-6">
            <div className="grid grid-cols-2 gap-4">
              <div className="space-y-2">
                <Label htmlFor="nipUsername">NIP / Username *</Label>
                <Input
                  id="nipUsername"
                  placeholder="Contoh: 198501012010011001 atau username_guru"
                  value={formData.nipUsername}
                  onChange={(e) => setFormData({ ...formData, nipUsername: e.target.value })}
                  required
                />
                <p className="text-xs text-muted-foreground">Bisa berupa NIP atau username</p>
              </div>
              <div className="space-y-2">
                <Label htmlFor="email">Email *</Label>
                <Input
                  id="email"
                  type="email"
                  value={formData.email}
                  onChange={(e) => setFormData({ ...formData, email: e.target.value })}
                  required
                />
              </div>
            </div>

            <div className="space-y-2">
              <Label htmlFor="nama">Nama Lengkap *</Label>
              <Input
                id="nama"
                value={formData.nama}
                onChange={(e) => setFormData({ ...formData, nama: e.target.value })}
                required
              />
            </div>

            <div className="grid grid-cols-2 gap-4">
              <div className="space-y-2">
                <Label htmlFor="jenisKelamin">Jenis Kelamin *</Label>
                <select
                  id="jenisKelamin"
                  className="flex h-10 w-full rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background"
                  value={formData.jenisKelamin}
                  onChange={(e) => setFormData({ ...formData, jenisKelamin: e.target.value })}
                  required
                >
                  <option value="L">Laki-laki</option>
                  <option value="P">Perempuan</option>
                </select>
              </div>
              <div className="space-y-2">
                <Label htmlFor="isActive">Status *</Label>
                <select
                  id="isActive"
                  className="flex h-10 w-full rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background"
                  value={formData.isActive ? "true" : "false"}
                  onChange={(e) => setFormData({ ...formData, isActive: e.target.value === "true" })}
                  required
                >
                  <option value="true">Aktif</option>
                  <option value="false">Nonaktif</option>
                </select>
              </div>
            </div>

            <div className="space-y-2">
              <Label htmlFor="alamat">Alamat</Label>
              <Input
                id="alamat"
                value={formData.alamat}
                onChange={(e) => setFormData({ ...formData, alamat: e.target.value })}
              />
            </div>

            <div className="grid grid-cols-2 gap-6">
              <div className="space-y-3">
                <Label>Mata Pelajaran yang Diajar *</Label>
                <div className="border rounded-lg p-4 space-y-3 max-h-60 overflow-y-auto">
                  {mapelList.length === 0 ? (
                    <p className="text-sm text-muted-foreground">Tidak ada mata pelajaran</p>
                  ) : (
                    mapelList.map((mapel: any) => (
                      <div key={mapel.id} className="flex items-center space-x-3">
                        <Checkbox
                          id={`mapel-${mapel.id}`}
                          checked={formData.mapelIds.includes(mapel.id)}
                          onCheckedChange={() => toggleMapel(mapel.id)}
                        />
                        <label
                          htmlFor={`mapel-${mapel.id}`}
                          className="text-sm font-medium leading-none cursor-pointer flex items-center gap-2"
                        >
                          <BookOpen className="h-4 w-4 text-muted-foreground" />
                          {mapel.nama}
                          <span className="text-xs text-muted-foreground">({mapel.kode})</span>
                        </label>
                      </div>
                    ))
                  )}
                </div>
                {formData.mapelIds.length > 0 && (
                  <p className="text-xs text-primary">
                    {formData.mapelIds.length} mata pelajaran dipilih
                  </p>
                )}
              </div>

              <div className="space-y-3">
                <Label>Kelas yang Diajar *</Label>
                <div className="border rounded-lg p-4 space-y-3 max-h-60 overflow-y-auto">
                  {kelasList.length === 0 ? (
                    <p className="text-sm text-muted-foreground">Tidak ada kelas</p>
                  ) : (
                    kelasList.map((kelas: any) => (
                      <div key={kelas.id} className="flex items-center space-x-3">
                        <Checkbox
                          id={`kelas-${kelas.id}`}
                          checked={formData.kelasIds.includes(kelas.id)}
                          onCheckedChange={() => toggleKelas(kelas.id)}
                        />
                        <label
                          htmlFor={`kelas-${kelas.id}`}
                          className="text-sm font-medium leading-none cursor-pointer flex items-center gap-2"
                        >
                          <Users className="h-4 w-4 text-muted-foreground" />
                          {kelas.nama}
                          <span className="text-xs text-muted-foreground">(Tingkat {kelas.tingkat})</span>
                        </label>
                      </div>
                    ))
                  )}
                </div>
                {formData.kelasIds.length > 0 && (
                  <p className="text-xs text-primary">
                    {formData.kelasIds.length} kelas dipilih
                  </p>
                )}
              </div>
            </div>

            <div className="flex justify-end gap-2 pt-4 border-t">
              <Button type="button" variant="outline" onClick={() => setIsDialogOpen(false)}>
                Batal
              </Button>
              <Button type="submit" disabled={formData.mapelIds.length === 0 || formData.kelasIds.length === 0}>
                {editingGuru ? "Perbarui" : "Tambah"} Guru
              </Button>
            </div>
          </form>
        </DialogContent>
      </Dialog>

      <DeleteConfirmationModal
        open={deleteModal.open}
        onOpenChange={(open) => setDeleteModal({ open, guru: null })}
        onConfirm={handleDelete}
        title="Hapus Guru"
        description="Apakah Anda yakin ingin menghapus guru"
        itemName={deleteModal.guru?.nama}
      />
    </div>
  );
}

// frontend-nuxt/pages/admin/guru/index.vue
<template>
  <div>
    <!-- Data Table -->
    <DataTable
      title="Manajemen Guru"
      subtitle="Kelola data guru"
      :columns="columns"
      :data="guruList"
      searchable
      search-placeholder="Cari guru..."
      :search-keys="['nama', 'nip', 'email']"
    >
      <template #header>
        <Button icon="lucide:plus" @click="openAddModal">
          Tambah Guru
        </Button>
      </template>

      <template #cell-nip="{ row }">
        <span class="text-gray-900 font-medium">{{ row.nip || row.nipUsername || '-' }}</span>
      </template>

      <template #cell-mapel="{ row }">
        <div class="flex flex-wrap gap-1">
          <template v-if="getMapelList(row).length > 0">
            <span 
              v-for="(mapel, idx) in getMapelList(row)" 
              :key="idx"
              class="px-2 py-0.5 text-xs rounded-full bg-blue-100 text-blue-700"
            >
              {{ mapel }}
            </span>
          </template>
          <span v-else class="text-gray-400">-</span>
        </div>
      </template>

      <template #cell-kelas="{ row }">
        <div class="flex flex-wrap gap-1">
          <template v-if="getKelasList(row).length > 0">
            <span 
              v-for="(kelas, idx) in getKelasList(row)" 
              :key="idx"
              class="px-2 py-0.5 text-xs rounded-full bg-purple-100 text-purple-700"
            >
              {{ kelas }}
            </span>
          </template>
          <span v-else class="text-gray-400">-</span>
        </div>
      </template>

      <template #cell-actions="{ row }">
        <div class="flex items-center justify-end gap-1">
          <Button
            variant="ghost"
            size="sm"
            icon="lucide:pencil"
            @click="editGuru(row)"
          />
          <Button
            variant="ghost"
            size="sm"
            icon="lucide:trash-2"
            class="text-red-600 hover:text-red-700 hover:bg-red-50"
            @click="confirmDelete(row)"
          />
        </div>
      </template>
    </DataTable>

    <!-- Add/Edit Modal -->
    <Modal
      v-model="showAddModal"
      :title="editingId ? 'Edit Guru' : 'Tambah Guru'"
      :description="editingId ? 'Ubah data guru yang sudah ada' : 'Tambahkan guru baru ke sistem'"
      size="lg"
    >
      <form @submit.prevent="saveGuru" class="space-y-4">
        <div class="grid grid-cols-2 gap-4">
          <div class="space-y-2">
            <Label>NIP / Username *</Label>
            <Input v-model="form.nip" placeholder="Masukkan NIP atau username" icon="lucide:hash" />
          </div>
          <div class="space-y-2">
            <Label>Email *</Label>
            <Input v-model="form.email" type="email" placeholder="Masukkan email" icon="lucide:mail" />
          </div>
        </div>
        
        <div class="space-y-2">
          <Label>Nama Lengkap *</Label>
          <Input v-model="form.nama" placeholder="Masukkan nama lengkap" icon="lucide:user" />
        </div>

        <div class="grid grid-cols-2 gap-4">
          <div class="space-y-2">
            <Label>Jenis Kelamin *</Label>
            <select 
              v-model="form.jenisKelamin" 
              class="w-full px-4 py-2.5 border border-gray-200 rounded-xl text-sm focus:outline-none focus:ring-2 focus:ring-orange-500/20 focus:border-orange-500"
            >
              <option value="L">Laki-laki</option>
              <option value="P">Perempuan</option>
            </select>
          </div>
          <div class="space-y-2">
            <Label>Status *</Label>
            <select 
              v-model="form.isActive" 
              class="w-full px-4 py-2.5 border border-gray-200 rounded-xl text-sm focus:outline-none focus:ring-2 focus:ring-orange-500/20 focus:border-orange-500"
            >
              <option :value="true">Aktif</option>
              <option :value="false">Nonaktif</option>
            </select>
          </div>
        </div>

        <div class="space-y-2">
          <Label>Alamat</Label>
          <Input v-model="form.alamat" placeholder="Masukkan alamat" icon="lucide:map-pin" />
        </div>

        <!-- Mata Pelajaran Selection -->
        <div class="grid grid-cols-2 gap-6">
          <div class="space-y-3">
            <Label>Mata Pelajaran yang Diajar *</Label>
            <div class="border border-gray-200 rounded-xl p-4 space-y-2 max-h-48 overflow-y-auto">
              <div v-if="mapelList.length === 0" class="text-sm text-gray-500">
                Tidak ada mata pelajaran
              </div>
              <div 
                v-for="mapel in mapelList" 
                :key="mapel.id" 
                class="flex items-center gap-3"
              >
                <input
                  type="checkbox"
                  :id="`mapel-${mapel.id}`"
                  :checked="form.mapelIds.includes(mapel.id)"
                  @change="toggleMapel(mapel.id)"
                  class="w-4 h-4 text-orange-500 rounded focus:ring-orange-500"
                />
                <label :for="`mapel-${mapel.id}`" class="text-sm cursor-pointer flex items-center gap-2">
                  <Icon name="lucide:book-open" class="w-4 h-4 text-gray-400" />
                  {{ mapel.nama }}
                  <span v-if="mapel.kode" class="text-xs text-gray-400">({{ mapel.kode }})</span>
                </label>
              </div>
            </div>
            <p v-if="form.mapelIds.length > 0" class="text-xs text-orange-600">
              {{ form.mapelIds.length }} mata pelajaran dipilih
            </p>
          </div>

          <!-- Kelas Selection -->
          <div class="space-y-3">
            <Label>Kelas yang Diajar *</Label>
            <div class="border border-gray-200 rounded-xl p-4 space-y-2 max-h-48 overflow-y-auto">
              <div v-if="kelasList.length === 0" class="text-sm text-gray-500">
                Tidak ada kelas
              </div>
              <div 
                v-for="kelas in kelasList" 
                :key="kelas.id" 
                class="flex items-center gap-3"
              >
                <input
                  type="checkbox"
                  :id="`kelas-${kelas.id}`"
                  :checked="form.kelasIds.includes(kelas.id)"
                  @change="toggleKelas(kelas.id)"
                  class="w-4 h-4 text-orange-500 rounded focus:ring-orange-500"
                />
                <label :for="`kelas-${kelas.id}`" class="text-sm cursor-pointer flex items-center gap-2">
                  <Icon name="lucide:users" class="w-4 h-4 text-gray-400" />
                  {{ kelas.nama }}
                  <span v-if="kelas.tingkat" class="text-xs text-gray-400">(Tingkat {{ kelas.tingkat }})</span>
                </label>
              </div>
            </div>
            <p v-if="form.kelasIds.length > 0" class="text-xs text-orange-600">
              {{ form.kelasIds.length }} kelas dipilih
            </p>
          </div>
        </div>
      </form>

      <template #footer>
        <div class="flex justify-end gap-3">
          <Button variant="outline" @click="showAddModal = false">
            Batal
          </Button>
          <Button :loading="isSaving" @click="saveGuru">
            {{ editingId ? 'Update' : 'Simpan' }}
          </Button>
        </div>
      </template>
    </Modal>

    <!-- Delete Confirmation -->
    <ConfirmDialog
      v-model="showDeleteDialog"
      title="Hapus Guru"
      :message="`Apakah Anda yakin ingin menghapus guru '${deletingItem?.nama}'? Tindakan ini tidak dapat dibatalkan.`"
      type="danger"
      confirm-text="Ya, Hapus"
      :loading="isDeleting"
      @confirm="handleDelete"
    />
  </div>
</template>

<script setup lang="ts">
import { toast } from 'vue-sonner'

definePageMeta({
  layout: 'admin',
})

useHead({
  title: 'Manajemen Guru',
})

const isLoading = ref(true)
const isSaving = ref(false)
const isDeleting = ref(false)
const showAddModal = ref(false)
const showDeleteDialog = ref(false)
const editingId = ref<string | null>(null)
const deletingItem = ref<any>(null)

const guruList = ref<any[]>([])
const mapelList = ref<any[]>([])
const kelasList = ref<any[]>([])

const form = ref({
  nip: '',
  nama: '',
  email: '',
  alamat: '',
  jenisKelamin: 'L',
  isActive: true,
  mapelIds: [] as string[],
  kelasIds: [] as string[],
})

const columns = [
  { key: 'nip', label: 'NIP' },
  { key: 'nama', label: 'Nama' },
  { key: 'email', label: 'Email' },
  { key: 'mapel', label: 'Mata Pelajaran' },
  { key: 'kelas', label: 'Kelas' },
  { key: 'actions', label: '', align: 'right' as const },
]

const getMapelList = (guru: any) => {
  if (!guru.mapel || !Array.isArray(guru.mapel)) return []
  return guru.mapel.map((m: any) => {
    if (typeof m === 'string') return m
    return m.nama || ''
  }).filter(Boolean)
}

const getKelasList = (guru: any) => {
  if (!guru.kelas || !Array.isArray(guru.kelas)) return []
  return guru.kelas.map((k: any) => {
    if (typeof k === 'string') return k
    return k.nama || ''
  }).filter(Boolean)
}

const toggleMapel = (mapelId: string) => {
  const idx = form.value.mapelIds.indexOf(mapelId)
  if (idx === -1) {
    form.value.mapelIds.push(mapelId)
  } else {
    form.value.mapelIds.splice(idx, 1)
  }
}

const toggleKelas = (kelasId: string) => {
  const idx = form.value.kelasIds.indexOf(kelasId)
  if (idx === -1) {
    form.value.kelasIds.push(kelasId)
  } else {
    form.value.kelasIds.splice(idx, 1)
  }
}

const resetForm = () => {
  form.value = {
    nip: '',
    nama: '',
    email: '',
    alamat: '',
    jenisKelamin: 'L',
    isActive: true,
    mapelIds: [],
    kelasIds: [],
  }
  editingId.value = null
}

const editGuru = (guru: any) => {
  editingId.value = guru.id
  form.value = {
    nip: guru.nip || guru.nipUsername || '',
    nama: guru.nama || '',
    email: guru.email || '',
    alamat: guru.alamat || '',
    jenisKelamin: guru.jenisKelamin || 'L',
    isActive: guru.isActive !== undefined ? guru.isActive : true,
    mapelIds: guru.mapel?.map((m: any) => m.mapelId || m.id) || [],
    kelasIds: guru.kelas?.map((k: any) => k.kelasId || k.id) || [],
  }
  showAddModal.value = true
}

const saveGuru = async () => {
  isSaving.value = true
  try {
    const url = editingId.value 
      ? `/api/admin/guru/${editingId.value}`
      : '/api/admin/guru'
    
    const body = {
      nip: form.value.nip,
      nipUsername: form.value.nip,
      nama: form.value.nama,
      email: form.value.email,
      alamat: form.value.alamat,
      jenisKelamin: form.value.jenisKelamin,
      isActive: form.value.isActive,
      mapelIds: form.value.mapelIds,
      kelasIds: form.value.kelasIds,
    }
    
    const response = await fetchApi(url, {
      method: editingId.value ? 'PUT' : 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(body),
    })
    
    const data = await response.json()
    
    if (data.success) {
      toast.success(editingId.value ? 'Guru berhasil diupdate' : 'Guru berhasil ditambahkan')
      showAddModal.value = false
      resetForm()
      await fetchGuru()
    } else {
      toast.error(data.error || 'Gagal menyimpan')
    }
  } catch (err) {
    toast.error('Terjadi kesalahan')
  } finally {
    isSaving.value = false
  }
}

const openAddModal = () => {
  resetForm()
  showAddModal.value = true
}

const confirmDelete = (guru: any) => {
  deletingItem.value = guru
  showDeleteDialog.value = true
}

const handleDelete = async () => {
  if (!deletingItem.value) return
  
  isDeleting.value = true
  try {
    const response = await fetchApi(`/api/admin/guru/${deletingItem.value.id}`, {
      method: 'DELETE',
    })
    
    const data = await response.json()
    
    if (data.success) {
      toast.success('Guru berhasil dihapus')
      showDeleteDialog.value = false
      deletingItem.value = null
      await fetchGuru()
    } else {
      toast.error(data.error || 'Gagal menghapus')
    }
  } catch (err) {
    toast.error('Terjadi kesalahan')
  } finally {
    isDeleting.value = false
  }
}

const fetchGuru = async () => {
  const response = await fetchApi('/api/admin/guru')
  const data = await response.json()
  if (data.success) {
    guruList.value = data.data || []
  }
}

const fetchMapel = async () => {
  const response = await fetchApi('/api/admin/mapel')
  const data = await response.json()
  if (data.success) {
    mapelList.value = data.data || []
  }
}

const fetchKelas = async () => {
  const response = await fetchApi('/api/admin/kelas')
  const data = await response.json()
  if (data.success) {
    kelasList.value = data.data || []
  }
}

onMounted(async () => {
  try {
    await Promise.all([fetchGuru(), fetchMapel(), fetchKelas()])
  } catch (err) {
    console.error('Error:', err)
  } finally {
    isLoading.value = false
  }
})

watch(showAddModal, (val) => {
  if (!val) resetForm()
})
</script>
