// frontend/src/app/(main)/guru/bank-soal/page.tsx
"use client";

import { useState } from "react";
import useSWR from "swr";
import { fetcherWithAuth } from "@/lib/swr-config";
import { fetchApi } from "@/lib/fetch-api";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Badge } from "@/components/ui/badge";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import { Checkbox } from "@/components/ui/checkbox";
import { LoadingSpinner } from "@/components/ui/loading-spinner";
import { Plus, Search, Trash2, FileUp, FileDown, BookOpen, CheckCircle, X, Pencil, Eye } from "lucide-react";
import { toast } from "sonner";
import Link from "next/link";

const TIPE_LABELS: Record<string, string> = {
  PILIHAN_GANDA: "Pilihan Ganda",
  ESSAY: "Essay",
  ISIAN_SINGKAT: "Isian Singkat",
  BENAR_SALAH: "Benar/Salah",
  PENCOCOKAN: "Pencocokan",
};

const TIPE_COLORS: Record<string, string> = {
  PILIHAN_GANDA: "bg-blue-100 text-blue-800",
  ESSAY: "bg-purple-100 text-purple-800",
  ISIAN_SINGKAT: "bg-green-100 text-green-800",
  BENAR_SALAH: "bg-orange-100 text-orange-800",
  PENCOCOKAN: "bg-pink-100 text-pink-800",
};

export default function BankSoalPage() {
  const [searchQuery, setSearchQuery] = useState("");
  const [filterMapel, setFilterMapel] = useState<string>("all");
  const [filterTipe, setFilterTipe] = useState<string>("all");
  const [selectedIds, setSelectedIds] = useState<string[]>([]);
  const [importDialog, setImportDialog] = useState(false);
  const [selectedUjian, setSelectedUjian] = useState<string>("");
  const [deleteDialog, setDeleteDialog] = useState(false);
  const [deleteId, setDeleteId] = useState<string | null>(null);
  const [bulkDeleteDialog, setBulkDeleteDialog] = useState(false);

  const { data: bankSoalData, isLoading, mutate } = useSWR('/api/guru/bank-soal', fetcherWithAuth);
  const { data: statsData } = useSWR('/api/guru/bank-soal/stats', fetcherWithAuth);
  const { data: mapelData } = useSWR('/api/mapel', fetcherWithAuth);
  const { data: ujianData } = useSWR('/api/guru/ujian', fetcherWithAuth);

  if (isLoading) return <LoadingSpinner />;

  const bankSoal = bankSoalData?.data || [];
  const stats = statsData?.data || { total: 0, byTipe: {}, byMapel: [] };
  const mapelList = mapelData?.data || [];
  const ujianList = ujianData?.data?.ujian || [];

  const filteredSoal = bankSoal.filter((s: any) => {
    const matchSearch = !searchQuery || 
      s.pertanyaan?.toLowerCase().includes(searchQuery.toLowerCase()) ||
      s.tags?.some((t: string) => t.toLowerCase().includes(searchQuery.toLowerCase()));
    const matchMapel = filterMapel === "all" || s.mapelId === filterMapel;
    const matchTipe = filterTipe === "all" || s.tipe === filterTipe;
    return matchSearch && matchMapel && matchTipe;
  });

  const handleSelectAll = () => {
    if (selectedIds.length === filteredSoal.length) {
      setSelectedIds([]);
    } else {
      setSelectedIds(filteredSoal.map((s: any) => s.id));
    }
  };

  const handleSelect = (id: string) => {
    setSelectedIds(prev => 
      prev.includes(id) ? prev.filter(i => i !== id) : [...prev, id]
    );
  };

  const openDeleteDialog = (id: string) => {
    setDeleteId(id);
    setDeleteDialog(true);
  };

  const handleDelete = async () => {
    if (!deleteId) return;
    
    try {
      const res = await fetchApi(`/api/guru/bank-soal/${deleteId}`, { method: 'DELETE' });
      if (res.ok) {
        toast.success("Soal berhasil dihapus");
        mutate();
      } else {
        toast.error("Gagal menghapus soal");
      }
    } catch (error) {
      toast.error("Terjadi kesalahan");
    } finally {
      setDeleteDialog(false);
      setDeleteId(null);
    }
  };

  const handleBulkDelete = async () => {
    if (selectedIds.length === 0) return;
    
    try {
      const res = await fetchApi('/api/guru/bank-soal/bulk-delete', {
        method: 'POST',
        body: JSON.stringify({ ids: selectedIds }),
      });
      if (res.ok) {
        toast.success(`${selectedIds.length} soal berhasil dihapus`);
        setSelectedIds([]);
        mutate();
      } else {
        const data = await res.json();
        toast.error(data.error || "Gagal menghapus soal");
      }
    } catch (error) {
      toast.error("Terjadi kesalahan");
    } finally {
      setBulkDeleteDialog(false);
    }
  };

  const handleImportToUjian = async () => {
    if (!selectedUjian || selectedIds.length === 0) {
      toast.error("Pilih ujian dan soal terlebih dahulu");
      return;
    }

    try {
      const res = await fetchApi('/api/guru/bank-soal/import-to-ujian', {
        method: 'POST',
        body: JSON.stringify({ ujianId: selectedUjian, bankSoalIds: selectedIds }),
      });
      const data = await res.json();
      
      if (res.ok && data.success) {
        toast.success(data.message);
        setImportDialog(false);
        setSelectedIds([]);
        setSelectedUjian("");
      } else {
        toast.error(data.error || "Gagal import soal");
      }
    } catch (error) {
      toast.error("Terjadi kesalahan");
    }
  };

  const stripHtml = (html: string) => {
    const tmp = document.createElement("div");
    tmp.innerHTML = html;
    return tmp.textContent || tmp.innerText || "";
  };

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold tracking-tight">Bank Soal</h1>
          <p className="text-muted-foreground">
            Kelola koleksi soal untuk digunakan di berbagai ujian
          </p>
        </div>
        <div className="flex gap-2">
          {selectedIds.length > 0 && (
            <>
              <Button variant="outline" onClick={() => setImportDialog(true)}>
                <FileUp className="w-4 h-4 mr-2" />
                Import ke Ujian ({selectedIds.length})
              </Button>
              <Button variant="destructive" onClick={() => setBulkDeleteDialog(true)}>
                <Trash2 className="w-4 h-4 mr-2" />
                Hapus ({selectedIds.length})
              </Button>
            </>
          )}
          <Link href="/guru/bank-soal/create">
            <Button>
              <Plus className="w-4 h-4 mr-2" />
              Tambah Soal
            </Button>
          </Link>
        </div>
      </div>

      {/* Stats */}
      <div className="grid gap-4 md:grid-cols-6">
        <Card>
          <CardContent className="pt-4">
            <div className="text-2xl font-bold">{stats.total}</div>
            <p className="text-xs text-muted-foreground">Total Soal</p>
          </CardContent>
        </Card>
        {Object.entries(stats.byTipe || {}).map(([tipe, count]) => (
          <Card key={tipe}>
            <CardContent className="pt-4">
              <div className="text-2xl font-bold">{count as number}</div>
              <p className="text-xs text-muted-foreground">{TIPE_LABELS[tipe] || tipe}</p>
            </CardContent>
          </Card>
        ))}
      </div>

      {/* Filters */}
      <Card>
        <CardContent className="pt-4">
          <div className="flex gap-4 flex-wrap">
            <div className="flex-1 min-w-[200px]">
              <div className="relative">
                <Search className="absolute left-3 top-3 h-4 w-4 text-muted-foreground" />
                <Input
                  placeholder="Cari soal atau tag..."
                  value={searchQuery}
                  onChange={(e) => setSearchQuery(e.target.value)}
                  className="pl-10"
                />
              </div>
            </div>
            <Select value={filterMapel} onValueChange={setFilterMapel}>
              <SelectTrigger className="w-[180px]">
                <SelectValue placeholder="Filter Mapel" />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="all">Semua Mapel</SelectItem>
                {mapelList.map((m: any) => (
                  <SelectItem key={m.id} value={m.id}>{m.nama}</SelectItem>
                ))}
              </SelectContent>
            </Select>
            <Select value={filterTipe} onValueChange={setFilterTipe}>
              <SelectTrigger className="w-[180px]">
                <SelectValue placeholder="Filter Tipe" />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="all">Semua Tipe</SelectItem>
                {Object.entries(TIPE_LABELS).map(([key, label]) => (
                  <SelectItem key={key} value={key}>{label}</SelectItem>
                ))}
              </SelectContent>
            </Select>
          </div>
        </CardContent>
      </Card>

      {/* Table */}
      <Card>
        <CardHeader className="pb-3">
          <CardTitle className="text-lg">Daftar Soal ({filteredSoal.length})</CardTitle>
        </CardHeader>
        <CardContent className="p-0">
          <Table>
            <TableHeader>
              <TableRow className="bg-muted/50">
                <TableHead className="w-12 pl-4">
                  <Checkbox 
                    checked={selectedIds.length === filteredSoal.length && filteredSoal.length > 0}
                    onCheckedChange={handleSelectAll}
                  />
                </TableHead>
                <TableHead className="min-w-[300px]">Pertanyaan</TableHead>
                <TableHead className="w-36">Mapel</TableHead>
                <TableHead className="w-36">Kelas</TableHead>
                <TableHead className="w-32">Tipe</TableHead>
                <TableHead className="w-20 text-center">Poin</TableHead>
                <TableHead className="w-32 text-center">Aksi</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {filteredSoal.length === 0 ? (
                <TableRow>
                  <TableCell colSpan={7} className="text-center py-12 text-muted-foreground">
                    <BookOpen className="w-16 h-16 mx-auto mb-4 opacity-30" />
                    <p className="text-lg font-medium mb-1">Belum ada soal di bank soal</p>
                    <p className="text-sm">Tambah soal baru atau export dari ujian yang sudah ada</p>
                  </TableCell>
                </TableRow>
              ) : (
                filteredSoal.map((soal: any) => (
                  <TableRow key={soal.id} className="hover:bg-muted/30">
                    <TableCell className="pl-4">
                      <Checkbox 
                        checked={selectedIds.includes(soal.id)}
                        onCheckedChange={() => handleSelect(soal.id)}
                      />
                    </TableCell>
                    <TableCell className="py-4">
                      <div className="space-y-1.5">
                        <p className="font-medium text-sm line-clamp-2 leading-relaxed">
                          {stripHtml(soal.pertanyaan)}
                        </p>
                        {soal.tags?.length > 0 && (
                          <div className="flex flex-wrap gap-1">
                            {soal.tags.slice(0, 3).map((tag: string, idx: number) => (
                              <Badge key={idx} variant="outline" className="text-xs px-1.5 py-0">
                                {tag}
                              </Badge>
                            ))}
                            {soal.tags.length > 3 && (
                              <span className="text-xs text-muted-foreground">+{soal.tags.length - 3}</span>
                            )}
                          </div>
                        )}
                      </div>
                    </TableCell>
                    <TableCell>
                      <span className="text-sm font-medium">{soal.mapel || '-'}</span>
                    </TableCell>
                    <TableCell>
                      {soal.kelas?.length > 0 ? (
                        <div className="flex flex-wrap gap-1">
                          {soal.kelas.slice(0, 2).map((k: string, idx: number) => (
                            <Badge key={idx} variant="secondary" className="text-xs">
                              {k}
                            </Badge>
                          ))}
                          {soal.kelas.length > 2 && (
                            <span className="text-xs text-muted-foreground">+{soal.kelas.length - 2}</span>
                          )}
                        </div>
                      ) : (
                        <span className="text-xs text-muted-foreground">Semua</span>
                      )}
                    </TableCell>
                    <TableCell>
                      <Badge className={`${TIPE_COLORS[soal.tipe] || "bg-gray-100"} text-xs`}>
                        {TIPE_LABELS[soal.tipe] || soal.tipe}
                      </Badge>
                    </TableCell>
                    <TableCell className="text-center">
                      <span className="font-semibold">{soal.poin}</span>
                    </TableCell>
                    <TableCell>
                      <div className="flex items-center justify-center gap-1">
                        <Link href={`/guru/bank-soal/${soal.id}/edit`}>
                          <Button variant="ghost" size="sm" className="h-8 w-8 p-0">
                            <Pencil className="w-4 h-4 text-blue-600" />
                          </Button>
                        </Link>
                        <Button 
                          variant="ghost" 
                          size="sm" 
                          className="h-8 w-8 p-0"
                          onClick={() => openDeleteDialog(soal.id)}
                        >
                          <Trash2 className="w-4 h-4 text-red-500" />
                        </Button>
                      </div>
                    </TableCell>
                  </TableRow>
                ))
              )}
            </TableBody>
          </Table>
        </CardContent>
      </Card>

      {/* Import to Ujian Dialog */}
      <Dialog open={importDialog} onOpenChange={setImportDialog}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle>Import Soal ke Ujian</DialogTitle>
            <DialogDescription>
              Pilih ujian untuk menambahkan {selectedIds.length} soal yang dipilih
            </DialogDescription>
          </DialogHeader>
          <div className="space-y-4">
            <Select value={selectedUjian} onValueChange={setSelectedUjian}>
              <SelectTrigger>
                <SelectValue placeholder="Pilih Ujian" />
              </SelectTrigger>
              <SelectContent>
                {ujianList.filter((u: any) => u.status === 'draft').map((u: any) => (
                  <SelectItem key={u.id} value={u.id}>{u.judul}</SelectItem>
                ))}
              </SelectContent>
            </Select>
            <div className="flex justify-end gap-2">
              <Button variant="outline" onClick={() => setImportDialog(false)}>Batal</Button>
              <Button onClick={handleImportToUjian} disabled={!selectedUjian}>
                <FileUp className="w-4 h-4 mr-2" />
                Import
              </Button>
            </div>
          </div>
        </DialogContent>
      </Dialog>

      {/* Delete Confirmation Dialog */}
      <Dialog open={deleteDialog} onOpenChange={setDeleteDialog}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle>Hapus Soal</DialogTitle>
            <DialogDescription>
              Apakah Anda yakin ingin menghapus soal ini dari bank soal? Tindakan ini tidak dapat dibatalkan.
            </DialogDescription>
          </DialogHeader>
          <div className="flex justify-end gap-2 mt-4">
            <Button variant="outline" onClick={() => setDeleteDialog(false)}>Batal</Button>
            <Button variant="destructive" onClick={handleDelete}>
              <Trash2 className="w-4 h-4 mr-2" />
              Hapus
            </Button>
          </div>
        </DialogContent>
      </Dialog>

      {/* Bulk Delete Confirmation Dialog */}
      <Dialog open={bulkDeleteDialog} onOpenChange={setBulkDeleteDialog}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle>Hapus {selectedIds.length} Soal</DialogTitle>
            <DialogDescription>
              Apakah Anda yakin ingin menghapus {selectedIds.length} soal yang dipilih dari bank soal? Tindakan ini tidak dapat dibatalkan.
            </DialogDescription>
          </DialogHeader>
          <div className="flex justify-end gap-2 mt-4">
            <Button variant="outline" onClick={() => setBulkDeleteDialog(false)}>Batal</Button>
            <Button variant="destructive" onClick={handleBulkDelete}>
              <Trash2 className="w-4 h-4 mr-2" />
              Hapus {selectedIds.length} Soal
            </Button>
          </div>
        </DialogContent>
      </Dialog>
    </div>
  );
}

// frontend-nuxt/pages/guru/bank-soal/index.vue
<template>
  <div>
    <!-- Search & Filter Card -->
    <div class="bg-white rounded-2xl p-5 card-shadow mb-6">
      <div class="flex gap-4">
        <div class="flex-1">
          <Input
            v-model="searchQuery"
            placeholder="Cari soal..."
            icon="lucide:search"
            class="w-full"
          />
        </div>
        <select
          v-model="filterMapel"
          class="px-4 py-2.5 border border-gray-200 rounded-xl bg-white text-sm focus:outline-none focus:ring-2 focus:ring-orange-500/20 focus:border-orange-500"
        >
          <option value="">Semua Mapel</option>
          <option v-for="mapel in mapelList" :key="mapel.id" :value="mapel.id">
            {{ mapel.nama }}
          </option>
        </select>
        <select
          v-model="filterTipe"
          class="px-4 py-2.5 border border-gray-200 rounded-xl bg-white text-sm focus:outline-none focus:ring-2 focus:ring-orange-500/20 focus:border-orange-500"
        >
          <option value="">Semua Tipe</option>
          <option value="PILIHAN_GANDA">Pilihan Ganda</option>
          <option value="ESSAY">Essay</option>
          <option value="ISIAN_SINGKAT">Isian Singkat</option>
          <option value="BENAR_SALAH">Benar/Salah</option>
        </select>
        <Button @click="openAddModal" icon="lucide:plus">
          Tambah Soal
        </Button>
      </div>
    </div>

    <!-- Loading -->
    <div v-if="isLoading" class="flex items-center justify-center h-64">
      <Icon name="lucide:loader-2" class="w-8 h-8 animate-spin text-orange-500" />
    </div>

    <!-- Soal List -->
    <div v-else class="space-y-4">
      <div
        v-for="soal in filteredSoal"
        :key="soal.id"
        class="bg-white rounded-2xl p-6 card-shadow"
      >
        <div class="flex items-start justify-between">
          <div class="flex-1">
            <div class="flex items-center gap-3 mb-2">
              <span :class="getTipeClass(soal.tipe)">
                {{ getTipeLabel(soal.tipe) }}
              </span>
              <span class="text-sm text-gray-500">{{ soal.mapel?.nama || soal.mapel || '-' }}</span>
            </div>
            <p class="text-gray-900 mb-2" v-html="truncateText(soal.pertanyaan, 200)"></p>
            <p class="text-sm text-gray-500">Bobot: {{ soal.poin || soal.bobot || 10 }} poin</p>
          </div>
          <div class="flex gap-2 ml-4">
            <Button
              variant="ghost"
              size="sm"
              icon="lucide:pencil"
              @click="editSoal(soal)"
            />
            <Button
              variant="ghost"
              size="sm"
              icon="lucide:trash-2"
              class="text-red-600 hover:text-red-700 hover:bg-red-50"
              @click="confirmDelete(soal)"
            />
          </div>
        </div>
      </div>
      
      <div v-if="filteredSoal.length === 0" class="bg-white rounded-2xl p-12 card-shadow text-center">
        <Icon name="lucide:database" class="w-12 h-12 mx-auto mb-3 text-gray-300" />
        <p class="text-gray-500">Belum ada soal</p>
      </div>
    </div>

    <!-- Add/Edit Modal -->
    <Modal
      v-model="showAddModal"
      :title="editingId ? 'Edit Soal' : 'Tambah Soal'"
      :description="editingId ? 'Ubah data soal' : 'Tambahkan soal baru ke bank soal'"
      size="lg"
    >
      <form @submit.prevent="saveSoal" class="space-y-4">
        <div class="grid grid-cols-2 gap-4">
          <div class="space-y-2">
            <Label>Mata Pelajaran</Label>
            <select v-model="form.mapelId" class="w-full px-4 py-2.5 border border-gray-200 rounded-xl text-sm focus:outline-none focus:ring-2 focus:ring-orange-500/20 focus:border-orange-500" required>
              <option value="">Pilih Mapel</option>
              <option v-for="mapel in mapelList" :key="mapel.id" :value="mapel.id">
                {{ mapel.nama }}
              </option>
            </select>
          </div>
          <div class="space-y-2">
            <Label>Tipe Soal</Label>
            <select v-model="form.tipe" class="w-full px-4 py-2.5 border border-gray-200 rounded-xl text-sm focus:outline-none focus:ring-2 focus:ring-orange-500/20 focus:border-orange-500" required>
              <option value="PILIHAN_GANDA">Pilihan Ganda</option>
              <option value="ESSAY">Essay</option>
              <option value="ISIAN_SINGKAT">Isian Singkat</option>
              <option value="BENAR_SALAH">Benar/Salah</option>
            </select>
          </div>
        </div>
        
        <div class="space-y-2">
          <Label>Pertanyaan</Label>
          <TiptapEditor
            v-model="form.pertanyaan"
            placeholder="Masukkan pertanyaan..."
          />
        </div>
        
        <!-- Pilihan Ganda Options -->
        <div v-if="form.tipe === 'PILIHAN_GANDA'" class="space-y-2">
          <Label>Pilihan Jawaban</Label>
          <div v-for="opsi in form.data.opsi" :key="opsi.label" class="flex gap-3 items-start">
            <div class="flex items-center gap-2 pt-2">
              <input
                type="radio"
                name="jawaban"
                :value="opsi.label"
                v-model="form.data.kunciJawaban"
                class="w-4 h-4 text-orange-500 focus:ring-orange-500"
              />
              <span class="w-8 h-8 flex items-center justify-center bg-gray-100 rounded-lg font-medium text-sm">
                {{ opsi.label }}
              </span>
            </div>
            <div class="flex-1">
              <TiptapEditor
                v-model="opsi.text"
                :placeholder="`Pilihan ${opsi.label}`"
                mini
              />
            </div>
          </div>
          <p class="text-xs text-gray-500">Pilih radio button untuk menandai jawaban yang benar</p>
        </div>

        <!-- Essay -->
        <div v-if="form.tipe === 'ESSAY'" class="space-y-2">
          <Label>Kunci Jawaban (Referensi)</Label>
          <TiptapEditor
            v-model="form.data.kunciJawaban"
            placeholder="Kunci jawaban untuk referensi penilaian..."
            mini
          />
        </div>

        <!-- Isian Singkat -->
        <div v-if="form.tipe === 'ISIAN_SINGKAT'" class="space-y-2">
          <Label>Kunci Jawaban</Label>
          <Input
            v-model="form.data.kunciJawaban"
            placeholder="Jawaban yang benar"
          />
        </div>

        <!-- Benar/Salah -->
        <div v-if="form.tipe === 'BENAR_SALAH'" class="space-y-2">
          <Label>Jawaban yang Benar</Label>
          <div class="flex gap-4">
            <label class="flex items-center gap-2 cursor-pointer">
              <input
                type="radio"
                name="benar-salah"
                :value="true"
                v-model="form.data.kunciJawaban"
                class="w-4 h-4 text-orange-500 focus:ring-orange-500"
              />
              <span class="text-sm">Benar</span>
            </label>
            <label class="flex items-center gap-2 cursor-pointer">
              <input
                type="radio"
                name="benar-salah"
                :value="false"
                v-model="form.data.kunciJawaban"
                class="w-4 h-4 text-orange-500 focus:ring-orange-500"
              />
              <span class="text-sm">Salah</span>
            </label>
          </div>
        </div>
        
        <div class="space-y-2">
          <Label>Poin</Label>
          <Input v-model.number="form.poin" type="number" min="1" icon="lucide:star" />
        </div>
      </form>

      <template #footer>
        <div class="flex justify-end gap-3">
          <Button variant="outline" @click="showAddModal = false">
            Batal
          </Button>
          <Button :loading="isSaving" @click="saveSoal">
            {{ editingId ? 'Update' : 'Simpan' }}
          </Button>
        </div>
      </template>
    </Modal>

    <!-- Delete Confirmation -->
    <ConfirmDialog
      v-model="showDeleteDialog"
      title="Hapus Soal"
      message="Apakah Anda yakin ingin menghapus soal ini? Tindakan ini tidak dapat dibatalkan."
      type="danger"
      confirm-text="Ya, Hapus"
      :loading="isDeleting"
      @confirm="handleDelete"
    />
  </div>
</template>

<script setup lang="ts">
import { toast } from 'vue-sonner'

definePageMeta({
  layout: 'guru',
})

useHead({
  title: 'Bank Soal',
})

const isLoading = ref(true)
const isSaving = ref(false)
const isDeleting = ref(false)
const showAddModal = ref(false)
const showDeleteDialog = ref(false)
const editingId = ref<string | null>(null)
const deletingItem = ref<any>(null)
const searchQuery = ref('')
const filterMapel = ref('')
const filterTipe = ref('')

const soalList = ref<any[]>([])
const mapelList = ref<any[]>([])

const form = ref({
  mapelId: '',
  tipe: 'PILIHAN_GANDA',
  pertanyaan: '',
  data: {
    opsi: [
      { label: 'A', text: '' },
      { label: 'B', text: '' },
      { label: 'C', text: '' },
      { label: 'D', text: '' },
    ],
    kunciJawaban: 'A',
  },
  poin: 10,
})

const filteredSoal = computed(() => {
  let result = soalList.value
  
  if (searchQuery.value) {
    const query = searchQuery.value.toLowerCase()
    result = result.filter(s => s.pertanyaan.toLowerCase().includes(query))
  }
  
  if (filterMapel.value) {
    result = result.filter(s => s.mapelId === filterMapel.value)
  }
  
  if (filterTipe.value) {
    result = result.filter(s => s.tipe === filterTipe.value)
  }
  
  return result
})

const truncateText = (text: string, length: number) => {
  if (text.length <= length) return text
  return text.substring(0, length) + '...'
}

const getTipeClass = (tipe: string) => {
  const classes: Record<string, string> = {
    PILIHAN_GANDA: 'px-2 py-1 text-xs rounded-full bg-blue-100 text-blue-600',
    ESSAY: 'px-2 py-1 text-xs rounded-full bg-purple-100 text-purple-600',
    ISIAN_SINGKAT: 'px-2 py-1 text-xs rounded-full bg-orange-100 text-orange-600',
    BENAR_SALAH: 'px-2 py-1 text-xs rounded-full bg-green-100 text-green-600',
  }
  return classes[tipe] || 'px-2 py-1 text-xs rounded-full bg-gray-100 text-gray-600'
}

const getTipeLabel = (tipe: string) => {
  const labels: Record<string, string> = {
    PILIHAN_GANDA: 'Pilihan Ganda',
    ESSAY: 'Essay',
    ISIAN_SINGKAT: 'Isian Singkat',
    BENAR_SALAH: 'Benar/Salah',
  }
  return labels[tipe] || tipe
}

const resetForm = () => {
  form.value = {
    mapelId: '',
    tipe: 'PILIHAN_GANDA',
    pertanyaan: '',
    data: {
      opsi: [
        { label: 'A', text: '' },
        { label: 'B', text: '' },
        { label: 'C', text: '' },
        { label: 'D', text: '' },
      ],
      kunciJawaban: 'A',
    },
    poin: 10,
  }
  editingId.value = null
}

const editSoal = (soal: any) => {
  editingId.value = soal.id
  form.value = {
    mapelId: soal.mapelId || '',
    tipe: soal.tipe || 'PILIHAN_GANDA',
    pertanyaan: soal.pertanyaan || '',
    data: soal.data || {
      opsi: [
        { label: 'A', text: '' },
        { label: 'B', text: '' },
        { label: 'C', text: '' },
        { label: 'D', text: '' },
      ],
      kunciJawaban: 'A',
    },
    poin: soal.poin || 10,
  }
  showAddModal.value = true
}

const saveSoal = async () => {
  isSaving.value = true
  try {
    const url = editingId.value 
      ? `/api/guru/bank-soal/${editingId.value}`
      : '/api/guru/bank-soal'
    
    const response = await fetchApi(url, {
      method: editingId.value ? 'PUT' : 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(form.value),
    })
    
    const data = await response.json()
    
    if (data.success) {
      toast.success(editingId.value ? 'Soal berhasil diupdate' : 'Soal berhasil ditambahkan')
      showAddModal.value = false
      resetForm()
      await fetchSoal()
    } else {
      toast.error(data.error || 'Gagal menyimpan')
    }
  } catch (err) {
    toast.error('Terjadi kesalahan')
  } finally {
    isSaving.value = false
  }
}

const openAddModal = () => {
  resetForm()
  showAddModal.value = true
}

const confirmDelete = (soal: any) => {
  deletingItem.value = soal
  showDeleteDialog.value = true
}

const handleDelete = async () => {
  if (!deletingItem.value) return
  
  isDeleting.value = true
  try {
    const response = await fetchApi(`/api/guru/bank-soal/${deletingItem.value.id}`, {
      method: 'DELETE',
    })
    
    const data = await response.json()
    
    if (data.success) {
      toast.success('Soal berhasil dihapus')
      showDeleteDialog.value = false
      deletingItem.value = null
      await fetchSoal()
    } else {
      toast.error(data.error || 'Gagal menghapus')
    }
  } catch (err) {
    toast.error('Terjadi kesalahan')
  } finally {
    isDeleting.value = false
  }
}

const fetchSoal = async () => {
  const response = await fetchApi('/api/guru/bank-soal')
  const data = await response.json()
  if (data.success) {
    soalList.value = data.data || []
  }
}

const fetchMapel = async () => {
  const response = await fetchApi('/api/admin/mapel')
  const data = await response.json()
  if (data.success) {
    mapelList.value = data.data || []
  }
}

onMounted(async () => {
  try {
    await Promise.all([fetchSoal(), fetchMapel()])
  } catch (err) {
    console.error('Error:', err)
  } finally {
    isLoading.value = false
  }
})

watch(showAddModal, (val) => {
  if (!val) resetForm()
})
</script>
