// frontend/src/app/superadmin/notifications/page.tsx
"use client";


import { fetchApi } from '@/lib/fetch-api';
import { useState } from "react";
import useSWR from "swr";
import { Card, CardContent } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from "@/components/ui/dialog";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { toast } from "sonner";
import { Plus, Send, Pencil, Trash2, Loader2, Bell, Info, AlertTriangle, Wrench, Megaphone } from "lucide-react";
import { cn } from "@/lib/utils";

import { superadminFetcher, superadminFetch } from '../_lib/fetcher';

const TIPE_OPTIONS = [
  { value: "info", label: "Info", icon: Info, color: "text-blue-500" },
  { value: "warning", label: "Warning", icon: AlertTriangle, color: "text-yellow-500" },
  { value: "update", label: "Update", icon: Bell, color: "text-green-500" },
  { value: "maintenance", label: "Maintenance", icon: Wrench, color: "text-orange-500" },
  { value: "promo", label: "Promo", icon: Megaphone, color: "text-purple-500" },
];

const PRIORITY_OPTIONS = ["low", "normal", "high", "urgent"];
const ROLE_OPTIONS = ["ALL", "ADMIN", "GURU", "SISWA"];

const emptyForm = {
  judul: "", pesan: "", tipe: "info", targetRole: ["ALL"] as string[],
  priority: "normal", expiresAt: "",
};

export default function NotificationsPage() {
  const { data, mutate, isLoading } = useSWR("/api/superadmin/notifications", superadminFetcher);
  const [showDialog, setShowDialog] = useState(false);
  const [editId, setEditId] = useState<string | null>(null);
  const [form, setForm] = useState<any>(emptyForm);
  const [saving, setSaving] = useState(false);

  const notifications = data?.data || [];

  const openCreate = () => {
    setEditId(null);
    setForm({ ...emptyForm });
    setShowDialog(true);
  };

  const openEdit = (n: any) => {
    setEditId(n.id);
    setForm({
      judul: n.judul, pesan: n.pesan, tipe: n.tipe,
      targetRole: n.targetRole || ["ALL"], priority: n.priority || "normal",
      expiresAt: n.expiresAt ? new Date(n.expiresAt).toISOString().slice(0, 16) : "",
    });
    setShowDialog(true);
  };

  const handleSave = async (publish = false) => {
    if (!form.judul || !form.pesan) { toast.error("Judul dan pesan harus diisi"); return; }
    setSaving(true);
    try {
      const method = editId ? "PUT" : "POST";
      const body = editId
        ? { id: editId, ...form, publish }
        : { ...form, publish };

      const res = await fetchApi("/api/superadmin/notifications", {
        method, headers: { "Content-Type": "application/json" },
        credentials: "include", body: JSON.stringify(body),
      });
      const result = await res.json();
      if (result.success) {
        toast.success(result.message);
        mutate();
        setShowDialog(false);
      } else {
        toast.error(result.error);
      }
    } catch { toast.error("Gagal menyimpan notifikasi"); }
    finally { setSaving(false); }
  };

  const handleDelete = async (id: string) => {
    if (!confirm("Hapus notifikasi ini?")) return;
    try {
      const res = await fetchApi(`/api/superadmin/notifications?id=${id}`, {
        method: "DELETE", credentials: "include",
      });
      const result = await res.json();
      if (result.success) { toast.success(result.message); mutate(); }
      else toast.error(result.error);
    } catch { toast.error("Gagal menghapus"); }
  };

  const toggleRole = (role: string) => {
    const current = form.targetRole || [];
    if (role === "ALL") {
      setForm({ ...form, targetRole: ["ALL"] });
    } else {
      const filtered = current.filter((r: string) => r !== "ALL");
      if (filtered.includes(role)) {
        setForm({ ...form, targetRole: filtered.filter((r: string) => r !== role) });
      } else {
        setForm({ ...form, targetRole: [...filtered, role] });
      }
    }
  };

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <h1 className="text-2xl font-bold text-gray-900 dark:text-white">Notifikasi Platform</h1>
        <Button onClick={openCreate} className="bg-purple-600 hover:bg-purple-700">
          <Plus className="w-4 h-4 mr-2" /> Buat Notifikasi
        </Button>
      </div>

      {isLoading ? (
        <div className="space-y-3">
          {[...Array(3)].map((_, i) => (
            <Card key={i} className="bg-white dark:bg-slate-900 border-gray-200 dark:border-slate-800 animate-pulse">
              <CardContent className="p-4"><div className="h-16" /></CardContent>
            </Card>
          ))}
        </div>
      ) : notifications.length === 0 ? (
        <Card className="bg-white dark:bg-slate-900 border-gray-200 dark:border-slate-800">
          <CardContent className="p-8 text-center text-gray-400 dark:text-slate-400">
            Belum ada notifikasi. Klik tombol di atas untuk membuat notifikasi baru.
          </CardContent>
        </Card>
      ) : (
        <div className="space-y-3">
          {notifications.map((n: any) => {
            const tipeConfig = TIPE_OPTIONS.find((t) => t.value === n.tipe) || TIPE_OPTIONS[0];
            const TipeIcon = tipeConfig.icon;
            return (
              <Card key={n.id} className="bg-white dark:bg-slate-900 border-gray-200 dark:border-slate-800">
                <CardContent className="p-4">
                  <div className="flex items-start justify-between gap-3">
                    <div className="flex items-start gap-3 flex-1 min-w-0">
                      <div className={cn("mt-0.5 shrink-0", tipeConfig.color)}>
                        <TipeIcon className="w-5 h-5" />
                      </div>
                      <div className="min-w-0 flex-1">
                        <div className="flex items-center gap-2 flex-wrap">
                          <h3 className="font-medium text-gray-900 dark:text-white">{n.judul}</h3>
                          <span className={cn(
                            "px-1.5 py-0.5 rounded text-[10px] font-medium",
                            n.isPublished
                              ? "bg-green-100 text-green-700 dark:bg-green-500/20 dark:text-green-400"
                              : "bg-gray-100 text-gray-500 dark:bg-slate-700 dark:text-slate-400"
                          )}>
                            {n.isPublished ? "Published" : "Draft"}
                          </span>
                          <span className="px-1.5 py-0.5 rounded text-[10px] font-medium bg-purple-100 text-purple-700 dark:bg-purple-500/20 dark:text-purple-400 capitalize">
                            {n.priority}
                          </span>
                        </div>
                        <p className="text-sm text-gray-500 dark:text-slate-400 mt-0.5 line-clamp-2">{n.pesan}</p>
                        <div className="flex items-center gap-2 mt-1.5 text-xs text-gray-400 dark:text-slate-500">
                          <span>Target: {(n.targetRole || []).join(", ")}</span>
                          <span>·</span>
                          <span>{n._count?.reads || 0} dibaca</span>
                          {n.publishedAt && (
                            <>
                              <span>·</span>
                              <span>{new Date(n.publishedAt).toLocaleDateString("id-ID")}</span>
                            </>
                          )}
                        </div>
                      </div>
                    </div>
                    <div className="flex items-center gap-1 shrink-0">
                      <Button size="icon" variant="ghost" className="h-8 w-8 text-gray-400 hover:text-gray-900 dark:text-slate-400 dark:hover:text-white" onClick={() => openEdit(n)}>
                        <Pencil className="w-3.5 h-3.5" />
                      </Button>
                      <Button size="icon" variant="ghost" className="h-8 w-8 text-gray-400 hover:text-red-500 dark:text-slate-400 dark:hover:text-red-400" onClick={() => handleDelete(n.id)}>
                        <Trash2 className="w-3.5 h-3.5" />
                      </Button>
                    </div>
                  </div>
                </CardContent>
              </Card>
            );
          })}
        </div>
      )}

      <Dialog open={showDialog} onOpenChange={setShowDialog}>
        <DialogContent className="max-w-lg max-h-[90vh] overflow-y-auto">
          <DialogHeader>
            <DialogTitle>{editId ? "Edit Notifikasi" : "Buat Notifikasi Baru"}</DialogTitle>
            <DialogDescription>Kirim notifikasi ke guru, admin, atau siswa di seluruh platform</DialogDescription>
          </DialogHeader>
          <div className="space-y-4">
            <div className="space-y-1.5">
              <Label>Judul</Label>
              <Input placeholder="Judul notifikasi" value={form.judul} onChange={(e) => setForm({ ...form, judul: e.target.value })} />
            </div>
            <div className="space-y-1.5">
              <Label>Pesan</Label>
              <Textarea placeholder="Isi pesan notifikasi..." value={form.pesan} onChange={(e) => setForm({ ...form, pesan: e.target.value })} rows={4} />
            </div>
            <div className="grid grid-cols-2 gap-3">
              <div className="space-y-1.5">
                <Label>Tipe</Label>
                <Select value={form.tipe} onValueChange={(v) => setForm({ ...form, tipe: v })}>
                  <SelectTrigger><SelectValue /></SelectTrigger>
                  <SelectContent>
                    {TIPE_OPTIONS.map((t) => (
                      <SelectItem key={t.value} value={t.value}>{t.label}</SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </div>
              <div className="space-y-1.5">
                <Label>Prioritas</Label>
                <Select value={form.priority} onValueChange={(v) => setForm({ ...form, priority: v })}>
                  <SelectTrigger><SelectValue /></SelectTrigger>
                  <SelectContent>
                    {PRIORITY_OPTIONS.map((p) => (
                      <SelectItem key={p} value={p} className="capitalize">{p}</SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </div>
            </div>
            <div className="space-y-1.5">
              <Label>Target Role</Label>
              <div className="flex flex-wrap gap-2">
                {ROLE_OPTIONS.map((role) => (
                  <button
                    key={role}
                    onClick={() => toggleRole(role)}
                    className={cn(
                      "px-3 py-1.5 rounded-lg text-xs font-medium border transition-colors",
                      (form.targetRole || []).includes(role)
                        ? "bg-purple-600 text-white border-purple-600"
                        : "bg-gray-100 text-gray-600 border-gray-200 dark:bg-slate-800 dark:text-slate-300 dark:border-slate-700"
                    )}
                  >
                    {role}
                  </button>
                ))}
              </div>
            </div>
            <div className="space-y-1.5">
              <Label>Kadaluarsa (opsional)</Label>
              <Input type="datetime-local" value={form.expiresAt} onChange={(e) => setForm({ ...form, expiresAt: e.target.value })} />
            </div>
            <div className="flex gap-2">
              <Button onClick={() => handleSave(false)} disabled={saving} variant="outline" className="flex-1">
                {saving ? <Loader2 className="w-4 h-4 mr-2 animate-spin" /> : null}
                Simpan Draft
              </Button>
              <Button onClick={() => handleSave(true)} disabled={saving} className="flex-1 bg-purple-600 hover:bg-purple-700">
                {saving ? <Loader2 className="w-4 h-4 mr-2 animate-spin" /> : <Send className="w-4 h-4 mr-2" />}
                Publish
              </Button>
            </div>
          </div>
        </DialogContent>
      </Dialog>
    </div>
  );
}

// frontend-nuxt/pages/superadmin/notifications/index.vue
<template>
  <div>
    <div class="flex items-center justify-between mb-6">
      <div>
        <h2 class="text-lg font-semibold text-gray-900">Platform Notifications</h2>
        <p class="text-sm text-gray-500">Kelola notifikasi untuk semua pengguna platform</p>
      </div>
      <Button @click="showCreate = true" size="sm">
        <Icon name="lucide:plus" class="w-4 h-4 mr-1.5" />
        Buat Notifikasi
      </Button>
    </div>

    <!-- Loading -->
    <div v-if="loading" class="flex justify-center py-12">
      <Icon name="lucide:loader-2" class="w-6 h-6 text-gray-400 animate-spin" />
    </div>

    <!-- Empty -->
    <div v-else-if="notifications.length === 0" class="text-center py-16 bg-white rounded-xl border border-gray-100">
      <Icon name="lucide:bell-off" class="w-12 h-12 text-gray-300 mx-auto mb-3" />
      <p class="text-gray-500">Belum ada notifikasi platform</p>
    </div>

    <!-- List -->
    <div v-else class="space-y-3">
      <div
        v-for="notif in notifications"
        :key="notif.id"
        class="bg-white rounded-xl border border-gray-100 p-4 hover:shadow-sm transition-shadow"
      >
        <div class="flex items-start justify-between gap-4">
          <div class="flex items-start gap-3 min-w-0">
            <div :class="['w-10 h-10 rounded-lg flex items-center justify-center flex-shrink-0', typeColor(notif.tipe)]">
              <Icon :name="typeIcon(notif.tipe)" class="w-5 h-5" />
            </div>
            <div class="min-w-0">
              <div class="flex items-center gap-2 mb-1">
                <h3 class="text-sm font-semibold text-gray-900 truncate">{{ notif.judul }}</h3>
                <Badge :variant="notif.isPublished ? 'success' : 'default'" size="sm">
                  {{ notif.isPublished ? 'Published' : 'Draft' }}
                </Badge>
                <Badge variant="info" size="sm">{{ notif.tipe }}</Badge>
              </div>
              <p class="text-sm text-gray-500 line-clamp-2">{{ notif.pesan }}</p>
              <div class="flex items-center gap-3 mt-2 text-xs text-gray-400">
                <span>Target: {{ notif.targetRole?.join(', ') || 'ALL' }}</span>
                <span>Priority: {{ notif.priority }}</span>
                <span v-if="notif.readCount">{{ notif.readCount }} dibaca</span>
              </div>
            </div>
          </div>
          <div class="flex items-center gap-1 flex-shrink-0">
            <button
              v-if="!notif.isPublished"
              @click="publishNotif(notif)"
              class="p-1.5 rounded-lg hover:bg-green-50 text-gray-400 hover:text-green-600 transition-colors"
              title="Publish"
            >
              <Icon name="lucide:send" class="w-4 h-4" />
            </button>
            <button
              @click="deleteNotif(notif.id)"
              class="p-1.5 rounded-lg hover:bg-red-50 text-gray-400 hover:text-red-500 transition-colors"
              title="Hapus"
            >
              <Icon name="lucide:trash-2" class="w-4 h-4" />
            </button>
          </div>
        </div>
      </div>
    </div>

    <!-- Create Modal -->
    <Modal v-model="showCreate" title="Buat Notifikasi Baru">
      <form @submit.prevent="handleCreate" class="space-y-4">
        <div class="space-y-2">
          <Label>Judul</Label>
          <Input v-model="form.judul" placeholder="Judul notifikasi" />
        </div>
        <div class="space-y-2">
          <Label>Pesan</Label>
          <textarea
            v-model="form.pesan"
            rows="4"
            class="w-full rounded-lg border border-gray-200 px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:border-transparent"
            placeholder="Isi pesan notifikasi..."
          />
        </div>
        <div class="grid grid-cols-2 gap-4">
          <div class="space-y-2">
            <Label>Tipe</Label>
            <select v-model="form.tipe" class="w-full rounded-lg border border-gray-200 px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-indigo-500">
              <option value="info">Info</option>
              <option value="warning">Warning</option>
              <option value="update">Update</option>
              <option value="maintenance">Maintenance</option>
              <option value="promo">Promo</option>
            </select>
          </div>
          <div class="space-y-2">
            <Label>Priority</Label>
            <select v-model="form.priority" class="w-full rounded-lg border border-gray-200 px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-indigo-500">
              <option value="low">Low</option>
              <option value="normal">Normal</option>
              <option value="high">High</option>
              <option value="urgent">Urgent</option>
            </select>
          </div>
        </div>
        <div class="flex items-center gap-2">
          <input type="checkbox" v-model="form.isPublished" id="publish" class="rounded border-gray-300" />
          <label for="publish" class="text-sm text-gray-700">Langsung publish</label>
        </div>
        <div class="flex justify-end gap-2 pt-2">
          <Button variant="outline" type="button" @click="showCreate = false">Batal</Button>
          <Button type="submit" :loading="creating">Buat</Button>
        </div>
      </form>
    </Modal>
  </div>
</template>

<script setup lang="ts">
import { toast } from 'vue-sonner'

definePageMeta({ layout: 'superadmin' })
useHead({ title: 'Platform Notifications' })

const loading = ref(true)
const creating = ref(false)
const showCreate = ref(false)
const notifications = ref<any[]>([])

const form = reactive({
  judul: '',
  pesan: '',
  tipe: 'info',
  priority: 'normal',
  targetRole: ['ALL'],
  isPublished: false,
})

const typeIcon = (tipe: string) => {
  const icons: Record<string, string> = {
    info: 'lucide:info', warning: 'lucide:alert-triangle', update: 'lucide:sparkles',
    maintenance: 'lucide:wrench', promo: 'lucide:gift',
  }
  return icons[tipe] || 'lucide:info'
}

const typeColor = (tipe: string) => {
  const colors: Record<string, string> = {
    info: 'bg-blue-100 text-blue-600', warning: 'bg-amber-100 text-amber-600',
    update: 'bg-green-100 text-green-600', maintenance: 'bg-red-100 text-red-600',
    promo: 'bg-purple-100 text-purple-600',
  }
  return colors[tipe] || 'bg-blue-100 text-blue-600'
}

const fetchNotifications = async () => {
  loading.value = true
  try {
    const token = typeof window !== 'undefined' ? localStorage.getItem('superadmin_token') : null
    const apiUrl = String(useRuntimeConfig().public.apiUrl || 'http://localhost:5000/api').replace(/\/api$/, '')
    const res = await fetch(`${apiUrl}/api/superadmin/notifications`, {
      headers: token ? { 'Authorization': `Bearer ${token}` } : {},
      credentials: 'include',
    })
    const data = await res.json()
    if (data.success) notifications.value = data.data || []
  } catch (err) {
    console.error(err)
  } finally {
    loading.value = false
  }
}

const handleCreate = async () => {
  if (!form.judul || !form.pesan) {
    toast.error('Judul dan pesan wajib diisi')
    return
  }
  creating.value = true
  try {
    const token = typeof window !== 'undefined' ? localStorage.getItem('superadmin_token') : null
    const apiUrl = String(useRuntimeConfig().public.apiUrl || 'http://localhost:5000/api').replace(/\/api$/, '')
    const res = await fetch(`${apiUrl}/api/superadmin/notifications`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json', ...(token ? { 'Authorization': `Bearer ${token}` } : {}) },
      credentials: 'include',
      body: JSON.stringify(form),
    })
    const data = await res.json()
    if (data.success) {
      toast.success('Notifikasi berhasil dibuat')
      showCreate.value = false
      form.judul = ''
      form.pesan = ''
      form.tipe = 'info'
      form.priority = 'normal'
      form.isPublished = false
      await fetchNotifications()
    } else {
      toast.error(data.error || 'Gagal membuat notifikasi')
    }
  } catch (err) {
    toast.error('Terjadi kesalahan')
  } finally {
    creating.value = false
  }
}

const publishNotif = async (notif: any) => {
  try {
    const token = typeof window !== 'undefined' ? localStorage.getItem('superadmin_token') : null
    const apiUrl = String(useRuntimeConfig().public.apiUrl || 'http://localhost:5000/api').replace(/\/api$/, '')
    const res = await fetch(`${apiUrl}/api/superadmin/notifications/${notif.id}`, {
      method: 'PUT',
      headers: { 'Content-Type': 'application/json', ...(token ? { 'Authorization': `Bearer ${token}` } : {}) },
      credentials: 'include',
      body: JSON.stringify({ isPublished: true }),
    })
    const data = await res.json()
    if (data.success) {
      toast.success('Notifikasi dipublish')
      await fetchNotifications()
    }
  } catch (err) {
    toast.error('Gagal publish')
  }
}

const deleteNotif = async (id: string) => {
  if (!confirm('Hapus notifikasi ini?')) return
  try {
    const token = typeof window !== 'undefined' ? localStorage.getItem('superadmin_token') : null
    const apiUrl = String(useRuntimeConfig().public.apiUrl || 'http://localhost:5000/api').replace(/\/api$/, '')
    const res = await fetch(`${apiUrl}/api/superadmin/notifications/${id}`, {
      method: 'DELETE',
      headers: token ? { 'Authorization': `Bearer ${token}` } : {},
      credentials: 'include',
    })
    const data = await res.json()
    if (data.success) {
      toast.success('Notifikasi dihapus')
      notifications.value = notifications.value.filter(n => n.id !== id)
    }
  } catch (err) {
    toast.error('Gagal menghapus')
  }
}

onMounted(fetchNotifications)
</script>
