// src/app/superadmin/page.tsx
"use client";

import useSWR from "swr";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { School, Users, GraduationCap, BookOpen, ClipboardList, Building2 } from "lucide-react";

const fetcher = (url: string) => fetch(url, { credentials: "include" }).then((r) => r.json());

export default function SuperAdminDashboard() {
  const { data, isLoading } = useSWR("/api/superadmin/stats", fetcher, {
    refreshInterval: 30000,
  });

  const stats = data?.data;

  if (isLoading) {
    return (
      <div className="space-y-6">
        <h1 className="text-2xl font-bold text-gray-900 dark:text-white">Dashboard</h1>
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
          {[...Array(6)].map((_, i) => (
            <Card key={i} className="bg-white dark:bg-slate-900 border-gray-200 dark:border-slate-800 animate-pulse">
              <CardContent className="p-6"><div className="h-16" /></CardContent>
            </Card>
          ))}
        </div>
      </div>
    );
  }

  const statCards = [
    {
      title: "Total Sekolah",
      value: stats?.schools?.total || 0,
      subtitle: `${stats?.schools?.active || 0} aktif, ${stats?.schools?.inactive || 0} nonaktif`,
      icon: Building2,
      color: "text-purple-600 dark:text-purple-400",
      bg: "bg-purple-100 dark:bg-purple-500/10",
    },
    {
      title: "Total User",
      value: stats?.users?.total || 0,
      subtitle: "Semua role",
      icon: Users,
      color: "text-blue-600 dark:text-blue-400",
      bg: "bg-blue-100 dark:bg-blue-500/10",
    },
    {
      title: "Total Guru",
      value: stats?.users?.guru || 0,
      subtitle: "Seluruh sekolah",
      icon: School,
      color: "text-green-600 dark:text-green-400",
      bg: "bg-green-100 dark:bg-green-500/10",
    },
    {
      title: "Total Siswa",
      value: stats?.users?.siswa || 0,
      subtitle: "Seluruh sekolah",
      icon: GraduationCap,
      color: "text-yellow-600 dark:text-yellow-400",
      bg: "bg-yellow-100 dark:bg-yellow-500/10",
    },
    {
      title: "Total Ujian",
      value: stats?.content?.ujian || 0,
      subtitle: "Seluruh sekolah",
      icon: ClipboardList,
      color: "text-red-600 dark:text-red-400",
      bg: "bg-red-100 dark:bg-red-500/10",
    },
    {
      title: "Total Tugas",
      value: stats?.content?.tugas || 0,
      subtitle: "Seluruh sekolah",
      icon: BookOpen,
      color: "text-cyan-600 dark:text-cyan-400",
      bg: "bg-cyan-100 dark:bg-cyan-500/10",
    },
  ];

  return (
    <div className="space-y-6">
      <h1 className="text-2xl font-bold text-gray-900 dark:text-white">Dashboard</h1>

      {/* Stat Cards */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
        {statCards.map((card) => (
          <Card key={card.title} className="bg-white dark:bg-slate-900 border-gray-200 dark:border-slate-800">
            <CardContent className="p-5">
              <div className="flex items-center justify-between">
                <div>
                  <p className="text-xs text-gray-500 dark:text-slate-400 font-medium">{card.title}</p>
                  <p className="text-2xl font-bold mt-1 text-gray-900 dark:text-white">{card.value.toLocaleString()}</p>
                  <p className="text-xs text-gray-400 dark:text-slate-500 mt-0.5">{card.subtitle}</p>
                </div>
                <div className={`w-10 h-10 rounded-lg ${card.bg} flex items-center justify-center`}>
                  <card.icon className={`w-5 h-5 ${card.color}`} />
                </div>
              </div>
            </CardContent>
          </Card>
        ))}
      </div>

      {/* Tier Breakdown */}
      {stats?.tierBreakdown && (
        <Card className="bg-white dark:bg-slate-900 border-gray-200 dark:border-slate-800">
          <CardHeader>
            <CardTitle className="text-base text-gray-900 dark:text-white">Tier Breakdown</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="flex flex-wrap gap-4">
              {Object.entries(stats.tierBreakdown as Record<string, number>).map(([tier, count]) => (
                <div key={tier} className="flex items-center gap-2 px-3 py-2 bg-gray-100 dark:bg-slate-800 rounded-lg">
                  <span className="text-xs font-medium text-gray-500 dark:text-slate-400">{tier}</span>
                  <span className="text-sm font-bold text-gray-900 dark:text-white">{count}</span>
                </div>
              ))}
            </div>
          </CardContent>
        </Card>
      )}

      {/* Recent Schools */}
      {stats?.recentSchools && stats.recentSchools.length > 0 && (
        <Card className="bg-white dark:bg-slate-900 border-gray-200 dark:border-slate-800">
          <CardHeader>
            <CardTitle className="text-base text-gray-900 dark:text-white">Sekolah Terbaru</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="space-y-3">
              {stats.recentSchools.map((school: any) => (
                <div
                  key={school.id}
                  className="flex items-center justify-between p-3 bg-gray-50 dark:bg-slate-800 rounded-lg"
                >
                  <div>
                    <p className="text-sm font-medium text-gray-900 dark:text-white">{school.nama}</p>
                    <p className="text-xs text-gray-500 dark:text-slate-400">
                      {school.kota || "-"} &middot; {school.jenjang || "-"} &middot;{" "}
                      <span className={school.isActive ? "text-green-400" : "text-red-400"}>
                        {school.isActive ? "Aktif" : "Nonaktif"}
                      </span>
                    </p>
                  </div>
                  <div className="text-right text-xs text-gray-500 dark:text-slate-400">
                    <p>{school._count?.guru || 0} guru</p>
                    <p>{school._count?.siswa || 0} siswa</p>
                  </div>
                </div>
              ))}
            </div>
          </CardContent>
        </Card>
      )}
    </div>
  );
}

// frontend-nuxt/pages/superadmin/index.vue
<template>
  <div class="space-y-6">
    <!-- Stats Cards -->
    <div class="grid grid-cols-2 lg:grid-cols-4 gap-4">
      <div class="bg-white rounded-2xl p-5 card-shadow">
        <div class="flex items-center gap-3 mb-3">
          <div class="w-10 h-10 rounded-xl bg-indigo-100 flex items-center justify-center">
            <Icon name="lucide:school" class="w-5 h-5 text-indigo-600" />
          </div>
        </div>
        <p class="text-2xl font-bold text-gray-900">{{ stats?.schools?.total ?? '-' }}</p>
        <p class="text-xs text-gray-400 mt-1">Total Sekolah</p>
        <div class="flex items-center gap-2 mt-2">
          <span class="text-xs text-green-600">{{ stats?.schools?.active ?? 0 }} aktif</span>
          <span class="text-xs text-gray-300">·</span>
          <span class="text-xs text-red-500">{{ stats?.schools?.inactive ?? 0 }} nonaktif</span>
        </div>
      </div>

      <div class="bg-white rounded-2xl p-5 card-shadow">
        <div class="flex items-center gap-3 mb-3">
          <div class="w-10 h-10 rounded-xl bg-emerald-100 flex items-center justify-center">
            <Icon name="lucide:users" class="w-5 h-5 text-emerald-600" />
          </div>
        </div>
        <p class="text-2xl font-bold text-gray-900">{{ stats?.users?.total ?? '-' }}</p>
        <p class="text-xs text-gray-400 mt-1">Total Users</p>
        <div class="flex items-center gap-2 mt-2">
          <span class="text-xs text-blue-600">{{ stats?.users?.guru ?? 0 }} guru</span>
          <span class="text-xs text-gray-300">·</span>
          <span class="text-xs text-purple-600">{{ stats?.users?.siswa ?? 0 }} siswa</span>
        </div>
      </div>

      <div class="bg-white rounded-2xl p-5 card-shadow">
        <div class="flex items-center gap-3 mb-3">
          <div class="w-10 h-10 rounded-xl bg-amber-100 flex items-center justify-center">
            <Icon name="lucide:file-text" class="w-5 h-5 text-amber-600" />
          </div>
        </div>
        <p class="text-2xl font-bold text-gray-900">{{ stats?.content?.ujian ?? '-' }}</p>
        <p class="text-xs text-gray-400 mt-1">Total Ujian</p>
      </div>

      <div class="bg-white rounded-2xl p-5 card-shadow">
        <div class="flex items-center gap-3 mb-3">
          <div class="w-10 h-10 rounded-xl bg-pink-100 flex items-center justify-center">
            <Icon name="lucide:crown" class="w-5 h-5 text-pink-600" />
          </div>
        </div>
        <p class="text-2xl font-bold text-gray-900">{{ tierCount }}</p>
        <p class="text-xs text-gray-400 mt-1">Paket Tier</p>
        <div v-if="stats?.tierBreakdown" class="flex flex-wrap gap-1 mt-2">
          <span v-for="(count, label) in stats.tierBreakdown" :key="label" class="text-xs text-gray-500">
            {{ label }}: {{ count }}
          </span>
        </div>
      </div>
    </div>

    <!-- Recent Schools -->
    <div class="bg-white rounded-2xl card-shadow overflow-hidden">
      <div class="flex items-center justify-between px-6 py-4 border-b border-gray-100">
        <h3 class="text-lg font-semibold text-gray-900">Sekolah Terbaru</h3>
        <NuxtLink to="/superadmin/schools" class="text-sm text-indigo-600 hover:text-indigo-500 transition-colors">
          Lihat Semua →
        </NuxtLink>
      </div>

      <div v-if="isLoading" class="flex items-center justify-center py-12">
        <Icon name="lucide:loader-2" class="w-6 h-6 animate-spin text-indigo-600" />
      </div>

      <table v-else-if="stats?.recentSchools?.length" class="w-full">
        <thead>
          <tr class="border-b border-gray-100">
            <th class="px-6 py-3 text-left text-xs font-semibold text-gray-400 uppercase">Sekolah</th>
            <th class="px-6 py-3 text-left text-xs font-semibold text-gray-400 uppercase">Kota</th>
            <th class="px-6 py-3 text-center text-xs font-semibold text-gray-400 uppercase">Guru</th>
            <th class="px-6 py-3 text-center text-xs font-semibold text-gray-400 uppercase">Siswa</th>
            <th class="px-6 py-3 text-center text-xs font-semibold text-gray-400 uppercase">Status</th>
          </tr>
        </thead>
        <tbody>
          <tr v-for="school in stats.recentSchools" :key="school.id" class="border-b border-gray-50 hover:bg-gray-50 transition-colors">
            <td class="px-6 py-3">
              <NuxtLink :to="`/superadmin/schools/${school.id}`" class="text-sm font-medium text-gray-900 hover:text-indigo-600 transition-colors">
                {{ school.nama }}
              </NuxtLink>
              <p class="text-xs text-gray-400">{{ school.jenjang || '-' }}</p>
            </td>
            <td class="px-6 py-3 text-sm text-gray-500">{{ school.kota || '-' }}</td>
            <td class="px-6 py-3 text-sm text-gray-500 text-center">{{ school._count?.guru ?? 0 }}</td>
            <td class="px-6 py-3 text-sm text-gray-500 text-center">{{ school._count?.siswa ?? 0 }}</td>
            <td class="px-6 py-3 text-center">
              <span :class="[
                'px-2 py-1 text-xs rounded-full font-medium',
                school.isActive ? 'bg-green-50 text-green-600 border border-green-200' : 'bg-red-50 text-red-600 border border-red-200'
              ]">
                {{ school.isActive ? 'Aktif' : 'Nonaktif' }}
              </span>
            </td>
          </tr>
        </tbody>
      </table>

      <div v-else class="py-12 text-center">
        <p class="text-gray-400">Belum ada sekolah terdaftar</p>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
definePageMeta({ layout: 'superadmin' })
useHead({ title: 'Super Admin Dashboard' })

const { data: stats, isLoading } = useSuperAdminStats()

const tierCount = computed(() => {
  if (!stats.value?.tierBreakdown) return 0
  return Object.keys(stats.value.tierBreakdown).length
})
</script>
