// frontend-nuxt/components/NotificationBell.vue
<template>
  <div class="relative">
    <button
      @click="open = !open"
      class="relative p-2 rounded-lg hover:bg-gray-100 transition-colors"
    >
      <Icon name="lucide:bell" class="w-5 h-5 text-gray-500" />
      <span
        v-if="unreadCount > 0"
        class="absolute -top-0.5 -right-0.5 w-4.5 h-4.5 bg-red-500 text-white text-[10px] font-bold rounded-full flex items-center justify-center min-w-[18px] h-[18px]"
      >
        {{ unreadCount > 9 ? '9+' : unreadCount }}
      </span>
    </button>

    <!-- Dropdown -->
    <Transition
      enter-active-class="transition ease-out duration-200"
      enter-from-class="opacity-0 translate-y-1"
      enter-to-class="opacity-100 translate-y-0"
      leave-active-class="transition ease-in duration-150"
      leave-from-class="opacity-100 translate-y-0"
      leave-to-class="opacity-0 translate-y-1"
    >
      <div
        v-if="open"
        class="absolute right-0 top-full mt-2 w-80 bg-white rounded-xl shadow-lg border border-gray-100 z-50 overflow-hidden"
      >
        <div class="flex items-center justify-between px-4 py-3 border-b border-gray-100">
          <h3 class="text-sm font-semibold text-gray-900">Notifikasi</h3>
          <span v-if="unreadCount > 0" class="text-xs text-orange-500 font-medium">
            {{ unreadCount }} belum dibaca
          </span>
        </div>

        <div class="max-h-80 overflow-y-auto">
          <div v-if="loading" class="p-6 text-center">
            <Icon name="lucide:loader-2" class="w-5 h-5 text-gray-400 animate-spin mx-auto" />
          </div>

          <div v-else-if="notifications.length === 0" class="p-6 text-center">
            <Icon name="lucide:bell-off" class="w-8 h-8 text-gray-300 mx-auto mb-2" />
            <p class="text-sm text-gray-400">Tidak ada notifikasi</p>
          </div>

          <div v-else>
            <button
              v-for="notif in notifications"
              :key="notif.id"
              @click="markAsRead(notif)"
              :class="[
                'w-full text-left px-4 py-3 border-b border-gray-50 hover:bg-gray-50 transition-colors',
                !notif.isRead ? 'bg-orange-50/50' : ''
              ]"
            >
              <div class="flex items-start gap-3">
                <div
                  :class="[
                    'w-8 h-8 rounded-lg flex items-center justify-center flex-shrink-0 mt-0.5',
                    typeStyles[notif.tipe]?.bg || 'bg-blue-100'
                  ]"
                >
                  <Icon
                    :name="typeStyles[notif.tipe]?.icon || 'lucide:info'"
                    :class="['w-4 h-4', typeStyles[notif.tipe]?.text || 'text-blue-600']"
                  />
                </div>
                <div class="min-w-0 flex-1">
                  <p class="text-sm font-medium text-gray-900 truncate">{{ notif.judul }}</p>
                  <p class="text-xs text-gray-500 line-clamp-2 mt-0.5">{{ notif.pesan }}</p>
                  <p class="text-[10px] text-gray-400 mt-1">{{ formatTime(notif.publishedAt) }}</p>
                </div>
                <div v-if="!notif.isRead" class="w-2 h-2 bg-orange-500 rounded-full flex-shrink-0 mt-2" />
              </div>
            </button>
          </div>
        </div>
      </div>
    </Transition>

    <!-- Click outside to close -->
    <div v-if="open" class="fixed inset-0 z-40" @click="open = false" />
  </div>
</template>

<script setup lang="ts">
interface PlatformNotification {
  id: string
  judul: string
  pesan: string
  tipe: string
  priority: string
  publishedAt: string
  isRead: boolean
}

const open = ref(false)
const loading = ref(false)
const notifications = ref<PlatformNotification[]>([])
const unreadCount = ref(0)

const typeStyles: Record<string, { bg: string; text: string; icon: string }> = {
  info: { bg: 'bg-blue-100', text: 'text-blue-600', icon: 'lucide:info' },
  warning: { bg: 'bg-amber-100', text: 'text-amber-600', icon: 'lucide:alert-triangle' },
  update: { bg: 'bg-green-100', text: 'text-green-600', icon: 'lucide:sparkles' },
  maintenance: { bg: 'bg-red-100', text: 'text-red-600', icon: 'lucide:wrench' },
  promo: { bg: 'bg-purple-100', text: 'text-purple-600', icon: 'lucide:gift' },
}

const formatTime = (dateStr: string) => {
  if (!dateStr) return ''
  const date = new Date(dateStr)
  const now = new Date()
  const diffMs = now.getTime() - date.getTime()
  const diffMin = Math.floor(diffMs / 60000)
  if (diffMin < 1) return 'Baru saja'
  if (diffMin < 60) return `${diffMin} menit lalu`
  const diffHr = Math.floor(diffMin / 60)
  if (diffHr < 24) return `${diffHr} jam lalu`
  const diffDay = Math.floor(diffHr / 24)
  if (diffDay < 7) return `${diffDay} hari lalu`
  return date.toLocaleDateString('id-ID', { day: 'numeric', month: 'short' })
}

const fetchNotifications = async () => {
  loading.value = true
  try {
    const response = await fetchApi('/api/notifications/platform')
    const data = await response.json()
    if (data.success) {
      notifications.value = data.data || []
      unreadCount.value = data.unreadCount || 0
    }
  } catch (err) {
    console.error('Error fetching notifications:', err)
  } finally {
    loading.value = false
  }
}

const markAsRead = async (notif: PlatformNotification) => {
  if (notif.isRead) return
  try {
    await fetchApi('/api/notifications/platform/read', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ notificationId: notif.id }),
    })
    notif.isRead = true
    unreadCount.value = Math.max(0, unreadCount.value - 1)
  } catch (err) {
    console.error('Error marking notification:', err)
  }
}

onMounted(() => {
  fetchNotifications()
})

// Refresh every 60 seconds
let interval: ReturnType<typeof setInterval>
onMounted(() => {
  interval = setInterval(fetchNotifications, 60000)
})
onUnmounted(() => {
  clearInterval(interval)
})
</script>

// src/components/notification-bell.tsx
"use client";

import { useState, useRef, useEffect, useCallback } from "react";
import { createPortal } from "react-dom";
import useSWR from "swr";
import { Bell, X, CheckCheck, Info, AlertTriangle, Wrench, Megaphone } from "lucide-react";
import { cn } from "@/lib/utils";

const fetcher = (url: string) => fetch(url, { credentials: "include" }).then((r) => r.json());

const TIPE_ICONS: Record<string, any> = {
  info: Info,
  warning: AlertTriangle,
  update: Bell,
  maintenance: Wrench,
  promo: Megaphone,
};

const TIPE_COLORS: Record<string, string> = {
  info: "text-blue-500",
  warning: "text-yellow-500",
  update: "text-green-500",
  maintenance: "text-orange-500",
  promo: "text-purple-500",
};

const PRIORITY_COLORS: Record<string, string> = {
  urgent: "border-l-red-500",
  high: "border-l-orange-500",
  normal: "border-l-transparent",
  low: "border-l-transparent",
};

export function NotificationBell() {
  const { data, mutate } = useSWR("/api/notifications", fetcher, {
    refreshInterval: 15000,
    revalidateOnFocus: true,
    revalidateOnReconnect: true,
    dedupingInterval: 5000,
  });
  const [open, setOpen] = useState(false);
  const buttonRef = useRef<HTMLButtonElement>(null);
  const panelRef = useRef<HTMLDivElement>(null);
  const [panelPos, setPanelPos] = useState({ top: 0, right: 0 });

  const notifications = data?.data || [];
  const unreadCount = data?.unreadCount || 0;

  // Calculate panel position relative to button
  const updatePosition = useCallback(() => {
    if (!buttonRef.current) return;
    const rect = buttonRef.current.getBoundingClientRect();
    setPanelPos({
      top: rect.bottom + 8,
      right: window.innerWidth - rect.right,
    });
  }, []);

  // Refresh data when panel opens
  useEffect(() => {
    if (open) {
      mutate();
      updatePosition();
      window.addEventListener("resize", updatePosition);
      window.addEventListener("scroll", updatePosition, true);
      return () => {
        window.removeEventListener("resize", updatePosition);
        window.removeEventListener("scroll", updatePosition, true);
      };
    }
  }, [open, mutate, updatePosition]);

  // Close on click outside
  useEffect(() => {
    if (!open) return;
    const handler = (e: MouseEvent) => {
      const target = e.target as Node;
      if (
        buttonRef.current && !buttonRef.current.contains(target) &&
        panelRef.current && !panelRef.current.contains(target)
      ) {
        setOpen(false);
      }
    };
    document.addEventListener("mousedown", handler);
    return () => document.removeEventListener("mousedown", handler);
  }, [open]);

  // Close on Escape
  useEffect(() => {
    if (!open) return;
    const handler = (e: KeyboardEvent) => {
      if (e.key === "Escape") setOpen(false);
    };
    document.addEventListener("keydown", handler);
    return () => document.removeEventListener("keydown", handler);
  }, [open]);

  const markAsRead = async (notificationId: string) => {
    await fetch("/api/notifications", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      credentials: "include",
      body: JSON.stringify({ notificationId }),
    });
    mutate();
  };

  const markAllRead = async () => {
    await fetch("/api/notifications", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      credentials: "include",
      body: JSON.stringify({ markAllRead: true }),
    });
    mutate();
  };

  const panel = open
    ? createPortal(
        <div
          ref={panelRef}
          style={{ position: "fixed", top: panelPos.top, right: panelPos.right, zIndex: 9999 }}
          className="w-80 sm:w-96 bg-white dark:bg-slate-900 border border-gray-200 dark:border-slate-700 rounded-xl shadow-2xl overflow-hidden animate-in fade-in-0 zoom-in-95 duration-150"
        >
          {/* Header */}
          <div className="flex items-center justify-between px-4 py-3 border-b border-gray-100 dark:border-slate-800">
            <h3 className="font-semibold text-sm text-gray-900 dark:text-white">Notifikasi</h3>
            <div className="flex items-center gap-1">
              {unreadCount > 0 && (
                <button
                  onClick={markAllRead}
                  className="text-xs text-purple-600 dark:text-purple-400 hover:underline flex items-center gap-1"
                >
                  <CheckCheck className="w-3 h-3" />
                  Tandai semua
                </button>
              )}
              <button onClick={() => setOpen(false)} className="p-1 hover:bg-gray-100 dark:hover:bg-slate-800 rounded">
                <X className="w-4 h-4 text-gray-400" />
              </button>
            </div>
          </div>

          {/* List */}
          <div className="max-h-80 overflow-y-auto">
            {notifications.length === 0 ? (
              <div className="p-6 text-center text-sm text-gray-400 dark:text-slate-500">
                Tidak ada notifikasi
              </div>
            ) : (
              notifications.map((n: any) => {
                const Icon = TIPE_ICONS[n.tipe] || Info;
                const iconColor = TIPE_COLORS[n.tipe] || "text-gray-500";
                const priorityBorder = PRIORITY_COLORS[n.priority] || "";
                return (
                  <div
                    key={n.id}
                    className={cn(
                      "px-4 py-3 border-b border-gray-50 dark:border-slate-800/50 hover:bg-gray-50 dark:hover:bg-slate-800/50 transition-colors cursor-pointer border-l-2",
                      priorityBorder,
                      !n.isRead && "bg-purple-50/50 dark:bg-purple-900/10"
                    )}
                    onClick={() => !n.isRead && markAsRead(n.id)}
                  >
                    <div className="flex items-start gap-2.5">
                      <Icon className={cn("w-4 h-4 mt-0.5 shrink-0", iconColor)} />
                      <div className="flex-1 min-w-0">
                        <div className="flex items-center gap-1.5">
                          <p className={cn("text-sm font-medium truncate", n.isRead ? "text-gray-500 dark:text-slate-400" : "text-gray-900 dark:text-white")}>
                            {n.judul}
                          </p>
                          {!n.isRead && <span className="w-1.5 h-1.5 rounded-full bg-purple-500 shrink-0" />}
                        </div>
                        <p className="text-xs text-gray-400 dark:text-slate-500 line-clamp-2 mt-0.5">{n.pesan}</p>
                        {n.publishedAt && (
                          <p className="text-[10px] text-gray-300 dark:text-slate-600 mt-1">
                            {new Date(n.publishedAt).toLocaleDateString("id-ID", { day: "numeric", month: "short", year: "numeric" })}
                          </p>
                        )}
                      </div>
                    </div>
                  </div>
                );
              })
            )}
          </div>
        </div>,
        document.body
      )
    : null;

  return (
    <div className="relative">
      <button
        ref={buttonRef}
        onClick={() => setOpen(!open)}
        className="relative p-2 rounded-lg hover:bg-gray-100 dark:hover:bg-slate-800 transition-colors"
      >
        <Bell className="w-5 h-5 text-gray-500 dark:text-slate-400" />
        {unreadCount > 0 && (
          <span className="absolute -top-0.5 -right-0.5 w-4.5 h-4.5 min-w-[18px] px-1 bg-red-500 text-white text-[10px] font-bold rounded-full flex items-center justify-center animate-pulse">
            {unreadCount > 99 ? "99+" : unreadCount}
          </span>
        )}
      </button>
      {panel}
    </div>
  );
}
