// frontend/src/app/reset-password/page.tsx
"use client";


import { fetchApi } from '@/lib/fetch-api';
import { useState, useEffect, Suspense } from "react";
import { useSearchParams, useRouter } from "next/navigation";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Eye, EyeOff, CheckCircle, XCircle, Loader2 } from "lucide-react";
import Image from "next/image";
import { toast } from "sonner";

function ResetPasswordForm() {
  const searchParams = useSearchParams();
  const router = useRouter();
  const token = searchParams.get("token");

  const [password, setPassword] = useState("");
  const [confirmPassword, setConfirmPassword] = useState("");
  const [showPassword, setShowPassword] = useState(false);
  const [showConfirm, setShowConfirm] = useState(false);
  const [isLoading, setIsLoading] = useState(false);
  const [isValidating, setIsValidating] = useState(true);
  const [isValid, setIsValid] = useState(false);
  const [email, setEmail] = useState("");
  const [success, setSuccess] = useState(false);

  useEffect(() => {
    if (!token) {
      setIsValidating(false);
      return;
    }

    // Validate token
    fetchApi(`/api/auth/reset-password?token=${token}`)
      .then((res) => res.json())
      .then((data) => {
        if (data.success) {
          setIsValid(true);
          setEmail(data.data.email);
        }
      })
      .catch(() => {})
      .finally(() => setIsValidating(false));
  }, [token]);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();

    if (password !== confirmPassword) {
      toast.error("Password tidak cocok");
      return;
    }

    if (password.length < 6) {
      toast.error("Password minimal 6 karakter");
      return;
    }

    setIsLoading(true);
    try {
      const res = await fetchApi("/api/auth/reset-password", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ token, password }),
      });

      const data = await res.json();

      if (data.success) {
        setSuccess(true);
        toast.success("Password berhasil direset!");
      } else {
        toast.error(data.error || "Gagal mereset password");
      }
    } catch {
      toast.error("Terjadi kesalahan");
    } finally {
      setIsLoading(false);
    }
  };

  if (isValidating) {
    return (
      <div className="min-h-screen flex items-center justify-center bg-[#0221CD] p-4">
        <Card className="w-full max-w-md shadow-xl">
          <CardContent className="flex flex-col items-center justify-center py-12">
            <Loader2 className="w-8 h-8 animate-spin text-[#0221CD] mb-4" />
            <p className="text-muted-foreground">Memvalidasi token...</p>
          </CardContent>
        </Card>
      </div>
    );
  }

  if (!token || !isValid) {
    return (
      <div className="min-h-screen flex items-center justify-center bg-[#0221CD] p-4">
        <Card className="w-full max-w-md shadow-xl">
          <CardContent className="flex flex-col items-center justify-center py-12">
            <XCircle className="w-12 h-12 text-red-500 mb-4" />
            <h2 className="text-lg font-semibold mb-2">Token Tidak Valid</h2>
            <p className="text-sm text-muted-foreground text-center mb-6">
              Link reset password tidak valid atau sudah kadaluarsa. Silakan minta link baru.
            </p>
            <Button onClick={() => router.push("/admin-guru")} variant="outline">
              Kembali ke Login
            </Button>
          </CardContent>
        </Card>
      </div>
    );
  }

  if (success) {
    return (
      <div className="min-h-screen flex items-center justify-center bg-[#0221CD] p-4">
        <Card className="w-full max-w-md shadow-xl">
          <CardContent className="flex flex-col items-center justify-center py-12">
            <CheckCircle className="w-12 h-12 text-green-500 mb-4" />
            <h2 className="text-lg font-semibold mb-2">Password Berhasil Direset</h2>
            <p className="text-sm text-muted-foreground text-center mb-6">
              Password Anda telah berhasil diubah. Silakan login dengan password baru.
            </p>
            <Button onClick={() => router.push("/admin-guru")} className="text-white">
              Login Sekarang
            </Button>
          </CardContent>
        </Card>
      </div>
    );
  }

  return (
    <div className="min-h-screen flex items-center justify-center bg-[#0221CD] p-4">
      <Card className="w-full max-w-md shadow-xl">
        <CardHeader className="space-y-1 text-center">
          <div className="flex justify-center mb-4">
            <div className="relative w-16 h-16">
              <Image
                src="/icon/logo-no-bg-png-blue.png"
                alt="E-Learning Logo"
                fill
                className="object-contain"
                priority
              />
            </div>
          </div>
          <CardTitle className="text-xl font-bold">Reset Password</CardTitle>
          <CardDescription>
            Masukkan password baru untuk akun <strong>{email}</strong>
          </CardDescription>
        </CardHeader>
        <CardContent>
          <form onSubmit={handleSubmit} className="space-y-4">
            <div className="space-y-2">
              <Label htmlFor="password">Password Baru</Label>
              <div className="relative">
                <Input
                  id="password"
                  type={showPassword ? "text" : "password"}
                  placeholder="Minimal 6 karakter"
                  value={password}
                  onChange={(e) => setPassword(e.target.value)}
                  disabled={isLoading}
                  className="pr-10"
                  required
                  minLength={6}
                />
                <button
                  type="button"
                  onClick={() => setShowPassword(!showPassword)}
                  className="absolute right-3 top-1/2 -translate-y-1/2 text-gray-500 hover:text-gray-700"
                >
                  {showPassword ? <EyeOff className="w-4 h-4" /> : <Eye className="w-4 h-4" />}
                </button>
              </div>
            </div>

            <div className="space-y-2">
              <Label htmlFor="confirmPassword">Konfirmasi Password</Label>
              <div className="relative">
                <Input
                  id="confirmPassword"
                  type={showConfirm ? "text" : "password"}
                  placeholder="Ulangi password baru"
                  value={confirmPassword}
                  onChange={(e) => setConfirmPassword(e.target.value)}
                  disabled={isLoading}
                  className="pr-10"
                  required
                  minLength={6}
                />
                <button
                  type="button"
                  onClick={() => setShowConfirm(!showConfirm)}
                  className="absolute right-3 top-1/2 -translate-y-1/2 text-gray-500 hover:text-gray-700"
                >
                  {showConfirm ? <EyeOff className="w-4 h-4" /> : <Eye className="w-4 h-4" />}
                </button>
              </div>
              {confirmPassword && password !== confirmPassword && (
                <p className="text-xs text-red-500">Password tidak cocok</p>
              )}
            </div>

            <Button
              type="submit"
              className="w-full text-white"
              disabled={isLoading || password !== confirmPassword || password.length < 6}
            >
              {isLoading ? (
                <>
                  <Loader2 className="w-4 h-4 mr-2 animate-spin" />
                  Memproses...
                </>
              ) : (
                "Reset Password"
              )}
            </Button>

            <div className="text-center">
              <a href="/admin-guru" className="text-sm text-primary hover:underline">
                Kembali ke Login
              </a>
            </div>
          </form>
        </CardContent>
      </Card>
    </div>
  );
}

export default function ResetPasswordPage() {
  return (
    <Suspense
      fallback={
        <div className="min-h-screen flex items-center justify-center bg-[#0221CD] p-4">
          <Loader2 className="w-8 h-8 animate-spin text-white" />
        </div>
      }
    >
      <ResetPasswordForm />
    </Suspense>
  );
}

// frontend-nuxt/pages/reset-password.vue
<template>
  <div class="min-h-screen flex items-center justify-center p-8" style="background-color: #f8f9fb;">
    <div class="w-full max-w-md">
      <div class="flex items-center justify-center gap-3 mb-8">
        <div class="w-12 h-12 bg-orange-100 rounded-xl flex items-center justify-center">
          <Icon name="lucide:graduation-cap" class="w-7 h-7 text-orange-600" />
        </div>
        <span class="text-2xl font-bold text-gray-900">Nilai Online</span>
      </div>

      <div class="bg-white rounded-2xl p-8 card-shadow">
        <!-- Success State -->
        <div v-if="success" class="text-center">
          <div class="w-16 h-16 bg-green-100 rounded-full flex items-center justify-center mx-auto mb-4">
            <Icon name="lucide:check-circle" class="w-8 h-8 text-green-600" />
          </div>
          <h2 class="text-xl font-bold text-gray-900 mb-2">Password Berhasil Direset</h2>
          <p class="text-gray-500 text-sm mb-6">
            Password Anda telah berhasil diubah. Silakan login dengan password baru.
          </p>
          <NuxtLink to="/login-admin">
            <Button class="w-full" size="lg">
              Login Sekarang
            </Button>
          </NuxtLink>
        </div>

        <!-- Invalid Token -->
        <div v-else-if="invalidToken" class="text-center">
          <div class="w-16 h-16 bg-red-100 rounded-full flex items-center justify-center mx-auto mb-4">
            <Icon name="lucide:alert-circle" class="w-8 h-8 text-red-600" />
          </div>
          <h2 class="text-xl font-bold text-gray-900 mb-2">Link Tidak Valid</h2>
          <p class="text-gray-500 text-sm mb-6">
            Link reset password tidak valid atau sudah expired. Silakan request ulang.
          </p>
          <NuxtLink to="/login-admin/forgot-password">
            <Button class="w-full" size="lg" variant="outline">
              Request Ulang
            </Button>
          </NuxtLink>
        </div>

        <!-- Form State -->
        <div v-else>
          <div class="text-center mb-8">
            <div class="w-14 h-14 bg-orange-100 rounded-full flex items-center justify-center mx-auto mb-4">
              <Icon name="lucide:lock-keyhole" class="w-7 h-7 text-orange-600" />
            </div>
            <h2 class="text-xl font-bold text-gray-900">Reset Password</h2>
            <p class="text-gray-500 mt-2 text-sm">Masukkan password baru Anda</p>
          </div>

          <form @submit.prevent="handleSubmit" class="space-y-5">
            <div class="space-y-2">
              <label class="text-sm font-medium text-gray-700">Password Baru</label>
              <div class="relative">
                <Input
                  v-model="password"
                  :type="showPassword ? 'text' : 'password'"
                  placeholder="Minimal 6 karakter"
                  icon="lucide:lock"
                  size="lg"
                  :disabled="isLoading"
                />
                <button
                  type="button"
                  @click="showPassword = !showPassword"
                  class="absolute right-4 top-1/2 -translate-y-1/2 text-gray-400 hover:text-gray-600"
                >
                  <Icon :name="showPassword ? 'lucide:eye-off' : 'lucide:eye'" class="w-4 h-4" />
                </button>
              </div>
            </div>

            <div class="space-y-2">
              <label class="text-sm font-medium text-gray-700">Konfirmasi Password</label>
              <div class="relative">
                <Input
                  v-model="confirmPassword"
                  :type="showConfirm ? 'text' : 'password'"
                  placeholder="Ulangi password baru"
                  icon="lucide:lock"
                  size="lg"
                  :disabled="isLoading"
                />
                <button
                  type="button"
                  @click="showConfirm = !showConfirm"
                  class="absolute right-4 top-1/2 -translate-y-1/2 text-gray-400 hover:text-gray-600"
                >
                  <Icon :name="showConfirm ? 'lucide:eye-off' : 'lucide:eye'" class="w-4 h-4" />
                </button>
              </div>
            </div>

            <Button
              type="submit"
              class="w-full"
              size="lg"
              :loading="isLoading"
            >
              Reset Password
            </Button>
          </form>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { toast } from 'vue-sonner'

definePageMeta({
  layout: 'default',
})

useHead({
  title: 'Reset Password',
})

const route = useRoute()
const token = computed(() => route.query.token as string || '')

const password = ref('')
const confirmPassword = ref('')
const showPassword = ref(false)
const showConfirm = ref(false)
const isLoading = ref(false)
const success = ref(false)
const invalidToken = ref(false)

onMounted(() => {
  if (!token.value) {
    invalidToken.value = true
  }
})

const handleSubmit = async () => {
  if (!password.value || !confirmPassword.value) {
    toast.error('Isi semua field')
    return
  }

  if (password.value.length < 6) {
    toast.error('Password minimal 6 karakter')
    return
  }

  if (password.value !== confirmPassword.value) {
    toast.error('Password tidak cocok')
    return
  }

  isLoading.value = true
  try {
    const response = await fetchApi('/api/auth/reset-password', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ token: token.value, password: password.value }),
    })

    const data = await response.json()

    if (data.success) {
      success.value = true
    } else {
      if (data.error?.includes('expired') || data.error?.includes('tidak valid')) {
        invalidToken.value = true
      } else {
        toast.error(data.error || 'Terjadi kesalahan')
      }
    }
  } catch (error) {
    console.error('Reset password error:', error)
    toast.error('Terjadi kesalahan')
  } finally {
    isLoading.value = false
  }
}
</script>
