// frontend-nuxt/pages/admin/ujian/index.vue
<template>
  <div class="space-y-6">
    <!-- Token Ujian Card -->
    <div :class="[
      'rounded-2xl card-shadow p-5 transition-all',
      tokenData.isActive ? 'bg-gradient-to-r from-orange-500 to-orange-600 text-white' : 'bg-white'
    ]">
      <div class="flex flex-col sm:flex-row sm:items-center gap-4">
        <div class="flex items-center gap-3 flex-1 min-w-0">
          <div :class="[
            'w-10 h-10 rounded-xl flex items-center justify-center flex-shrink-0',
            tokenData.isActive ? 'bg-white/20' : 'bg-orange-100'
          ]">
            <Icon name="lucide:key-round" :class="['w-5 h-5', tokenData.isActive ? 'text-white' : 'text-orange-600']" />
          </div>
          <div class="min-w-0">
            <p :class="['text-sm font-medium', tokenData.isActive ? 'text-white/80' : 'text-gray-500']">Token Akses Ujian</p>
            <div v-if="tokenData.isActive && tokenData.currentToken" class="flex items-center gap-2 mt-0.5">
              <p class="text-2xl font-mono font-bold tracking-[0.3em]">{{ tokenData.currentToken }}</p>
              <button @click="copyToken" class="p-1 hover:bg-white/20 rounded transition-colors">
                <Icon name="lucide:copy" class="w-4 h-4" />
              </button>
            </div>
            <p v-else :class="['text-sm', tokenData.isActive ? 'text-white/70' : 'text-gray-400']">Belum ada token aktif</p>
          </div>
        </div>

        <!-- Countdown Timer -->
        <div v-if="tokenData.isActive && tokenCountdown > 0" class="flex items-center gap-3 flex-shrink-0">
          <div class="text-center">
            <p :class="['text-2xl font-bold font-mono', tokenData.isActive ? 'text-white' : 'text-gray-900']">{{ formatCountdown }}</p>
            <p :class="['text-xs', tokenData.isActive ? 'text-white/70' : 'text-gray-400']">Sisa waktu</p>
          </div>
        </div>

        <!-- Actions -->
        <div class="flex items-center gap-2 flex-shrink-0">
          <template v-if="tokenData.isActive">
            <Button
              size="sm"
              variant="outline"
              class="!bg-white/20 !border-white/30 !text-white hover:!bg-white/30"
              @click="deactivateToken"
              :loading="isDeactivatingToken"
            >
              <Icon name="lucide:x" class="w-4 h-4 mr-1" />
              Nonaktifkan
            </Button>
          </template>
          <template v-else>
            <Button
              size="sm"
              @click="generateToken"
              :loading="isGeneratingToken"
            >
              <Icon name="lucide:zap" class="w-4 h-4 mr-1" />
              Aktifkan Token (5 menit)
            </Button>
          </template>
        </div>
      </div>
    </div>

    <!-- Stats Cards -->
    <div class="grid grid-cols-2 lg:grid-cols-4 gap-4">
      <div class="bg-white rounded-2xl card-shadow p-4">
        <div class="flex items-center gap-3">
          <div class="w-9 h-9 rounded-lg bg-blue-100 flex items-center justify-center">
            <Icon name="lucide:file-text" class="w-4 h-4 text-blue-600" />
          </div>
          <div>
            <p class="text-xl font-bold text-gray-900">{{ stats.total }}</p>
            <p class="text-xs text-gray-500">Total Ujian</p>
          </div>
        </div>
      </div>
      <div class="bg-white rounded-2xl card-shadow p-4">
        <div class="flex items-center gap-3">
          <div class="w-9 h-9 rounded-lg bg-green-100 flex items-center justify-center">
            <Icon name="lucide:check-circle" class="w-4 h-4 text-green-600" />
          </div>
          <div>
            <p class="text-xl font-bold text-gray-900">{{ stats.aktif }}</p>
            <p class="text-xs text-gray-500">Aktif</p>
          </div>
        </div>
      </div>
      <div class="bg-white rounded-2xl card-shadow p-4">
        <div class="flex items-center gap-3">
          <div class="w-9 h-9 rounded-lg bg-yellow-100 flex items-center justify-center">
            <Icon name="lucide:clock" class="w-4 h-4 text-yellow-600" />
          </div>
          <div>
            <p class="text-xl font-bold text-gray-900">{{ stats.berlangsung }}</p>
            <p class="text-xs text-gray-500">Berlangsung</p>
          </div>
        </div>
      </div>
      <div class="bg-white rounded-2xl card-shadow p-4">
        <div class="flex items-center gap-3">
          <div class="w-9 h-9 rounded-lg bg-gray-100 flex items-center justify-center">
            <Icon name="lucide:archive" class="w-4 h-4 text-gray-600" />
          </div>
          <div>
            <p class="text-xl font-bold text-gray-900">{{ stats.selesai }}</p>
            <p class="text-xs text-gray-500">Selesai</p>
          </div>
        </div>
      </div>
    </div>

    <!-- Filter & Search -->
    <div class="bg-white rounded-2xl card-shadow p-4">
      <div class="flex flex-col sm:flex-row gap-3">
        <div class="flex-1">
          <Input v-model="searchQuery" placeholder="Cari ujian..." icon="lucide:search" />
        </div>
        <select v-model="filterStatus" class="px-4 py-2.5 border border-gray-200 rounded-xl text-sm focus:outline-none focus:ring-2 focus:ring-orange-500/20 focus:border-orange-500">
          <option value="all">Semua Status</option>
          <option value="draft">Draft</option>
          <option value="active">Aktif</option>
          <option value="selesai">Selesai</option>
        </select>
      </div>
    </div>

    <!-- Ujian List -->
    <div class="space-y-3">
      <div v-if="filteredUjian.length === 0" class="bg-white rounded-2xl card-shadow p-12 text-center">
        <Icon name="lucide:inbox" class="w-12 h-12 text-gray-300 mx-auto mb-3" />
        <p class="text-gray-500">Tidak ada ujian ditemukan</p>
      </div>

      <div 
        v-for="ujian in filteredUjian" 
        :key="ujian.id" 
        class="bg-white rounded-2xl card-shadow p-5 hover:shadow-md transition-shadow"
      >
        <div class="flex flex-col lg:flex-row lg:items-center gap-4">
          <!-- Info -->
          <div class="flex-1 min-w-0">
            <div class="flex items-center gap-2 mb-1">
              <h3 class="font-semibold text-gray-900 truncate">{{ ujian.judul }}</h3>
              <span :class="getStatusClass(ujian)">{{ getStatusLabel(ujian) }}</span>
            </div>
            <div class="flex flex-wrap items-center gap-x-4 gap-y-1 text-sm text-gray-500">
              <span class="flex items-center gap-1">
                <Icon name="lucide:book-open" class="w-3.5 h-3.5" />
                {{ ujian.mapel || '-' }}
              </span>
              <span class="flex items-center gap-1">
                <Icon name="lucide:user" class="w-3.5 h-3.5" />
                {{ ujian.guru || '-' }}
              </span>
              <span class="flex items-center gap-1">
                <Icon name="lucide:users" class="w-3.5 h-3.5" />
                {{ ujian.kelas?.join(', ') || '-' }}
              </span>
              <span class="flex items-center gap-1">
                <Icon name="lucide:calendar" class="w-3.5 h-3.5" />
                {{ formatDate(ujian.startUjian) }} - {{ formatDate(ujian.endUjian) }}
              </span>
            </div>
          </div>

          <!-- Stats -->
          <div class="flex items-center gap-4 text-sm">
            <div class="text-center px-3">
              <p class="font-bold text-gray-900">{{ ujian.soalCount }}</p>
              <p class="text-xs text-gray-500">Soal</p>
            </div>
            <div class="text-center px-3 border-l border-gray-200">
              <p class="font-bold text-gray-900">{{ ujian.submissionCount }}/{{ ujian.targetSiswa }}</p>
              <p class="text-xs text-gray-500">Mengerjakan</p>
            </div>
          </div>

          <!-- Actions -->
          <div class="flex items-center gap-2">
            <Button 
              v-if="isUjianEnded(ujian)"
              size="sm" 
              variant="outline"
              icon="lucide:refresh-cw"
              @click="openSusulanModal(ujian)"
            >
              <span class="hidden sm:inline">Susulan</span>
            </Button>
          </div>
        </div>
      </div>
    </div>

    <!-- Susulan Modal -->
    <Modal
      v-model="showSusulanModal"
      :title="`Ujian Susulan - ${selectedUjian?.judul || ''}`"
      description="Berikan akses ujian susulan untuk siswa yang belum mengerjakan"
      size="lg"
    >
      <div class="space-y-4">
        <!-- Duration -->
        <div class="space-y-2">
          <Label>Durasi Susulan (menit) *</Label>
          <Input v-model.number="susulanDurasi" type="number" placeholder="60" icon="lucide:clock" />
          <p class="text-xs text-gray-400">Waktu yang diberikan untuk mengerjakan ujian susulan</p>
        </div>

        <!-- Siswa List -->
        <div class="space-y-2">
          <div class="flex items-center justify-between">
            <Label>Pilih Siswa</Label>
            <button 
              @click="selectAllBelumUjian" 
              class="text-xs text-orange-500 hover:text-orange-600 font-medium"
            >
              Pilih Semua Belum Ujian
            </button>
          </div>
          
          <div class="border border-gray-200 rounded-xl max-h-64 overflow-y-auto">
            <div v-if="susulanSiswaList.length === 0" class="p-4 text-center text-sm text-gray-500">
              Memuat data siswa...
            </div>
            <div 
              v-for="s in susulanSiswaList" 
              :key="s.id"
              :class="[
                'flex items-center gap-3 px-4 py-3 border-b border-gray-100 last:border-0',
                s.submittedAt ? 'opacity-50' : ''
              ]"
            >
              <input
                type="checkbox"
                :checked="selectedSiswaIds.includes(s.id)"
                :disabled="!!s.submittedAt"
                @change="toggleSiswa(s.id)"
                class="w-4 h-4 text-orange-500 rounded focus:ring-orange-500"
              />
              <div class="flex-1 min-w-0">
                <p class="text-sm font-medium text-gray-900 truncate">{{ s.nama }}</p>
                <p class="text-xs text-gray-500">{{ s.nis }} · {{ s.kelas }}</p>
              </div>
              <div class="text-right">
                <span v-if="s.submittedAt" class="text-xs px-2 py-0.5 rounded-full bg-green-100 text-green-700">Sudah Ujian</span>
                <span v-else-if="s.hasSusulan" class="text-xs px-2 py-0.5 rounded-full bg-yellow-100 text-yellow-700">Susulan Aktif</span>
                <span v-else class="text-xs px-2 py-0.5 rounded-full bg-red-100 text-red-700">Belum Ujian</span>
              </div>
            </div>
          </div>
          <p v-if="selectedSiswaIds.length > 0" class="text-xs text-orange-600">
            {{ selectedSiswaIds.length }} siswa dipilih
          </p>
        </div>
      </div>

      <template #footer>
        <div class="flex justify-end gap-3">
          <Button variant="outline" @click="showSusulanModal = false">Batal</Button>
          <Button 
            :loading="isGrantingSusulan" 
            :disabled="selectedSiswaIds.length === 0"
            @click="grantSusulan"
          >
            <Icon name="lucide:send" class="w-4 h-4 mr-1" />
            Berikan Akses Susulan
          </Button>
        </div>
      </template>
    </Modal>
  </div>
</template>

<script setup lang="ts">
import { toast } from 'vue-sonner'

definePageMeta({
  layout: 'admin',
})

useHead({
  title: 'Manajemen Ujian',
})

const searchQuery = ref('')
const filterStatus = ref('all')
const ujianList = ref<any[]>([])
const showSusulanModal = ref(false)
const selectedUjian = ref<any>(null)
const susulanSiswaList = ref<any[]>([])
const selectedSiswaIds = ref<string[]>([])
const susulanDurasi = ref(60)
const isGrantingSusulan = ref(false)

// Token state
const tokenData = ref<any>({ isActive: false, currentToken: null })
const tokenCountdown = ref(0)
const isGeneratingToken = ref(false)
const isDeactivatingToken = ref(false)
let countdownInterval: ReturnType<typeof setInterval> | null = null

const formatCountdown = computed(() => {
  const mins = Math.floor(tokenCountdown.value / 60)
  const secs = tokenCountdown.value % 60
  return `${String(mins).padStart(2, '0')}:${String(secs).padStart(2, '0')}`
})

const startCountdown = (seconds: number) => {
  if (countdownInterval) clearInterval(countdownInterval)
  tokenCountdown.value = seconds

  if (seconds <= 0) {
    tokenData.value.isActive = false
    tokenData.value.currentToken = null
    return
  }

  countdownInterval = setInterval(() => {
    tokenCountdown.value--
    if (tokenCountdown.value <= 0) {
      if (countdownInterval) clearInterval(countdownInterval)
      tokenData.value.isActive = false
      tokenData.value.currentToken = null
    }
  }, 1000)
}

const fetchTokenStatus = async () => {
  try {
    const response = await fetchApi('/api/admin/ujian/token')
    const data = await response.json()
    console.log('[TOKEN] fetchTokenStatus response:', JSON.stringify(data))
    if (data.success && data.data) {
      const isActive = data.data.isActive === true
      const remaining = typeof data.data.remainingSeconds === 'string' 
        ? parseInt(data.data.remainingSeconds) 
        : (data.data.remainingSeconds || 0)
      console.log('[TOKEN] parsed:', { isActive, remaining, currentToken: data.data.currentToken })
      tokenData.value = {
        isActive,
        currentToken: data.data.currentToken || null,
      }
      if (isActive && remaining > 0) {
        startCountdown(remaining)
      }
    }
  } catch (err) {
    console.error('Error fetching token:', err)
  }
}

const generateToken = async () => {
  isGeneratingToken.value = true
  try {
    const response = await fetchApi('/api/admin/ujian/token/generate', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ duration: 5 }),
    })
    const data = await response.json()
    if (data.success && data.data) {
      tokenData.value = {
        isActive: true,
        currentToken: data.data.currentToken,
      }
      startCountdown(data.data.remainingSeconds)
      toast.success('Token berhasil diaktifkan (5 menit)')
    } else {
      toast.error(data.error || 'Gagal mengaktifkan token')
    }
  } catch (err) {
    toast.error('Terjadi kesalahan')
  } finally {
    isGeneratingToken.value = false
  }
}

const deactivateToken = async () => {
  isDeactivatingToken.value = true
  try {
    const response = await fetchApi('/api/admin/ujian/token/deactivate', {
      method: 'POST',
    })
    const data = await response.json()
    if (data.success) {
      if (countdownInterval) clearInterval(countdownInterval)
      tokenData.value = { isActive: false, currentToken: null, tokenExpiresAt: null }
      tokenCountdown.value = 0
      toast.success('Token berhasil dinonaktifkan')
    } else {
      toast.error(data.error || 'Gagal menonaktifkan token')
    }
  } catch (err) {
    toast.error('Terjadi kesalahan')
  } finally {
    isDeactivatingToken.value = false
  }
}

const copyToken = () => {
  if (tokenData.value.currentToken) {
    navigator.clipboard.writeText(tokenData.value.currentToken)
    toast.success('Token disalin ke clipboard')
  }
}

const stats = computed(() => {
  const now = new Date()
  const total = ujianList.value.length
  const aktif = ujianList.value.filter(u => u.status === 'active' || u.status === 'aktif').length
  const berlangsung = ujianList.value.filter(u => {
    const start = new Date(u.startUjian)
    const end = new Date(u.endUjian)
    return now >= start && now <= end && (u.status === 'active' || u.status === 'aktif')
  }).length
  const selesai = ujianList.value.filter(u => new Date(u.endUjian) < now).length
  return { total, aktif, berlangsung, selesai }
})

const filteredUjian = computed(() => {
  let list = ujianList.value
  if (searchQuery.value) {
    const q = searchQuery.value.toLowerCase()
    list = list.filter(u => 
      u.judul?.toLowerCase().includes(q) || 
      u.mapel?.toLowerCase().includes(q) || 
      u.guru?.toLowerCase().includes(q)
    )
  }
  if (filterStatus.value !== 'all') {
    const now = new Date()
    if (filterStatus.value === 'selesai') {
      list = list.filter(u => new Date(u.endUjian) < now)
    } else if (filterStatus.value === 'active') {
      list = list.filter(u => u.status === 'active' || u.status === 'aktif')
    } else {
      list = list.filter(u => u.status === filterStatus.value)
    }
  }
  return list
})

const formatDate = (date: string) => {
  if (!date) return '-'
  return new Date(date).toLocaleDateString('id-ID', { day: 'numeric', month: 'short', year: 'numeric', hour: '2-digit', minute: '2-digit' })
}

const isUjianEnded = (ujian: any) => {
  return new Date(ujian.endUjian) < new Date()
}

const getStatusLabel = (ujian: any) => {
  const now = new Date()
  const start = new Date(ujian.startUjian)
  const end = new Date(ujian.endUjian)
  if (ujian.status === 'draft') return 'Draft'
  if (now < start) return 'Belum Mulai'
  if (now >= start && now <= end) return 'Berlangsung'
  if (now > end) return 'Selesai'
  return ujian.status
}

const getStatusClass = (ujian: any) => {
  const now = new Date()
  const start = new Date(ujian.startUjian)
  const end = new Date(ujian.endUjian)
  const base = 'text-xs px-2 py-0.5 rounded-full font-medium'
  if (ujian.status === 'draft') return `${base} bg-gray-100 text-gray-600`
  if (now < start) return `${base} bg-blue-100 text-blue-700`
  if (now >= start && now <= end) return `${base} bg-green-100 text-green-700`
  return `${base} bg-gray-100 text-gray-600`
}

const openSusulanModal = async (ujian: any) => {
  selectedUjian.value = ujian
  selectedSiswaIds.value = []
  susulanDurasi.value = 60
  showSusulanModal.value = true
  
  try {
    const response = await fetchApi(`/api/admin/ujian/${ujian.id}/siswa`)
    const data = await response.json()
    if (data.success) {
      susulanSiswaList.value = data.data.siswa || []
    }
  } catch (err) {
    console.error('Error fetching siswa:', err)
  }
}

const toggleSiswa = (siswaId: string) => {
  const idx = selectedSiswaIds.value.indexOf(siswaId)
  if (idx === -1) {
    selectedSiswaIds.value.push(siswaId)
  } else {
    selectedSiswaIds.value.splice(idx, 1)
  }
}

const selectAllBelumUjian = () => {
  selectedSiswaIds.value = susulanSiswaList.value
    .filter(s => !s.submittedAt)
    .map(s => s.id)
}

const grantSusulan = async () => {
  if (!selectedUjian.value || selectedSiswaIds.value.length === 0) return
  
  isGrantingSusulan.value = true
  try {
    const response = await fetchApi(`/api/admin/ujian/${selectedUjian.value.id}/susulan`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        siswaIds: selectedSiswaIds.value,
        durasiMenit: susulanDurasi.value,
      }),
    })
    const data = await response.json()
    if (data.success) {
      toast.success(data.message || 'Ujian susulan berhasil diberikan')
      showSusulanModal.value = false
      await fetchUjian()
    } else {
      toast.error(data.error || 'Gagal memberikan ujian susulan')
    }
  } catch (err) {
    toast.error('Terjadi kesalahan')
  } finally {
    isGrantingSusulan.value = false
  }
}

const fetchUjian = async () => {
  try {
    const response = await fetchApi('/api/admin/ujian')
    const data = await response.json()
    if (data.success) {
      ujianList.value = data.data || []
    }
  } catch (err) {
    console.error('Error fetching ujian:', err)
  }
}

onMounted(() => {
  fetchUjian()
  fetchTokenStatus()
})

onUnmounted(() => {
  if (countdownInterval) clearInterval(countdownInterval)
})
</script>

// frontend/src/app/(main)/guru/ujian/page.tsx
"use client";


import { fetchApi } from '@/lib/fetch-api';
import { fetcherWithAuth } from '@/lib/swr-config';
import { useState } from "react";
import useSWR from "swr";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { StatCard } from "@/components/ui/stat-card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { LoadingSpinner } from "@/components/ui/loading-spinner";
import { useAuth } from "@/hooks/useAuth";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
} from "@/components/ui/alert-dialog";
import { Badge } from "@/components/ui/badge";
import { Plus, Eye, CheckCircle, Exam, CheckCircle as CheckCirclePhosphor, File, XCircle, PencilSimple, MagnifyingGlass, ListChecks, Gear } from "@phosphor-icons/react";
import { Calendar as CalendarIcon, Trash2 } from "lucide-react";
import { toast } from "sonner";
import { useRouter } from "next/navigation";
import { format } from "date-fns";
import { id } from "date-fns/locale";
import { cn } from "@/lib/utils";

interface Ujian {
  id: string;
  judul: string;
  deskripsi: string;
  kelas: string | string[];
  mapel: string;
  startUjian: string | Date;
  endUjian: string | Date;
  jumlahSoal: number;
  status: "draft" | "aktif" | "selesai";
  jumlahPeserta?: number;
  sudahMengerjakan?: number;
}


export default function UjianGuruPage() {
  const router = useRouter();
  const { isLoading: authLoading } = useAuth();
  const [filterStatus, setFilterStatus] = useState<string>("all");
  const [showDeleteModal, setShowDeleteModal] = useState(false);
  const [showPublishModal, setShowPublishModal] = useState(false);
  const [selectedUjian, setSelectedUjian] = useState<{ id: string; judul: string } | null>(null);
  const [searchQuery, setSearchQuery] = useState<string>("");

  const { data, error, isLoading, mutate } = useSWR(
    `/api/guru/ujian?status=${filterStatus}`,
    fetcherWithAuth
  );

  if (authLoading || isLoading) {
    return <LoadingSpinner />;
  }

  if (error) {
    return (
      <div className="flex items-center justify-center h-96">
        <p className="text-red-600">Gagal memuat data ujian</p>
      </div>
    );
  }

  const ujian = data?.data?.ujian || [];

  // Filter ujian berdasarkan search query
  const filteredUjian = ujian.filter((u: any) => {
    const query = searchQuery.toLowerCase();
    return (
      u.judul?.toLowerCase().includes(query) ||
      u.mapel?.toLowerCase().includes(query) ||
      (Array.isArray(u.kelas) ? u.kelas.some((k: string) => k.toLowerCase().includes(query)) : u.kelas?.toLowerCase().includes(query))
    );
  });

  const handleDelete = async () => {
    if (!selectedUjian) return;
    
    try {
      const response = await fetchApi(`/api/guru/ujian?id=${selectedUjian.id}`, {
        method: 'DELETE',
      });

      const result = await response.json();

      if (response.ok && result.success) {
        await mutate();
        toast.success("Ujian berhasil dihapus");
        setShowDeleteModal(false);
        setSelectedUjian(null);
      } else {
        toast.error(result.error || "Gagal menghapus ujian");
      }
    } catch (error) {
      console.error('Error deleting ujian:', error);
      toast.error("Terjadi kesalahan saat menghapus ujian");
    }
  };

  const handlePublish = async () => {
    if (!selectedUjian) return;
    
    try {
      const response = await fetchApi(`/api/guru/ujian/${selectedUjian.id}`, {
        method: 'PUT',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ status: 'aktif' }),
      });

      const result = await response.json();

      if (response.ok && result.success) {
        await mutate();
        toast.success("Ujian berhasil dipublikasikan");
        setShowPublishModal(false);
        setSelectedUjian(null);
      } else {
        toast.error(result.error || "Gagal mempublikasikan ujian");
      }
    } catch (error) {
      console.error('Error publishing ujian:', error);
      toast.error("Terjadi kesalahan saat mempublikasikan ujian");
    }
  };

  const openDeleteModal = (id: string, judul: string) => {
    setSelectedUjian({ id, judul });
    setShowDeleteModal(true);
  };

  const openPublishModal = (id: string, judul: string) => {
    setSelectedUjian({ id, judul });
    setShowPublishModal(true);
  };

  const stats = {
    total: ujian.length,
    aktif: ujian.filter((u: any) => u.status === "aktif").length,
    draft: ujian.filter((u: any) => u.status === "draft").length,
    selesai: ujian.filter((u: any) => u.status === "selesai").length,
  };

  return (
    <div className="space-y-6">
      {/* Header Card with Blue Background */}
      <Card className="bg-gradient-to-br from-[#0221CD] to-[#0221CD]/80 border-0 shadow-lg">
        <CardContent className="p-6 md:p-8">
          <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-6">
            <div className="flex-1">
              <div className="flex items-center gap-3 mb-2">
                <Exam className="w-8 h-8 text-white" weight="duotone" />
                <h1 className="text-3xl md:text-4xl font-bold text-white tracking-tight">Manajemen Ujian</h1>
              </div>
              <p className="text-blue-50 text-base md:text-lg">Kelola dan pantau ujian untuk siswa Anda</p>
            </div>
            <Button 
              onClick={() => router.push("/guru/ujian/create")} 
              size="lg" 
              className="bg-white text-[#165DFB] hover:bg-blue-50 shadow-md hover:shadow-lg transition-all whitespace-nowrap"
            >
              <Plus className="w-5 h-5 mr-2" weight="bold" />
              Buat Ujian Baru
            </Button>
          </div>

          {/* Statistics Cards */}
          <div className="grid gap-4 grid-cols-2 md:grid-cols-4 mt-8">
            <div className="bg-white/10 backdrop-blur-sm rounded-lg p-4 border border-white/20">
              <div className="flex items-center gap-3 mb-2">
                <div className="p-2 bg-white/20 rounded-lg">
                  <Exam className="w-5 h-5 text-white" weight="duotone" />
                </div>
                <p className="text-blue-100 text-sm font-medium">Total Ujian</p>
              </div>
              <p className="text-white text-3xl font-bold">{stats.total}</p>
            </div>
            <div className="bg-white/10 backdrop-blur-sm rounded-lg p-4 border border-white/20">
              <div className="flex items-center gap-3 mb-2">
                <div className="p-2 bg-white/20 rounded-lg">
                  <CheckCirclePhosphor className="w-5 h-5 text-white" weight="duotone" />
                </div>
                <p className="text-blue-100 text-sm font-medium">Aktif</p>
              </div>
              <p className="text-white text-3xl font-bold">{stats.aktif}</p>
            </div>
            <div className="bg-white/10 backdrop-blur-sm rounded-lg p-4 border border-white/20">
              <div className="flex items-center gap-3 mb-2">
                <div className="p-2 bg-white/20 rounded-lg">
                  <File className="w-5 h-5 text-white" weight="duotone" />
                </div>
                <p className="text-blue-100 text-sm font-medium">Draft</p>
              </div>
              <p className="text-white text-3xl font-bold">{stats.draft}</p>
            </div>
            <div className="bg-white/10 backdrop-blur-sm rounded-lg p-4 border border-white/20">
              <div className="flex items-center gap-3 mb-2">
                <div className="p-2 bg-white/20 rounded-lg">
                  <XCircle className="w-5 h-5 text-white" weight="duotone" />
                </div>
                <p className="text-blue-100 text-sm font-medium">Selesai</p>
              </div>
              <p className="text-white text-3xl font-bold">{stats.selesai}</p>
            </div>
          </div>
        </CardContent>
      </Card>

      {/* Filters and Search */}
      <Card className="shadow-lg">
        <CardHeader>
          <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
            <div>
              <CardTitle>Daftar Ujian</CardTitle>
              <CardDescription className="mt-1">
                {filteredUjian.length} dari {ujian.length} ujian
              </CardDescription>
            </div>
            <div className="flex flex-col sm:flex-row gap-2">
              <div className="relative">
                <MagnifyingGlass className="absolute left-3 top-1/2 transform -translate-y-1/2 w-4 h-4 text-muted-foreground" />
                <Input
                  placeholder="Cari ujian..."
                  value={searchQuery}
                  onChange={(e) => setSearchQuery(e.target.value)}
                  className="pl-9 w-full sm:w-[250px]"
                />
              </div>
              <Select value={filterStatus} onValueChange={setFilterStatus}>
                <SelectTrigger className="w-full sm:w-[150px]">
                  <SelectValue placeholder="Filter Status" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="all">Semua Status</SelectItem>
                  <SelectItem value="draft">Draft</SelectItem>
                  <SelectItem value="aktif">Aktif</SelectItem>
                  <SelectItem value="selesai">Selesai</SelectItem>
                </SelectContent>
              </Select>
            </div>
          </div>
        </CardHeader>
        <CardContent>
          {filteredUjian.length === 0 ? (
            <div className="flex flex-col items-center justify-center py-16 text-center">
              <Exam className="w-16 h-16 text-muted-foreground mb-4" weight="duotone" />
              <h3 className="text-lg font-semibold mb-2">
                {searchQuery || filterStatus !== "all" ? "Tidak ada ujian yang ditemukan" : "Belum ada ujian"}
              </h3>
              <p className="text-sm text-muted-foreground mb-6 max-w-sm">
                {searchQuery || filterStatus !== "all" 
                  ? "Coba ubah filter atau kata kunci pencarian Anda"
                  : "Mulai dengan membuat ujian baru untuk siswa Anda"}
              </p>
              {!searchQuery && filterStatus === "all" && (
                <Button onClick={() => router.push("/guru/ujian/create")}>
                  <Plus className="w-4 h-4 mr-2" weight="bold" />
                  Buat Ujian Pertama
                </Button>
              )}
            </div>
          ) : (
            <div className="grid gap-4 sm:grid-cols-1 md:grid-cols-2 xl:grid-cols-3 2xl:grid-cols-4">
              {filteredUjian.map((u: any) => (
                <Card 
                  key={u.id} 
                  className="shadow-lg hover:shadow-xl transition-all duration-200 cursor-pointer group border hover:border-primary/20 overflow-hidden"
                  onClick={() => router.push(`/guru/ujian/${u.id}`)}
                >
                  <CardHeader className="pb-3 space-y-0">
                    <div className="flex items-start justify-between gap-3">
                      <div className="flex-1 min-w-0 space-y-2">
                        <CardTitle className="text-base sm:text-lg font-semibold line-clamp-2 leading-tight group-hover:text-primary transition-colors">
                          {u.judul}
                        </CardTitle>
                        <Badge variant="outline" className="text-[10px] sm:text-xs px-2 py-0.5 w-fit">
                          {u.mapel}
                        </Badge>
                      </div>
                      <DropdownMenu>
                        <DropdownMenuTrigger asChild onClick={(e) => e.stopPropagation()}>
                          <Button variant="ghost" size="icon" className="h-8 w-8 flex-shrink-0">
                            <Gear className="w-4 h-4" weight="duotone" />
                          </Button>
                        </DropdownMenuTrigger>
                        <DropdownMenuContent align="end" onClick={(e) => e.stopPropagation()}>
                          <DropdownMenuItem onClick={() => router.push(`/guru/ujian/${u.id}`)}>
                            <Eye className="w-4 h-4 mr-2" />
                            Lihat Detail
                          </DropdownMenuItem>
                          <DropdownMenuItem onClick={() => router.push(`/guru/ujian/${u.id}/edit`)}>
                            <PencilSimple className="w-4 h-4 mr-2" />
                            Edit Ujian
                          </DropdownMenuItem>
                          <DropdownMenuItem onClick={() => router.push(`/guru/ujian/${u.id}/nilai`)}>
                            <CheckCircle className="w-4 h-4 mr-2" />
                            Lihat Nilai
                          </DropdownMenuItem>
                          {u.status === "draft" && (
                            <DropdownMenuItem onClick={() => openPublishModal(u.id, u.judul)}>
                              <CheckCirclePhosphor className="w-4 h-4 mr-2" />
                              Publikasikan
                            </DropdownMenuItem>
                          )}
                          <DropdownMenuItem 
                            onClick={() => openDeleteModal(u.id, u.judul)}
                            className="text-red-600 focus:text-red-600"
                          >
                            <Trash2 className="w-4 h-4 mr-2" />
                            Hapus
                          </DropdownMenuItem>
                        </DropdownMenuContent>
                      </DropdownMenu>
                    </div>
                  </CardHeader>
                  <CardContent className="space-y-3 pt-0" onClick={(e) => e.stopPropagation()}>
                    {/* Kelas + Soal count row */}
                    <div className="flex items-center justify-between gap-2">
                      <div className="flex flex-wrap gap-1.5 flex-1 min-w-0">
                        {Array.isArray(u.kelas) ? (
                          u.kelas.slice(0, 3).map((kelas: string, idx: number) => (
                            <Badge key={idx} variant="secondary" className="text-[10px] sm:text-xs px-2 py-0.5">
                              {kelas}
                            </Badge>
                          ))
                        ) : (
                          <Badge variant="secondary" className="text-[10px] sm:text-xs px-2 py-0.5">
                            {u.kelas}
                          </Badge>
                        )}
                        {Array.isArray(u.kelas) && u.kelas.length > 3 && (
                          <Badge variant="outline" className="text-[10px] sm:text-xs px-2 py-0.5">
                            +{u.kelas.length - 3}
                          </Badge>
                        )}
                      </div>
                      <div className="flex items-center gap-1 text-muted-foreground flex-shrink-0">
                        <ListChecks className="w-3.5 h-3.5" />
                        <span className="text-xs font-medium">{u.totalSoal || 0} soal</span>
                      </div>
                    </div>

                    {/* Schedule compact */}
                    <div className="flex items-center gap-1.5 text-muted-foreground text-xs">
                      <CalendarIcon className="w-3.5 h-3.5 flex-shrink-0" />
                      <span className="truncate">
                        {format(new Date(u.startUjian), "dd MMM yyyy HH:mm", { locale: id })}
                        {" — "}
                        {format(new Date(u.endUjian), "dd MMM yyyy HH:mm", { locale: id })}
                      </span>
                      <span className="flex-shrink-0 text-muted-foreground/70">
                        ({Math.round((new Date(u.endUjian).getTime() - new Date(u.startUjian).getTime()) / 60000)}m)
                      </span>
                    </div>

                    {/* Status + Actions */}
                    <div className="flex items-center justify-between pt-3 border-t">
                      <Badge 
                        variant={
                          u.status === "aktif" ? "default" :
                          u.status === "draft" ? "secondary" :
                          "outline"
                        }
                        className={cn(
                          "text-[10px] sm:text-xs px-2 py-0.5 font-medium",
                          u.status === "aktif" && "bg-green-100 text-green-700 hover:bg-green-100 border-green-200",
                          u.status === "draft" && "bg-orange-100 text-orange-700 hover:bg-orange-100 border-orange-200",
                          u.status === "selesai" && "bg-gray-100 text-gray-700 hover:bg-gray-100 border-gray-200"
                        )}
                      >
                        {u.status === "aktif" ? "Aktif" : u.status === "draft" ? "Draft" : "Selesai"}
                      </Badge>
                      <div className="flex gap-0.5 sm:gap-1">
                        <Button 
                          size="sm" 
                          variant="ghost"
                          onClick={() => router.push(`/guru/ujian/${u.id}`)}
                          className="h-7 w-7 sm:h-8 sm:w-8 p-0"
                        >
                          <Eye className="w-3.5 h-3.5 sm:w-4 sm:h-4" />
                        </Button>
                        <Button 
                          size="sm" 
                          variant="ghost"
                          onClick={() => router.push(`/guru/ujian/${u.id}/edit`)}
                          className="h-7 w-7 sm:h-8 sm:w-8 p-0"
                        >
                          <PencilSimple className="w-3.5 h-3.5 sm:w-4 sm:h-4" />
                        </Button>
                      </div>
                    </div>
                  </CardContent>
                </Card>
              ))}
            </div>
          )}
        </CardContent>
      </Card>

      {/* Modal Konfirmasi Hapus */}
      <AlertDialog open={showDeleteModal} onOpenChange={setShowDeleteModal}>
        <AlertDialogContent>
          <AlertDialogHeader>
            <AlertDialogTitle>Konfirmasi Hapus Ujian</AlertDialogTitle>
            <AlertDialogDescription>
              Apakah Anda yakin ingin menghapus ujian <span className="font-semibold">{selectedUjian?.judul}</span>?
              <br />
              <br />
              Tindakan ini tidak dapat dibatalkan. Semua data ujian, soal, dan jawaban siswa akan dihapus secara permanen.
            </AlertDialogDescription>
          </AlertDialogHeader>
          <AlertDialogFooter>
            <AlertDialogCancel onClick={() => setSelectedUjian(null)}>Batal</AlertDialogCancel>
            <AlertDialogAction
              onClick={handleDelete}
              className="bg-destructive text-destructive-foreground hover:bg-destructive/90"
            >
              Ya, Hapus
            </AlertDialogAction>
          </AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>

      {/* Modal Konfirmasi Publish */}
      <AlertDialog open={showPublishModal} onOpenChange={setShowPublishModal}>
        <AlertDialogContent>
          <AlertDialogHeader>
            <AlertDialogTitle>Konfirmasi Publikasi Ujian</AlertDialogTitle>
            <AlertDialogDescription>
              Apakah Anda yakin ingin mempublikasikan ujian <span className="font-semibold">{selectedUjian?.judul}</span>?
              <br />
              <br />
              Setelah dipublikasikan, ujian akan menjadi aktif dan dapat diakses oleh siswa. Pastikan semua soal sudah lengkap dan benar.
            </AlertDialogDescription>
          </AlertDialogHeader>
          <AlertDialogFooter>
            <AlertDialogCancel onClick={() => setSelectedUjian(null)}>Batal</AlertDialogCancel>
            <AlertDialogAction
              onClick={handlePublish}
              className="bg-primary text-primary-foreground hover:bg-primary/90"
            >
              Ya, Publikasikan
            </AlertDialogAction>
          </AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>
    </div>
  );
}
