// frontend/src/app/admin-guru/forgot-password/page.tsx
"use client";


import { fetchApi } from '@/lib/fetch-api';
import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { ArrowLeft, Mail, CheckCircle, Loader2 } from "lucide-react";
import Image from "next/image";
import { toast } from "sonner";

export default function ForgotPasswordPage() {
  const [email, setEmail] = useState("");
  const [isLoading, setIsLoading] = useState(false);
  const [sent, setSent] = useState(false);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();

    if (!email) {
      toast.error("Email harus diisi");
      return;
    }

    setIsLoading(true);
    try {
      const res = await fetchApi("/api/auth/forgot-password", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ email }),
      });

      const data = await res.json();

      if (data.success) {
        setSent(true);
      } else {
        toast.error(data.error || "Gagal mengirim email reset");
      }
    } catch {
      toast.error("Terjadi kesalahan");
    } finally {
      setIsLoading(false);
    }
  };

  if (sent) {
    return (
      <div className="min-h-screen flex items-center justify-center bg-[#0221CD] p-4">
        <Card className="w-full max-w-md shadow-xl">
          <CardContent className="flex flex-col items-center justify-center py-12">
            <div className="w-16 h-16 bg-green-100 rounded-full flex items-center justify-center mb-4">
              <CheckCircle className="w-8 h-8 text-green-600" />
            </div>
            <h2 className="text-lg font-semibold mb-2">Email Terkirim</h2>
            <p className="text-sm text-muted-foreground text-center mb-2 px-4">
              Jika email <strong>{email}</strong> terdaftar di sistem, kami telah mengirimkan link untuk mereset password Anda.
            </p>
            <p className="text-xs text-muted-foreground text-center mb-6 px-4">
              Periksa folder inbox dan spam email Anda. Link akan kadaluarsa dalam 1 jam.
            </p>
            <div className="flex flex-col gap-2 w-full px-4">
              <Button
                variant="outline"
                onClick={() => {
                  setSent(false);
                  setEmail("");
                }}
                className="w-full"
              >
                Kirim Ulang
              </Button>
              <a href="/admin-guru" className="w-full">
                <Button variant="ghost" className="w-full">
                  <ArrowLeft className="w-4 h-4 mr-2" />
                  Kembali ke Login
                </Button>
              </a>
            </div>
          </CardContent>
        </Card>
      </div>
    );
  }

  return (
    <div className="min-h-screen flex items-center justify-center bg-[#0221CD] p-4">
      <Card className="w-full max-w-md shadow-xl">
        <CardHeader className="space-y-1 text-center">
          <div className="flex justify-center mb-4">
            <div className="relative w-16 h-16">
              <Image
                src="/icon/logo-no-bg-png-blue.png"
                alt="E-Learning Logo"
                fill
                className="object-contain"
                priority
              />
            </div>
          </div>
          <CardTitle className="text-xl font-bold">Lupa Password</CardTitle>
          <CardDescription>
            Masukkan email Anda untuk menerima link reset password
          </CardDescription>
        </CardHeader>
        <CardContent>
          <form onSubmit={handleSubmit} className="space-y-4">
            <div className="space-y-2">
              <Label htmlFor="email">Email</Label>
              <div className="relative">
                <Mail className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-gray-400" />
                <Input
                  id="email"
                  type="email"
                  placeholder="Masukkan email Anda"
                  value={email}
                  onChange={(e) => setEmail(e.target.value)}
                  disabled={isLoading}
                  className="pl-10"
                  required
                />
              </div>
            </div>

            <Button
              type="submit"
              className="w-full text-white"
              disabled={isLoading || !email}
            >
              {isLoading ? (
                <>
                  <Loader2 className="w-4 h-4 mr-2 animate-spin" />
                  Mengirim...
                </>
              ) : (
                "Kirim Link Reset Password"
              )}
            </Button>

            <div className="text-center">
              <a href="/admin-guru" className="text-sm text-primary hover:underline inline-flex items-center gap-1">
                <ArrowLeft className="w-3 h-3" />
                Kembali ke Login
              </a>
            </div>
          </form>
        </CardContent>
      </Card>
    </div>
  );
}

// frontend-nuxt/pages/login-admin/forgot-password.vue
<template>
  <div class="min-h-screen flex items-center justify-center p-8" style="background-color: #f8f9fb;">
    <div class="w-full max-w-md">
      <div class="flex items-center justify-center gap-3 mb-8">
        <div class="w-12 h-12 bg-orange-100 rounded-xl flex items-center justify-center">
          <Icon name="lucide:graduation-cap" class="w-7 h-7 text-orange-600" />
        </div>
        <span class="text-2xl font-bold text-gray-900">Nilai Online</span>
      </div>

      <div class="bg-white rounded-2xl p-8 card-shadow">
        <!-- Success State -->
        <div v-if="sent" class="text-center">
          <div class="w-16 h-16 bg-green-100 rounded-full flex items-center justify-center mx-auto mb-4">
            <Icon name="lucide:mail-check" class="w-8 h-8 text-green-600" />
          </div>
          <h2 class="text-xl font-bold text-gray-900 mb-2">Email Terkirim</h2>
          <p class="text-gray-500 text-sm mb-6">
            Jika email terdaftar, kami telah mengirimkan link untuk reset password. Silakan cek inbox Anda.
          </p>
          <NuxtLink
            to="/login-admin"
            class="inline-flex items-center gap-2 text-sm text-orange-500 hover:text-orange-600 font-medium"
          >
            <Icon name="lucide:arrow-left" class="w-4 h-4" />
            Kembali ke Login
          </NuxtLink>
        </div>

        <!-- Form State -->
        <div v-else>
          <div class="text-center mb-8">
            <div class="w-14 h-14 bg-orange-100 rounded-full flex items-center justify-center mx-auto mb-4">
              <Icon name="lucide:key-round" class="w-7 h-7 text-orange-600" />
            </div>
            <h2 class="text-xl font-bold text-gray-900">Lupa Password?</h2>
            <p class="text-gray-500 mt-2 text-sm">
              Masukkan email Anda dan kami akan mengirimkan link untuk reset password.
            </p>
          </div>

          <form @submit.prevent="handleSubmit" class="space-y-5">
            <div class="space-y-2">
              <label class="text-sm font-medium text-gray-700">Email</label>
              <Input
                v-model="email"
                type="email"
                placeholder="Masukkan email Anda"
                icon="lucide:mail"
                size="lg"
                :disabled="isLoading"
              />
            </div>

            <Button
              type="submit"
              class="w-full"
              size="lg"
              :loading="isLoading"
            >
              Kirim Link Reset
            </Button>
          </form>

          <div class="mt-6 text-center">
            <NuxtLink
              to="/login-admin"
              class="inline-flex items-center gap-2 text-sm text-gray-500 hover:text-gray-700"
            >
              <Icon name="lucide:arrow-left" class="w-4 h-4" />
              Kembali ke Login
            </NuxtLink>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { toast } from 'vue-sonner'

definePageMeta({
  layout: 'default',
})

useHead({
  title: 'Lupa Password',
})

const email = ref('')
const isLoading = ref(false)
const sent = ref(false)

const handleSubmit = async () => {
  if (!email.value) {
    toast.error('Masukkan email Anda')
    return
  }

  isLoading.value = true
  try {
    const response = await fetchApi('/api/auth/forgot-password', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ email: email.value }),
    })

    const data = await response.json()

    if (data.success) {
      sent.value = true
    } else {
      toast.error(data.error || 'Terjadi kesalahan')
    }
  } catch (error) {
    console.error('Forgot password error:', error)
    toast.error('Terjadi kesalahan')
  } finally {
    isLoading.value = false
  }
}
</script>
